localization["jpn"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "ライザのアトリエ3 素材マップ",
		"Choose a language:": "言語:",
		"Choose a map:": "マップ:",
		"Kurken": "クーケン島",
		"Mainland": "クーケン島周辺地域",
		"Cleria": "クレリア地方",
		"Nemed": "ネメド地方",
		"Orim": "異界オーリム",
		"Code": "万象の大典",
		"Rosca": "ロスカ島",
		"Rosca Control Tower": "ロスカ島中央制御塔",
		"Ashra-am Baird Outskirts": "王都アスラ・アム・バート辺境",
		"Choose an item:": "素材:",
		"Filter Gathering Tool:": "採取道具:",
		"Hand Maximum Rank": "通常採取ランク",
		"None": "なし",
		"Rank One": "ランク1",
		"Rank Two": "ランク2",
		"Rank Three": "ランク3",
		"Rod Maximum Rank": "杖採取ランク",
		"Sickle Maximum Rank": "鎌採取ランク",
		"Axe Maximum Rank": "斧採取ランク",
		"Hammer Maximum Rank": "鎚採取ランク",
		"Net Maximum Rank": "網採取ランク",
		"Alchemy Mysteries DLC": "錬金術の神秘 DLC",
		"Art of Adventure DLC": "冒険の極意 DLC",
		"Search": "検索",
		"Number found:": "見つかった数:",
		"$1 in $2": "$1 in $2",
		"Hand Gathering": "通常採取",
		"Rod Gathering": "杖採取",
		"Sickle Gathering": "鎌採取",
		"Axe Gathering": "斧採取",
		"Hammer Gathering": "鎚採取",
		"Net Gathering": "網採取",
	},
	"item": {
		"Clean Water": "きれいな水",
		"Goats Milk": "ヤギミルク",
		"Water Bamboo": "貯水竹",
		"Plant Essence": "植物エキス",
		"Roteswasser Tonic": "ロテスヴァッサ鉱水",
		"Rapwar Water": "ラプワール水",
		"Foamy Water": "泡立つ水",
		"Jade Water": "翡翠の煌水",
		"Ancient Blue Water": "太古の蒼水",
		"Curious Aqua": "キュリオスアクア",
		"Black Water": "黒水",
		"Nameless Grass": "ナナシ草",
		"Wasser Wheat": "ヴァッサ麦",
		"Dry Grass": "コゲクサ",
		"Hill Lettuce": "丘レタス",
		"Blue Herb": "ブルーハーブ",
		"Rishikelp": "リシリコ",
		"Chomping Grass": "かみつき草",
		"Sweet Leaf": "スイートリーフ",
		"Ancient Branch": "古代樹の枝",
		"Campanula": "釣鐘草",
		"Glowing Diatom": "光珪藻",
		"Lucky Clover": "幸せクローバー",
		"Blue Clover": "アオツメクサ",
		"Light Absorbing Grass": "光吸草",
		"Rosen Leaf": "ローゼンリーフ",
		"Uni": "うに",
		"Ancient Uni": "古代うに",
		"Water Uni": "ミズうに",
		"Charcoal Uni": "炭うに",
		"Gold Uni": "黄金うに",
		"Demon Uni": "鬼いがうに",
		"Emperor Uni": "大王うに",
		"Health Flower": "病忘れの花",
		"Northern Wind Flower": "北風の花",
		"Sunny Honey Flower": "陽気な蜜花",
		"Bubble Grass": "シャボン草",
		"Stained Flower": "ステンドフラワー",
		"Caged Flower": "檻の妖花",
		"Spring Princess": "清水の白姫",
		"Soul Flower": "散命の花",
		"Rose Crystal": "ローズクリスタル",
		"Delphi Rose": "デルフィローズ",
		"Polar Cactus": "極地サボテン",
		"Timeteller": "トキシラセ",
		"Taun": "トーン",
		"Tall Taun": "セイタカトーン",
		"Sapling Branch": "若木の枝葉",
		"Medicinal Moss": "クスリゴケ",
		"Fertile Soil": "肥沃な土壌",
		"Dry Incense": "乾燥香",
		"Bitter Root": "苦い根っこ",
		"Crimson Grass": "紅草",
		"Earth's Secret Oils": "大地の秘油",
		"Sage Grass": "仙人草",
		"Life Leaf": "生命の大葉",
		"Refueling Extract": "リフュールエキス",
		"Yugdore Water": "ユグドールの湧水",
		"Stinky Trash": "生ごみ",
		"Mushroom Powder": "キノコパウダー",
		"Mispel Seed": "ミスペルシード",
		"Resentful Scream": "怨嗟の叫び",
		"Blessing of Delusion": "虚妄の祝福",
		"Dragon Flower": "リュウソウラン",
		"Demon Blood": "デモンブラッド",
		"Forest Sage": "森の賢人",
		"Celestial Tears": "天宮の涙",
		"Solflower": "太陽の花",
		"Dunkelheit": "ドンケルハイト",
		"Soft Sand": "やわらかい砂",
		"Burning Sand": "燃える砂",
		"Corail Saber": "コライユサーブル",
		"Polluted Humus": "汚染された腐葉土",
		"Emerald Glass": "エメラルドグラス",
		"Seafloor Soil": "水底の土",
		"Black Muck": "黒泥",
		"Vortex Sand": "渦巻く流砂",
		"Glittering Sand": "グリッターサンド",
		"Eroded Stone": "風化した石材",
		"Nectar Rock": "甘露岩",
		"Nepheline": "霞石",
		"Waterside Moss Stone": "水辺の苔石",
		"Ethereal Stone": "白霊岩",
		"Ancient Pillar": "古代の石柱",
		"Coral Stone": "サンゴ石",
		"Breeze Stone": "ブリーズストーン",
		"Riverstone": "リバーストン",
		"Blue Flame Riverstone": "リバーストン・蒼炎",
		"Hot Saltpeter": "熱硝石",
		"Arknite": "アークナイト",
		"Crimson Ore": "セキネツ鉱",
		"Aqua Ore": "アクア鉱",
		"Lightning Ore": "イナズマ鉱",
		"Wind Ore": "ヴィント鉱",
		"Amatite Ore": "アマタイト鉱",
		"Luminous Rock": "夜光岩",
		"Pentanite": "ペントナイト",
		"Mordenite": "モルディナイト",
		"Goldinite": "ゴルディナイト",
		"Degenesis Stone": "創生の逆さ石",
		"Septrin": "セプトリエン",
		"Adamant": "アダマント",
		"Eternal Crystal": "永遠結晶",
		"Small Crystals": "小さな晶石",
		"Unknown Gemstone": "正体不明の原石",
		"Glowing Coral": "ヒカリサンゴ",
		"White Shell Pearl": "大貝の白玉",
		"Black Shell Pearl": "大貝の黒玉",
		"Amber Fragment": "琥珀の欠片",
		"Amber Crystal": "琥珀水晶",
		"Three-Colored Stone": "三色混石",
		"Clear Branch": "クリアブランチ",
		"Holy Arbor Crystal": "聖樹結晶",
		"Underworld Crystal": "異界結晶",
		"Black Glitter Stone": "黒煌石",
		"Rainbow Gemstone": "七煌原石",
		"Dried Lumber": "乾いた木くず",
		"Flint Pepper": "フリントペッパー",
		"Explosive Vine": "炸裂カズラ",
		"Flaming Black Sand": "焔の黒砂",
		"Magma Powder": "マグマパウダー",
		"Scrap Paper": "紙くず",
		"Flammable Bark": "よく燃える樹皮",
		"Palma Bark": "パルマ樹皮",
		"Fuel Coconut": "フューエルココナッツ",
		"Natural Oil": "自然油",
		"Amber Oil": "琥珀油",
		"Fire and Ice Crystal": "炎氷結晶",
		"Eternal Fire": "常世の焔",
		"Beast Meat": "ケモノ肉",
		"Fresh Meat": "新鮮な肉",
		"Some Kind of Egg": "何かの卵",
		"Oil Tree Fruit": "アブラ木の実",
		"Nectar Fruit": "甘露の実",
		"Wild Potato": "ノライモ",
		"Portpea": "ポルト豆",
		"Red Devil": "赤い悪魔",
		"Clenoko": "クレノコ",
		"Red King Apple": "王玉",
		"Skull Pumpkin": "スカルパンプキン",
		"Venom Nut": "ヴェノムナット",
		"Palma Fruit": "パルマの実",
		"Fresh Berry": "フレスベリー",
		"Werder Nut": "ヴェルダーナッツ",
		"Kurken Fruit": "クーケンフルーツ",
		"Fortune Fruit": "フォーチュンフルーツ",
		"Rainbow Grapevine": "七色葡萄",
		"Summer Gem": "サマージェム",
		"Softtail": "ソフテール",
		"Beehive": "ハチの巣",
		"Silver Beehive": "銀のハチの巣",
		"Gold Beehive": "金のハチの巣",
		"Bee Haven": "ビーハイブン",
		"Honey Ball": "ハニーボール",
		"Eicheloa": "アイヒェロア",
		"Mushroom Colony": "群体きのこ",
		"Brodenbits": "ブローデンビッツ",
		"Utopiechampignon": "ユピトピニオン",
		"Jellyfish Mushroom": "クラゲ茸",
		"Stool of Nature": "ヒトノコシカケ",
		"Dusk Mushroom": "ヨルノキフジン",
		"Danger Mushroom": "ゲキヤバイタケ",
		"Jewel Mushroom": "宝晶セオイダケ",
		"Golden Crown": "ゴールデンクラウン",
		"Sardine": "サルディン",
		"Seriole": "セリヨル",
		"Pourpremoule": "プルムル",
		"Crab": "シュラブ",
		"Pretty Shells": "きれいな貝殻",
		"Spikey": "トゲトゲ",
		"Uni Starfish": "ウニヒトデ",
		"Chestnut": "くり",
		"Rainbow Fish": "虹魚",
		"Mace Fish": "メイスフィッシュ",
		"Stingray": "スティンレイ",
		"Myria Fish": "万年魚",
		"Lake Master": "湖底のぬし",
		"Dragonpalace Nautilus": "リュウグウオウムガイ",
		"Crown Shellfish": "王冠サザエ",
		"Imperial Fish": "皇魚",
		"Seven Stars": "ナナホシ",
		"Honey Ant": "ハニーアント",
		"Narwhal Grasshopper": "イッカクバッタ",
		"Lantern Fly": "灯篭ホタル",
		"Rose Bee": "ローズビー",
		"Giant Beetle": "オオカブト",
		"Baby Wyrm": "ベビーヴルム",
		"Crimson Cloak": "クリムゾンマント",
		"Spirit Isopod": "スピリト・モルグ",
		"Amber Fly": "アンバーフライ",
		"Lapis Papillion": "ラピス・パピヨン",
		"Trihorn": "トライホーン",
		"Ancient Bug": "王古虫",
		"Rock Schloss": "ロックシュロス",
		"Restraint Silk": "束縛する鋼糸",
		"Cotton Grass": "綿毛草",
		"Tough Vine": "丈夫なつる",
		"Arbor Ivy": "大木のツタ",
		"Queen Spider Web": "女王グモの巣",
		"Hug of Arachne": "アラクネの抱擁",
		"Eiche": "アイヒェ",
		"Tough Log": "丈夫な丸太",
		"Mossy Driftwood": "苔むした流木",
		"Holy Arbor Branch": "聖樹の大枝",
		"Palma": "パルマ",
		"Fossil Tree": "化石樹",
		"Miasma Log": "瘴気を放つ倒木",
		"Lightning Tree": "蓄雷樹",
		"Ancient Log": "太古の老木",
		"Millennial Tree": "千年樹の幼木",
		"Wing Plant": "ウィングプラント",
		"Smoke Signal Flower": "狼煙草",
		"Crispy Mushroom": "こんがりきのこ",
		"Sky Bubble": "スカイバブル",
		"Rotwood Miasma": "腐木の毒霧",
		"Water Holy Branch": "水聖樹の枝",
		"Dragon Breath": "火竜の吐息",
		"Fairystone Fragment": "魔石の欠片",
		"Dark Crystal Fragment": "闇水晶の欠片",
		"Holy Stone Fragment": "聖石の欠片",
		"Rainbow Wing Fragment": "虹翼の欠片",
		"Magic Tome Piece": "魔導書の切れ端",
		"Old Magic Tome": "古びた魔導書",
		"Holy Tree Leaf": "聖樹の葉",
		"Mystic Sphere": "フロートスフィア",
		"Ancient Fossil": "古代生物の化石",
		"Forever Ice Block": "永久氷塊",
		"Decayed Iron Pieces": "朽ちた鉄片",
		"Rusted Sword": "サビついた剣",
		"Broken Tools": "壊れた道具",
		"Liquid Metal": "液体金属",
		"Ancient Sword": "古の闘剣",
		"Blue Puniball": "ぷにぷに玉・青",
		"Green Puniball": "ぷにぷに玉・緑",
		"Red Puniball": "ぷにぷに玉・赤",
		"Black Puniball": "ぷにぷに玉・黒",
		"Silver Puniball": "ぷにぷに玉・銀",
		"Gold Puniball": "ぷにぷに玉・金",
		"Animal Hide": "動物の毛皮",
		"Mythical Hide": "幻獣の毛皮",
		"Large Bone": "大きな骨",
		"Beast Fossil": "巨獣の化石",
		"Water Beast Fossil": "水獣の巨大化石",
		"Water Beast Scale": "水獣のウロコ",
		"Cave Bat Wing": "洞窟コウモリの羽",
		"White Swallow's Nest": "白ツバメの古巣",
		"Beast Fin": "魔獣の背びれ",
		"Beast Shell": "魔獣の甲殻",
		"Beast Scales": "魔獣のウロコ",
		"Giant Bird Feather": "巨鳥の風切羽",
		"Giant Bird Egg": "巨鳥の大卵",
		"Goat Horn": "ヤギ角",
		"Demon Claws": "魔爪",
		"Fluffy Wool": "モフモフウール",
		"Poison Needle": "毒の細針",
		"Dragon Wing": "翼竜の翼",
		"Dragon Egg": "翼竜の卵",
		"Dragon Eye": "竜眼",
		"Dragon Bone": "竜骨",
		"Dragon Meat": "竜肉",
		"Guardian Armor": "守護者の堅甲",
		"Heroic Spirit": "英霊の魂",
		"Giant Puniball": "大ぷに玉",
		"Fairy Horn Adornment": "妖精の大角飾り",
		"Giant Claws": "巨大な爪",
		"Golem Core": "ゴーレムコア",
		"Inverted Scale": "逆鱗",
		"Ether Core": "エーテルコア",
		"Imp's Lost Item": "小悪魔の落とし物",
		"Elemental Force": "エレメントフォース",
		"Twisted Thorns": "絡みつく根",
		"Curved Long Nails": "湾曲した長爪",
		"Running Beast Crest": "走獣のトサカ",
		"Phantom Color Tail": "幻色尾",
		"Wolf Beast's Blade": "狼獣の狩刃",
		"Duet Stock Solution": "ドゥエット原液",
		"Scintilla Ore": "シンティラ鉱石",
		"Lujada's Fairystone": "ルジャーダの魔石",
		"Pink Puniball": "ぷにぷに玉・桜",
		"Giant Kurken Fruit": "巨大クーケンフルーツ",
		"Cow Milk": "ウシミルク",
		"Giant Claws": "巨大な爪",
		"White Swallow's Nest": "白ツバメの古巣",
		"Water Beast Scale": "水獣のウロコ",
		"Mythical Hide": "幻獣の毛皮",
		"Dragon Meat": "竜肉",
		"Heroic Spirit": "英霊の魂",
		"Dragon Wing": "翼竜の翼",
		"Demon Claws": "魔爪",
		"Dragon Bone": "竜骨",
		"Dragon Eye": "竜眼",
		"Ether Core": "エーテルコア",
		"Myria Fish": "万年魚",
		"Summer Gem": "サマージェム",
		"Spring Princess": "清水の白姫",
		"Giant Beetle": "オオカブト",
		"Corail Saber": "コライユサーブル",
		"Celestial Tears": "天宮の涙",
		"Sky Bubble": "スカイバブル",
		"Rainbow Fish": "虹魚",
		"Red Devil": "赤い悪魔",
		"Chomping Grass": "かみつき草",
		"Solflower": "太陽の花",
		"Dark Crystal Fragment": "闇水晶の欠片",
		"Campanula": "釣鐘草",
		"Earth's Secret Oils": "大地の秘油",
		"Softtail": "ソフテール",
		"Dunkelheit": "ドンケルハイト",
		"Emperor Uni": "大王うに",
		"Light Absorbing Grass": "光吸草",
		"Black Muck": "黒泥",
		"Fire and Ice Crystal": "炎氷結晶",
		"Seal Branch": "シールグレイン",
		"Old Dragon's Claw": "古竜の鉤爪",
		"Water Stone": "水環石",
		"Silence Steel": "サイレスチル",
		"Verdant Moonflower": "深緑の月華",
		"Heavenly Seawater": "天海水",
		"Clearfish": "六花魚",
		"Pine Fruit": "ホウリの実",
		"Melocotone": "メロコトーン",
		"Star Clam": "ほししじみ",
		"Gemeater": "ジェムイータ",
		"Tsurugi Mushroom": "ツルギタケ",
		"Floating Petal Stone": "浮上花石",
		"Verdeum Metal": "ベルデウム金属",
		"Wool Flower": "風乗りの花",
		"Cleaner Plant": "ラルコ草",
		"Medicinal Sap": "薬樹液",
		"Immortal Sapling": "不朽の杣木",
		"Blessed Clouds": "恵みの綿雲",
		"Carved Relic": "木彫りの遺物",
		"Reaper's Scythe": "死神の大鎌",
		"Heavenly Rain Thread": "天梅雨の糸",
		"Unstable Lump": "不安定な塊",
		"Ignis Nut": "イグニスナッツ",
		"Ancient Scroll": "古風なスクロール",
		"Torch of the Ages": "千古の灯火",
		"Royal Spun Thread": "王家の紡糸",
		"White Sand of Eternity": "久遠の白砂",
		"Traveling Grass": "旅する枯草",
		"White Sand Metal": "白砂金属",
		"Ametrite": "アメトライト",
		"Forgotten Pottery": "遺却された陶器",
		"Desert Cleaner": "砂漠の掃除屋",
		"Trifruit": "トライフルーツ",
		"Cactus Blossom": "サボタン",
		"Mortal Anima": "モータルアニマ",
		"Shark Bone": "ティブロボーン",
		"Exotic Meat": "珍味な肉",
		"Kala's Translated Texts (Copy)": "カラの翻訳文献・写し",
		"Golden Puniball": "ぷにぷに玉・黄金",
		"Sandstorm Crystal": "砂嵐の結晶",
		"White Moon's Soul": "白月の魂",
		"Universe Sphere": "ユニバースフィア",
		"Fairywood": "フェアリーバオム",
		"Mini Volcano": "リーテンボルケ",
		"Seven-Color Pansy": "七色ビオラ",
		"Fairy Sapling": "妖精の苗木",
		"Lava Rock": "ラーヴァローク",
		"Moon Fragment": "月のフラグメント",
	},
	"monster": {
		"Blue Puni": "青ぷに",
		"Green Puni": "緑ぷに",
		"Red Puni": "赤ぷに",
		"Flower Puni": "花ぷに",
		"Black Puni": "黒ぷに",
		"Silver Puni": "シルバーぷに",
		"Gold Puni": "ゴールドぷに",
		"Lavender Puni": "ラベンダーぷに",
		"Big Puni": "でかぷに",
		"Shining Puni": "シャイニングぷに",
		"Rafflesia Puni": "ラフレシアぷに",
		"Darkness Puni": "ダークネスぷに",
		"Precious Puni": "プレシャスぷに",
		"Giant Weasel": "オオイタチ",
		"Bluefin": "ブルーフィン",
		"Silky Fur": "シルキーファー",
		"Scarf Bunny": "スカーフバニー",
		"Night Hunter": "ナイトハンター",
		"Ruined Corrupter": "ルインコラプター",
		"Hide Stalker": "ハイドストーカー",
		"Loppy Ear": "ロップイヤー",
		"Mother Weasel": "オオイタチマザー",
		"Savage Assassin": "サベージアサシン",
		"Hex Rabbit": "ヘクスラビット",
		"Large Antler": "ラージアントラー",
		"Holy Beast of the Stars": "星の聖獣",
		"Flower Pixie": "花の精",
		"Illuminated Sylph": "イルミネイトシルフ",
		"Flower Gardener": "フラワーガーデナー",
		"Zephyr Pixie": "ゼファーピクシー",
		"Eternal Guardian": "悠久の守り手",
		"Blazing Maiden": "光熱の乙女",
		"Hallowed Spirit": "ホーリースピリット",
		"Plumed Lorelei": "プルームローレライ",
		"Elder Fairy": "エルダーフェアリー",
		"Mirage Master": "幻を司る者",
		"Lunaria Angel": "ルナリアエンゼル",
		"Nightmare Spirit": "悪夢の精",
		"Schwarzwraith": "シュヴァルツレイス",
		"Sweet Nocturnal ": "スイートノクターナル",
		"Moon Veil": "ムーンヴェイル",
		"Stone Golem": "ストーンゴーレム",
		"Rock Puppet": "ロックパペット",
		"Jewel Guard": "ジュエルガード",
		"Fairystone Puppet": "魔石の傀儡",
		"Metal Golem": "メタルゴーレム",
		"Meteorite Doll": "メテオライトドール",
		"Earth Master": "土塊の使役者",
		"Rusty Onyx": "ラスティオニキス",
		"Colossus Golem": "コロッサスゴーレム",
		"Eternal Sculpture": "不朽の彫像",
		"Boulder Soldier": "巨石の兵士",
		"Darkomaton": "ダークマタ",
		"Noir Doll": "ノワールドール",
		"Cramberry": "クラムベリー",
		"Harvest Prayer": "豊穣を祈る者",
		"Horned Sheep": "つのひつじ",
		"Ashen Wool": "アッシュウール",
		"Fluffy Sheep": "フラッフィーシープ",
		"Dreamcatcher": "ドリームキャッチャー",
		"Giant Sheep": "きょだいひつじ",
		"Mindlurker": "暗い思い出の獣",
		"Mad Beast": "マッドビースト",
		"Scaled Armadillo": "スケイルアルマジロ",
		"Intact Carapace": "インタクトカラパス",
		"Tiny Devil": "タイニーデビル",
		"Blue Fiend": "ブルーフィーンド",
		"Hot Evil": "ホットイービル",
		"Ash Demon": "アッシュデーモン",
		"King Devil": "ダイアクマ",
		"Storm Elemental ": "ストームエレメンタル",
		"Icy Crystal": "アイシークリスタル",
		"Spirit of Nature": "自然の精霊",
		"Scrambled Energy": "スクランブルエナジー",
		"Disaster Core": "ディザスターコア",
		"Earth Plant": "アースプラント",
		"Root Spreader": "ルートスプレッダー",
		"Great Tree Messenger": "大樹の使い",
		"Great Mistread": "グリームミストルード",
		"Yggdrasil": "ユグドラシル",
		"Rageness": "レイジネス",
		"Ground Builder": "グランドビルダー",
		"Ruler of the Forest": "森の支配者",
		"Spark Riser": "スパークライザー",
		"Giant Sloth": "巨大ナマケモノ",
		"Feral Crow": "フェラルクロウ",
		"Smart Ripper": "スマートリッパー",
		"Ferocious Hopper": "バッダスホッパー",
		"Fierce Hunter": "獰猛たる狩人",
		"Tyrant": "タイラント",
		"Living Armor": "動く甲冑",
		"Ghost Armor": "ゴーストアーマー",
		"Honor Guard Armor": "亡国の近衛鎧",
		"Gladiator": "グラディエーター",
		"Legendary Warrior": "伝承の古強者",
		"Immortal Knight": "イモータルナイト",
		"Royal Admiral": "ロイヤルアドミラル",
		"Heavy Warrior Armor": "戦士の大鎧",
		"Noble Paladin": "ノーブルパラディン",
		"Great Guardian": "グレートガーディアン",
		"Demonic Phantom": "幻影の幽鬼",
		"Berserker Shadow": "狂戦士の影",
		"Temple Warrior": "テンプルウォーリアー",
		"Shattered Breaker": "シャタードブレイカー",
		"Stinger": "スティンガー",
		"Sharpened Scissors": "シャープシザーズ",
		"Pile Bunker": "パイルバンカー",
		"Parching Demon": "渇きの悪魔",
		"Dark Scout": "常闇の斥候",
		"Spine Rat": "スパインラット",
		"Ogre Head": "オーガヘッド",
		"Shadow Vanguard": "影の尖兵",
		"Thrust Hedge": "スラストヘッジ",
		"Shadow Eater": "シャドウイーター",
		"Legion Needle": "レジオンニードル",
		"Mini Wyvern": "ミニワイバーン",
		"Zephyr Feather": "ウィンドフェザー",
		"Evil Orchis": "イービルオーキス",
		"Stout Drake": "ファットドレイク",
		"Mach Hawk": "マッハホーク",
		"Watcher": "ウォッチャー",
		"Draconic Lord": "ドラゴニックロード",
		"Giant Maw": "ジャイアントモー",
		"Mega Wyvern": "メガワイバーン",
		"King of Storms": "キングオブストーム",
		"Cloud Liner": "クラウドライナー",
		"Landbound Dragon": "地縛竜",
		"Cursed Wing": "呪われた翼",
		"Armored Wing": "アーマーウィング",
		"Steel Raptor": "鋼の猛禽",
		"Sprinting Bird": "スプリントバード",
		"Massive Beak": "マッシブビーク",
		"Albatross": "アルバトロス",
		"Wild Crest": "ワイルドクレスト",
		"Overwhelming Bird": "狂奔する怪鳥",
		"Twilight Songbird": "宵鳴鳥",
		"Lifeless Shadow": "亡き巨鳥の影",
		"Twilight Assassin": "宵闇の刺客",
		"Cloak-in-dagger": "クロークインダガー",
		"Shadow Assassin ": "影の暗殺者",
		"Cipher Code": "サイファーコード",
		"Hell Keeper": "地獄の番人",
		"Slashblader": "スラッシュブレイダー",
		"Crimson Arms": "クリムゾンアームズ",
		"Spellblade Wielder": "魔剣の遣い手",
		"Demon Slayer Wolf": "破邪の月狼",
		"Sleipnir": "スレイプニル",
		"Hide Shark": "ハイドシャーク",
		"Megamouth": "大顎鮫",
		"Spinal Fin": "スピネルフィン",
		"Grand Tusk": "グランタスカー",
		"Sandstorm Tyrant": "砂塵の暴君",
		"Desert Lagoon": "デザートラグーン",
		"Mind Ravager": "思念の捕食者",
		"Land Crawler": "大地を這う大魚",
		"Soul Cleaver": "ソウルクリーバー",
		"Dark General": "常闇の将軍",
		"Cluster Beetle": "クラストビートル",
		"Shadow Commander": "影の司令",
		"Horned Demon": "ホーンデーモン",
		"Rhino Fiend": "ライノフィーンド",
		"Old Castle Dragon": "古城の翼竜",
		"Dragon Lord": "天統べる覇竜",
		"Dragon of Light": "闇を裂く光竜",
		"Ravaging Queen": "常闇の女王",
		"Queen of Shadows": "影の女王",
		"Crownless Queen": "無冠の女王",
		"Floating Skeleton": "浮遊する骸",
		"Skeleton Emperor ": "スケルトンエンペラー",
		"Automaton": "オートマトン",
		"Sentry Guard": "セントリーガード",
		"Elder Treant": "エルダートレント",
		"Ancient Dragon": "エンシェントドラゴン",
		"Deranged King": "狂気の王",
		"Gatekeeper": "ゲートキーパー",
		"Code of the Universe": "万象の大典",
		"Code of the Universe - Final": "万象の大典・終章",
		"Colossus Soldier": "巨像の兵士",
		"Code of the Universe (Arm)": "万象の大典・腕",
		"Weasel Roast": "ラムロースト２号",
		"Lamb Roast": "ラムロースト３号",
		"Orig. Code of the Universe": "万象の原典",
		"Orig. Code of the Universe (Arm)": "万象の原典・腕",
	}
}