localization["cht"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "萊莎的鍊金工房3 素材分布查詢",
		"Choose a language:": "選擇語言：",
		"Choose a map:": "選擇地圖：",
		"Kurken": "庫肯島",
		"Mainland": "庫肯島周邊地區",
		"Cleria": "克萊莉亞地區",
		"Nemed": "內米德地區",
		"Orim": "異界奧靈",
		"Code": "萬象大典",
		"Choose an item:": "選擇道具：",
		"Filter Gathering Tool:": "篩選採集工具：",
		"Hand Maximum Rank": "空手等級",
		"None": "無",
		"Rank One": "等級1",
		"Rank Two": "等級2",
		"Rank Three": "等級3",
		"Rod Maximum Rank": "手杖等級",
		"Sickle Maximum Rank": "鐮刀等級",
		"Axe Maximum Rank": "斧頭等級",
		"Hammer Maximum Rank": "錘子等級",
		"Net Maximum Rank": "捕捉網等級",
		"Alchemy Mysteries DLC": "DLC 鍊金術之神秘",
		"Art of Adventure DLC": "DLC 冒險之精髓",
		"Search": "搜尋",
		"Number found:": "尋找結果：",
		"$1 in $2": "$2有 $1 處",
		"Hand Gathering": "空手採集",
		"Rod Gathering": "手杖採集",
		"Sickle Gathering": "鐮刀採集",
		"Axe Gathering": "斧頭採集",
		"Hammer Gathering": "錘子採集",
		"Net Gathering": "捕捉網採集",
	},
	"item": {
		"Clean Water": "乾淨的水",
		"Goats Milk": "山羊奶",
		"Water Bamboo": "儲水竹",
		"Plant Essence": "植物精華",
		"Roteswasser Tonic": "羅德士瓦瑟礦水",
		"Rapwar Water": "梨花水",
		"Foamy Water": "起泡水",
		"Jade Water": "翡翠煌水",
		"Ancient Blue Water": "太古蒼水",
		"Curious Aqua": "神秘液體",
		"Black Water": "黑水",
		"Nameless Grass": "無名草",
		"Wasser Wheat": "瓦塞麥",
		"Dry Grass": "焦草",
		"Hill Lettuce": "丘陵萵苣",
		"Blue Herb": "藍色香草",
		"Rishikelp": "利西利藻",
		"Chomping Grass": "咬人草",
		"Sweet Leaf": "甜葉",
		"Ancient Branch": "古樹枝",
		"Campanula": "吊鐘草",
		"Glowing Diatom": "光矽藻",
		"Lucky Clover": "幸運四葉草",
		"Blue Clover": "藍詰草",
		"Light Absorbing Grass": "吸光草",
		"Rosen Leaf": "玫瑰葉",
		"Uni": "海膽",
		"Ancient Uni": "古代海膽",
		"Water Uni": "水海膽",
		"Charcoal Uni": "炭海膽",
		"Gold Uni": "黃金海膽",
		"Demon Uni": "鬼角海膽",
		"Emperor Uni": "大王海膽",
		"Health Flower": "忘憂花",
		"Northern Wind Flower": "北風之花",
		"Sunny Honey Flower": "陽氣蜜花",
		"Bubble Grass": "肥皂草",
		"Stained Flower": "彩光之花",
		"Caged Flower": "樹籠妖花",
		"Spring Princess": "清水白姫",
		"Soul Flower": "散命花",
		"Rose Crystal": "玫瑰水晶",
		"Delphi Rose": "德爾福玫瑰",
		"Polar Cactus": "極地仙人掌",
		"Timeteller": "報時花",
		"Taun": "通草",
		"Tall Taun": "長頸通草",
		"Sapling Branch": "幼樹枝葉",
		"Medicinal Moss": "藥苔",
		"Fertile Soil": "肥沃土壤",
		"Dry Incense": "乾燥香",
		"Bitter Root": "苦根",
		"Crimson Grass": "紅草",
		"Earth's Secret Oils": "大地秘油",
		"Sage Grass": "仙人草",
		"Life Leaf": "生命葉片",
		"Refueling Extract": "補給精華",
		"Yugdore Water": "優古多爾的湧水",
		"Stinky Trash": "廚餘",
		"Mushroom Powder": "蘑菇孢子",
		"Mispel Seed": "歐楂種子",
		"Resentful Scream": "怨嗟悲鳴",
		"Blessing of Delusion": "虛妄祝福",
		"Dragon Flower": "龍葬蘭",
		"Demon Blood": "惡魔之血",
		"Forest Sage": "森林智草",
		"Celestial Tears": "天宮之淚",
		"Solflower": "太陽花",
		"Dunkelheit": "一夜花",
		"Soft Sand": "軟砂",
		"Burning Sand": "可燃之砂",
		"Corail Saber": "珊瑚砂",
		"Polluted Humus": "受污染的腐葉土",
		"Emerald Glass": "翡翠玻璃",
		"Seafloor Soil": "水底土",
		"Black Muck": "黑泥",
		"Vortex Sand": "漩渦流砂",
		"Glittering Sand": "閃耀砂粒",
		"Eroded Stone": "風化石材",
		"Nectar Rock": "甘露岩",
		"Nepheline": "霞石",
		"Waterside Moss Stone": "水邊苔石",
		"Ethereal Stone": "白靈岩",
		"Ancient Pillar": "古代石柱",
		"Coral Stone": "珊瑚石",
		"Breeze Stone": "微風石",
		"Riverstone": "河石",
		"Blue Flame Riverstone": "河石‧蒼炎",
		"Hot Saltpeter": "熱硝石",
		"Arknite": "方舟夜石",
		"Crimson Ore": "赤熱礦",
		"Aqua Ore": "海藍石礦",
		"Lightning Ore": "閃電礦",
		"Wind Ore": "風礦",
		"Amatite Ore": "赤鐵礦",
		"Luminous Rock": "夜光岩",
		"Pentanite": "派恩特夜石",
		"Mordenite": "毛爾迪夜石",
		"Goldinite": "戈爾迪夜石",
		"Degenesis Stone": "創生逆石",
		"Septrin": "聖石",
		"Adamant": "金剛石",
		"Eternal Crystal": "永恆結晶",
		"Small Crystals": "小晶石",
		"Unknown Gemstone": "未知的原石",
		"Glowing Coral": "發光珊瑚",
		"White Shell Pearl": "大貝白珍珠",
		"Black Shell Pearl": "大貝黑珍珠",
		"Amber Fragment": "琥珀碎片",
		"Amber Crystal": "琥珀水晶",
		"Three-Colored Stone": "三色石",
		"Clear Branch": "清瑩樹枝",
		"Holy Arbor Crystal": "聖樹結晶",
		"Underworld Crystal": "異界結晶",
		"Black Glitter Stone": "黑煌石",
		"Rainbow Gemstone": "七煌原石",
		"Dried Lumber": "乾燥木屑",
		"Flint Pepper": "燧石胡椒",
		"Explosive Vine": "炸裂藤",
		"Flaming Black Sand": "焰之黑砂",
		"Magma Powder": "岩漿粉",
		"Scrap Paper": "紙屑",
		"Flammable Bark": "易燃樹皮",
		"Palma Bark": "帕爾馬樹皮",
		"Fuel Coconut": "燃料椰子",
		"Natural Oil": "天然油",
		"Amber Oil": "琥珀油",
		"Fire and Ice Crystal": "炎冰結晶",
		"Eternal Fire": "永世之焰",
		"Beast Meat": "獸肉",
		"Fresh Meat": "新鮮的肉",
		"Some Kind of Egg": "未知的蛋",
		"Oil Tree Fruit": "油木果實",
		"Nectar Fruit": "甘露果實",
		"Wild Potato": "野生馬鈴薯",
		"Portpea": "波多豆",
		"Red Devil": "紅惡魔",
		"Clenoko": "餘暉筍",
		"Red King Apple": "王玉蘋果",
		"Skull Pumpkin": "顱骨南瓜",
		"Venom Nut": "猛毒果",
		"Palma Fruit": "帕爾馬果實",
		"Fresh Berry": "莓果",
		"Werder Nut": "森林核果",
		"Kurken Fruit": "庫肯果",
		"Fortune Fruit": "幸運果實",
		"Rainbow Grapevine": "七色葡萄",
		"Summer Gem": "夏季寶石",
		"Softtail": "柔軟奶油果",
		"Beehive": "蜂巢",
		"Silver Beehive": "銀色蜂巢",
		"Gold Beehive": "金色蜂巢",
		"Bee Haven": "疊層蜂蜜塊",
		"Honey Ball": "蜜蜂球巢",
		"Eicheloa": "橡樹菇",
		"Mushroom Colony": "群生蘑菇",
		"Brodenbits": "布羅登皮特菇",
		"Utopiechampignon": "尤皮特齒菇",
		"Jellyfish Mushroom": "水母菇",
		"Stool of Nature": "椅菇",
		"Dusk Mushroom": "暗夜貴婦人",
		"Danger Mushroom": "極其危險菇",
		"Jewel Mushroom": "寶晶塞歐伊菇",
		"Golden Crown": "金色王冠",
		"Sardine": "沙丁魚",
		"Seriole": "黃尾魚",
		"Pourpremoule": "普魯姆魯螺",
		"Crab": "灌木蟹",
		"Pretty Shells": "美麗貝殼",
		"Spikey": "刺刺魚",
		"Uni Starfish": "海膽海星",
		"Chestnut": "栗子",
		"Rainbow Fish": "彩虹魚",
		"Mace Fish": "釘錘魚",
		"Stingray": "汙濁魟魚",
		"Myria Fish": "萬年魚",
		"Lake Master": "湖底之主",
		"Dragonpalace Nautilus": "龍宮鸚鵡螺",
		"Crown Shellfish": "王冠海螺",
		"Imperial Fish": "皇魚",
		"Seven Stars": "七星蟲",
		"Honey Ant": "蜜蟻",
		"Narwhal Grasshopper": "獨角蚱蜢",
		"Lantern Fly": "燈籠螢火蟲",
		"Rose Bee": "玫瑰蜂",
		"Giant Beetle": "甲蟲",
		"Baby Wyrm": "幼虹蟲",
		"Crimson Cloak": "緋紅斗篷",
		"Spirit Isopod": "靈團蟲",
		"Amber Fly": "琥珀飛蟲",
		"Lapis Papillion": "娜匹斯蝶",
		"Trihorn": "三角甲蟲",
		"Ancient Bug": "王古蟲",
		"Rock Schloss": "岩城蟹",
		"Restraint Silk": "鋼化蛛絲",
		"Cotton Grass": "綿毛草",
		"Tough Vine": "強韌藤蔓",
		"Arbor Ivy": "大樹常春藤",
		"Queen Spider Web": "女王蜘蛛網",
		"Hug of Arachne": "阿拉克妮的擁抱",
		"Eiche": "橡木",
		"Tough Log": "結實的圓木",
		"Mossy Driftwood": "長苔蘚的漂流木",
		"Holy Arbor Branch": "聖樹大枝",
		"Palma": "帕爾馬木",
		"Fossil Tree": "化石樹",
		"Miasma Log": "釋放瘴氣的倒木",
		"Lightning Tree": "蓄雷樹",
		"Ancient Log": "太古老柴",
		"Millennial Tree": "千年樹幼樹",
		"Wing Plant": "翼葉草",
		"Smoke Signal Flower": "狼煙草",
		"Crispy Mushroom": "焦菇",
		"Sky Bubble": "天空泡沫",
		"Rotwood Miasma": "朽木毒霧",
		"Water Holy Branch": "水聖樹樹枝",
		"Dragon Breath": "火龍吐息",
		"Fairystone Fragment": "魔石碎片",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Holy Stone Fragment": "聖石碎片",
		"Rainbow Wing Fragment": "虹翼碎片",
		"Magic Tome Piece": "魔導書殘頁",
		"Old Magic Tome": "陳舊的魔導書",
		"Holy Tree Leaf": "聖樹葉",
		"Mystic Sphere": "漂浮球體",
		"Ancient Fossil": "古代生物化石",
		"Forever Ice Block": "永恆冰塊",
		"Decayed Iron Pieces": "鏽蝕鐵片",
		"Rusted Sword": "生鏽的劍",
		"Broken Tools": "壞掉的道具",
		"Liquid Metal": "液態金屬",
		"Ancient Sword": "古老鬥劍",
		"Blue Puniball": "噗尼噗尼珠‧藍",
		"Green Puniball": "噗尼噗尼珠‧綠",
		"Red Puniball": "噗尼噗尼珠‧紅",
		"Black Puniball": "噗尼噗尼珠‧黑",
		"Silver Puniball": "噗尼噗尼珠‧銀",
		"Gold Puniball": "噗尼噗尼珠‧金",
		"Animal Hide": "動物毛皮",
		"Mythical Hide": "幻獸毛皮",
		"Large Bone": "大骨",
		"Beast Fossil": "巨獸化石",
		"Water Beast Fossil": "水獸巨大化石",
		"Water Beast Scale": "水獸鱗片",
		"Cave Bat Wing": "洞窟蝙蝠翅膀",
		"White Swallow's Nest": "白燕舊巢",
		"Beast Fin": "魔獸背鰭",
		"Beast Shell": "魔獸甲殼",
		"Beast Scales": "魔獸鱗片",
		"Giant Bird Feather": "巨鳥破風羽",
		"Giant Bird Egg": "巨鳥蛋",
		"Goat Horn": "山羊角",
		"Demon Claws": "魔爪",
		"Fluffy Wool": "柔軟羊毛",
		"Poison Needle": "劇毒細針",
		"Dragon Wing": "翼龍之翼",
		"Dragon Egg": "翼龍之蛋",
		"Dragon Eye": "龍之眼",
		"Dragon Bone": "龍骨",
		"Dragon Meat": "龍肉",
		"Guardian Armor": "守護者硬甲",
		"Heroic Spirit": "英靈之魂",
		"Giant Puniball": "大噗尼珠",
		"Fairy Horn Adornment": "妖精的大角飾",
		"Giant Claws": "巨大的爪子",
		"Golem Core": "魔巨人核心",
		"Inverted Scale": "逆鱗",
		"Ether Core": "乙太核",
		"Imp's Lost Item": "小惡魔的遺失物",
		"Elemental Force": "元素之力",
		"Twisted Thorns": "交纏之根",
		"Curved Long Nails": "彎曲長爪",
		"Running Beast Crest": "走獸肉冠",
		"Phantom Color Tail": "幻色尾",
		"Wolf Beast's Blade": "狼獸的獵刃",
		"Duet Stock Solution": "二重奏原液",
		"Scintilla Ore": "火花礦石",
		"Lujada's Fairystone": "露水魔石",
		"Pink Puniball": "噗尼噗尼珠‧櫻",
		"Giant Kurken Fruit": "巨大庫肯果",
		"Cow Milk": "牛奶",
		"Thick Reference Book": "厚重的參考書",
		"Giant Claws": "巨大的爪子",
		"White Swallow's Nest": "白燕舊巢",
		"Water Beast Scale": "水獸鱗片",
		"Mythical Hide": "幻獸毛皮",
		"Dragon Meat": "龍肉",
		"Heroic Spirit": "英靈之魂",
		"Dragon Wing": "翼龍之翼",
		"Demon Claws": "魔爪",
		"Dragon Bone": "龍骨",
		"Dragon Eye": "龍之眼",
		"Spirit Catalysts": "精靈觸媒",
		"Ether Core": "乙太核",
		"Spirit Catalysts": "精靈觸媒",
		"Guiding Bird Feather": "引導之鳥的羽毛",
		"Gnade Ring": "恩典戒指",
		"Phantom Scarf": "幻影絲巾",
		"Chick Doll": "小雞布偶",
		"Myria Fish": "萬年魚",
		"Summer Gem": "夏季寶石",
		"Spring Princess": "清水白姫",
		"Giant Beetle": "甲蟲",
		"Corail Saber": "珊瑚砂",
		"Celestial Tears": "天宮之淚",
		"Sky Bubble": "天空泡沫",
		"Rainbow Fish": "彩虹魚",
		"Red Devil": "紅惡魔",
		"Chomping Grass": "咬人草",
		"Solflower": "太陽花",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Campanula": "吊鐘草",
		"Earth's Secret Oils": "大地秘油",
		"Softtail": "柔軟奶油果",
		"Dunkelheit": "一夜花",
		"Emperor Uni": "大王海膽",
		"Light Absorbing Grass": "吸光草",
		"Black Muck": "黑泥",
		"Fire and Ice Crystal": "炎冰結晶",
		"Explosive Uni": "爆裂海膽",
		"Craft": "卡夫",
		"Bomb": "炎燒",
		"Ice Bomb": "冰精",
		"Plajig": "雷球",
		"Luft": "風精",
		"Trio Craft": "卡夫三重奏",
		"Anemo Bomb": "銀蓮花炎燒",
		"Melting Ice Bomb": "雪融冰精",
		"Lia Plajig": "雷球罐",
		"Edle Luft": "高貴風精",
		"Lunar Lamp": "夜月燈",
		"Astro Rose": "玫瑰枝",
		"Lavinage": "活雪結晶",
		"Grazeit": "閃耀時光",
		"Himmel Feather": "天國羽毛",
		"Forbidden Spell Book": "禁忌秘術書",
		"Zwei Resonance": "雙重共振",
		"Cross Judgement": "十字審判",
		"Sourcebook of Acacia": "金合歡原典",
		"Grass Beans": "草豆",
		"Dry Biscuit": "餅乾",
		"Nectar": "瓊漿玉液",
		"Elixir": "萬靈藥劑",
		"Hermit Ointment": "隱者軟膏",
		"Fairy Elixir": "妖精秘藥",
		"Mist of Silence": "靜寂輕霧",
		"Golden Heart": "黃金之心",
		"Mythic Nectar": "神話瓊漿玉液",
		"Eternal Holy Grail": "永劫回歸之聖杯",
		"Fish Oil": "液化魚油",
		"War Powder": "金創粉",
		"Energianica": "形意口琴",
		"Mystic Robe": "神秘的羽衣",
		"Miracle Ebonyal": "黑檀妖藥",
		"Astronomical Clock": "時空天文鐘",
		"Fake Bouquet": "虛假花束",
		"Haze Breath": "霧霾吐息",
		"Prison of Decline": "衰勢牢獄",
		"Barbaric Horn Whistle": "蠻勇角笛",
		"Depiction of a Devil": "惡魔的肖像畫",
		"Hourglass of Origin": "起源砂漏",
		"Cantera of Calamity": "災厄油燈",
		"Prelude of the Gods": "眾神的前奏曲",
		"Call of Abyss": "深淵呼喚",
		"Grass Sickle": "割草鐮刀",
		"Silent Sickle": "寂靜鐮刀",
		"Woodcutter's Axe": "劈柴斧",
		"Golden Axe": "黃金之斧",
		"Hammer": "錘子",
		"Ravage Hammer": "毀滅之錘",
		"Fishing Rod": "釣竿",
		"Divine Fishing Rod": "神竿慈悲",
		"Catcher's Net": "捕捉網",
		"Master Catcher's Net": "高手捕捉網",
		"Wind Shoes": "風精靈之靴",
		"Emerald Band": "綠寶石光帶",
		"Air Drop": "水中氣囊",
		"Summoner's Bell": "召喚師之鈴",
		"Red Neutralizer": "中和劑‧紅",
		"Blue Neutralizer": "中和劑‧藍",
		"Yellow Neutralizer": "中和劑‧黃",
		"Green Neutralizer": "中和劑‧綠",
		"Rainbow Neutralizer": "中和劑‧七彩",
		"Honey": "蜂蜜",
		"Berry Syrup": "莓果糖漿",
		"Flour": "麵粉",
		"Devil's Breath": "惡魔吐息",
		"Puppet Liquid": "傀儡液",
		"Super Pure Water": "超純水",
		"Traveler's Water Orb": "旅人的水珠",
		"Medica Powder": "藥粉",
		"Doctor's Bottle": "藥草瓶",
		"Holy Drop": "神聖水滴",
		"Taboo Drop": "禁忌水滴",
		"Zettel": "查科爾帖紙",
		"Reinforced Zettel": "強化查科爾帖紙",
		"Pearl Crystal": "珍珠核水晶",
		"Amberlite": "琥珀晶石",
		"Spirinite": "精神夜石",
		"Waking Emerald": "覺醒翡翠",
		"Arc en Ciel": "七光寶石",
		"Dark Glittering Oval": "煌黑勾玉",
		"Nitro Chips": "硝基片",
		"Donour Powder": "雷粉",
		"Blue Flame Ember": "蒼炎火種",
		"Mixing Oil": "混合油",
		"Flint Charcoal": "打火炭",
		"Colorful Oil": "彩色油",
		"Solid Ice Fuel": "可燃冰",
		"Feather Draft": "輕羽水晶",
		"Ingot": "金屬塊",
		"Startium": "星鐵礦",
		"Creaminea": "創生鐵礦",
		"Goldoterion": "金塊",
		"Grand Orgen": "閃耀鋼塊",
		"Alchemy Fibers": "鍊金纖維",
		"Himmel Schulwa": "天絲",
		"Eternal Firo": "永恆之絲",
		"Cloth": "布料",
		"Bestial Air": "獸布",
		"Sorcery Rose": "巫術玫瑰布",
		"Royal Cloth": "皇家布料",
		"Sage Coat": "賢者皮料",
		"Puni Leather": "噗尼皮甲",
		"Master Leather": "大師皮甲",
		"Dread Leather": "恐懼皮革",
		"Grace Nero": "黑色恩惠",
		"Philosopher's Stone": "賢者之石",
		"Olden Philosopher's Stone": "古代賢者之石",
		"Honey Crystal": "蜜結晶",
		"Glass Flower": "玻璃花",
		"Wind Crystal Ball": "風晶玉",
		"Growing Quartz": "成長水晶",
		"Spirit Bottle": "精靈的小瓶",
		"Crystal Element": "核水晶元素",
		"Poisonous Liquid": "毒液",
		"The Grim Reaper": "死神劇毒",
		"Polishing Powder": "研磨劑",
		"Rose Perfume": "玫瑰香水",
		"Spring Wind Pinwheel": "春風風車",
		"Luft Atomizer": "風精噴霧器",
		"Exotic Lantern": "異國燈籠",
		"Four Seasons Dome": "四季球",
		"Magna Mater": "地母板",
		"Polishing Sand": "研磨砂",
		"Marblestone": "大理石",
		"Eternal Monolith": "悠久磐石",
		"Plant Seeds": "植物種子",
		"Stone Seeds": "石之種子",
		"Fire Seeds": "火之種子",
		"Water Seeds": "水之種子",
		"Mystic Seeds": "神秘種子",
		"Poison Seeds": "毒之種子",
		"Golden Seeds": "金色種子",
		"Duet Solvent Solution": "二重奏溶劑",
		"Fairystone Compass": "魔石指針",
		"Scintilla Glass": "火花玻璃",
		"Lujada Crystals": "露水結晶",
		"Glass Goblet": "玻璃高腳杯",
		"Fairystone Pendant": "魔石墜飾",
		"Hollow Key": "虛空鑰匙",
		"The Starting Key": "初始鑰匙",
		"Castle Door Key": "城門鑰匙",
		"Blockade Key": "封鎖區域鑰匙",
		"Key of Honor": "榮譽鑰匙",
		"Pristine Key": "純淨鑰匙",
		"Red Stone Key": "赤石鑰匙",
		"Blue Stone Key": "青石鑰匙",
		"Yellow Stone Key": "黃石鑰匙",
		"Green Stone Key": "綠石鑰匙",
		"Red Iron Key": "紅鐵鑰匙",
		"Blue Iron Key": "蒼鐵鑰匙",
		"Orange Iron Key": "橙鐵鑰匙",
		"Jade Iron Key": "碧鐵鑰匙",
		"White Silver Key": "白銀鑰匙",
		"Golden Key": "黃金鑰匙",
		"Rainbow Key": "虹剛晶鑰匙",
		"Red Wing Key": "朱羽鑰匙",
		"Blue Wing Key": "藍羽鑰匙",
		"Light Wing Key": "光羽鑰匙",
		"Leaf Wing Key": "葉羽鑰匙",
		"Scarlet Wing Key": "緋翼鑰匙",
		"Cloud Wing Key": "雲翼鑰匙",
		"Wing Key": "閃翼鑰匙",
		"Tree Wing Key": "樹翼鑰匙",
		"Firebird Key": "鳳凰鑰匙",
		"Phoenix Key": "不死鳥鑰匙",
		"Phantom Wing Key": "幻翼支配者鑰匙",
		"Fire Gear Key": "火輪鑰匙",
		"Water Gear Key": "水輪鑰匙",
		"Gear Key": "齒輪鑰匙",
		"Wind Gear Key": "風輪鑰匙",
		"Fire Clock Key": "火鐘鑰匙",
		"Water Clock Key": "水鐘鑰匙",
		"Hourglass Key": "砂鐘鑰匙",
		"Gear Gimmick Key": "齒輪機關鑰匙",
		"Key to the Future": "未來鑰匙",
		"Key to the Past": "過去鑰匙",
		"Key of All Times": "時空統治者鑰匙",
		"Key of Bright Sky": "明空鑰匙",
		"Key of Blue Sky": "蒼空鑰匙",
		"Key of Twilight Sky": "暮空鑰匙",
		"Key of Night Sky": "夜空鑰匙",
		"Scarlet Key": "緋星鑰匙",
		"Dark Star Key": "暗星鑰匙",
		"Bright Star Key": "輝星鑰匙",
		"Meteor Key": "流星鑰匙",
		"Great Heavens Key": "大天陽鑰匙",
		"Moon Shadow Key": "小月影鑰匙",
		"Soul Cradle Key": "靈魂搖籃鑰匙",
		"Key of Truth": "真實鑰匙",
		"Key of the End": "終結鑰匙",
		"Shining Key": "發光鑰匙",
		"Alchemist's Staff": "鍊金術士之杖",
		"Svate Rod": "光輝短杖",
		"Celestial Seeker": "冰藍弦月杖",
		"Sparkling Reverie": "閃耀夢想",
		"Agnes Luce": "貞潔光杖",
		"Ciel Shoot": "擊空之弓",
		"Yale Soar": "翅翼飛弓",
		"Croiselt": "十叉之弓",
		"Astrumnox": "暗夜星矢",
		"Astral Regalia": "星辰徽章",
		"Smite Blade": "重擊之劍",
		"Sword of Rupture": "破離劍",
		"Lord Guardian": "疆土守護者",
		"Demon Ender": "惡魔終結者",
		"Liese Divider": "誓裂者",
		"Sharp Edge": "鋒利之刃",
		"Paradiera": "天堂紀元",
		"Luna Solis": "日月雙劍",
		"Amphisbaena": "雙頭龍牙劍",
		"Ifestio": "火山雙刃",
		"Aristoclite": "貴族長刀",
		"Herzog": "公爵長刀",
		"Might of Heaven": "神威",
		"Edel Schwert": "愛瑟爾劍",
		"Efflorescence": "白華綻放",
		"Wise Wand": "睿智權杖",
		"Educator": "教育者",
		"Occult Wisdom": "幽玄睿智之杖",
		"Nachfolger": "繼承者",
		"Genesis Staff": "創世輝杖",
		"Trisker": "三痕裂爪",
		"Aurora": "極光幻爪",
		"Oren Herald": "幽藍爪",
		"Ventiska": "飛雪夜爪",
		"Nevernoche": "迷霧闇夜",
		"Onyx Blade": "縞瑪瑙刀",
		"Lysil Edge": "里迪爾之劍",
		"Baron's Light": "豪族之光",
		"Unfold": "示展長劍",
		"Lost Alucard": "失落阿爾卡多",
		"Iron Fan": "鐵扇",
		"Purple Orchid": "紫蘭",
		"Scarlet Heaven": "緋天",
		"Jing Qing Fan": "景清扇",
		"Shrine Maiden's Dance": "巫女神樂",
		"Wild Axe": "狂野之斧",
		"Daybreak": "黎明之斧",
		"Estacado": "奮力一搏",
		"Elde Divide": "裂地戰斧",
		"Diamantis": "璀璨鑽石",
		"Moon Quake": "月震之錘",
		"Crepusclype": "暮光之罪",
		"Gravimarius": "重力武錘",
		"Elder Lily": "百合長老",
		"Raventoad": "部落復興",
		"Mistral Cane": "寒風之杖",
		"Etoile Filant": "流星之弓",
		"Hashbringer": "碎斬大劍",
		"Vita Reaper": "生命收割者",
		"Folklore": "民謠金刀",
		"Windword": "風之言",
		"Crimson Mist": "緋紅霧爪",
		"Void Punisher": "虛無制裁者",
		"Self-defense Fans": "護身扇",
		"Brute Veil": "赤血面紗",
		"Solmarkt": "太陽王國",
		"Noble Tunic": "尊貴外衣",
		"Leather Protector": "護身皮甲",
		"Bone Armor": "骸骨鎧甲",
		"Mage's Robe": "術者長袍",
		"Soldier's Cuirass": "士兵鐵甲",
		"Radiant Plate": "光輝板甲",
		"Fairy Cloak": "妖精羽衣",
		"Chainmail Cloak": "鎖鏈大衣",
		"Foreign Armor": "異國盔甲",
		"Elven Robe": "精靈法衣",
		"Moonlight Cloak": "月影外套",
		"Dragoon Mail": "龍騎兵鎧甲",
		"Kruger Cloak": "聰慧大衣",
		"Meuchelmolder": "刺客大衣",
		"Armanoir": "黑魂盔甲",
		"Uni Charm": "海膽掛飾",
		"Energy Pendant": "能量墜飾",
		"Gnade Ring": "恩典戒指",
		"Phantom Scarf": "幻影絲巾",
		"Locket of Devotion": "奉獻相框墜",
		"Migratory Charm": "候鳥護身符",
		"Quartz Necklace": "石英項鍊",
		"Warlock Ring": "術士戒指",
		"Warrior Bangle": "鬥士手環",
		"Clairvoyance Monocle": "千里眼鏡片",
		"Harnal Ring": "靈巧戒指",
		"Warrior Choker": "軍師頸鍊",
		"Four Spirits Amulet": "四精靈護身符",
		"Cluster Cuffs": "聚合袖扣",
		"Baron's Crown": "男爵冠",
		"Dragon Scale Necklace": "龍鱗首飾",
		"Broken Hoe": "斷掉的鋤頭",
		"Light and Sturdy Hoe": "輕巧堅固的鋤頭",
		"Fairystone Light": "魔石光源",
		"Fairystone Light EX": "魔石光源‧改",
		"Scruffy Drawing": "拙劣的構造圖",
		"Flame Hair Clip": "火炎髮簪",
		"Hammer Brooch": "錘形胸針",
		"Duet Stock Solution+": "高濃度二重奏原液",
		"Duet Solvent Solution EX": "二重奏溶劑‧改",
		"Seeds of Light": "光之種",
		"Seeds of Light EX": "光之種‧改",
		"Disturbing Bell": "干擾鈴",
		"Emil's Tablet": "埃米爾之石盤",
		"Emil's Book": "埃米爾之書",
		"True Silver": "真銀",
		"Chart of Another Sky": "異空界圖",
		"Fi's Necklace": "菲的項鍊",
		"Shiny Necklace": "亮晶晶項鍊",
		"Dancing Bird Pinwheel": "舞鳥風車",
		"Silver Crystal": "真銀結晶體",
		"Celestial Globe of Another Sky": "異空天球儀",
		"High Quality Wood": "高品質木材",
		"Sturdy Wood": "堅固的加工木材",
		"Broken Ancient Artifact": "損壞的古式神器",
		"New Purifier": "新‧淨化裝置",
		"Broken Light": "壞掉的燈具",
		"Lamp of the Beginning": "起源燈",
		"Age of God Manual": "機械教科書神話時代之章",
		"Dragon Bone Fragment": "龍骨碎片",
		"Ancient Dragon Gem": "古龍寶石",
		"Indestructible Box": "不朽箱",
		"Auxiliary Prosthesis": "輔助義手",
		"Wild Meat on the Bone": "狂野帶骨肉",
		"Father's Album": "父親的圖稿集",
		"Desalination Equipment EX": "淡水化裝置‧改",
		"Iridescent Mucus": "彩虹色黏液",
		"Iridescent High-Purity Mucus": "彩虹色的高純度黏液",
		"High Quality Coral Stone": "高品質珊瑚石",
		"&quot;Agnes Luce&quot; Recipe": "「貞潔光杖」的配方",
		"&quot;Astral Regalia&quot; Recipe": "「星辰徽章」的配方",
		"&quot;Ifestio&quot; Recipe": "「火山雙刃」的配方",
		"&quot;Efflorescence&quot; Recipe": "「白華綻放」的配方",
		"&quot;Genesis Staff&quot; Recipe": "「創世輝杖」的配方",
		"&quot;Nevernoche&quot; Recipe": "「迷霧闇夜」的配方",
		"&quot;Lost Alucard&quot; Recipe": "「失落阿爾卡多」的配方",
		"&quot;Shrine Maiden's Dance&quot; Recipe": "「巫女神樂」的配方",
		"&quot;Diamantis&quot; Recipe": "「璀璨鑽石」的配方",
		"&quot;Raventoad&quot; Recipe": "「部落復興」的配方",
		"Federica's Pendant": "菲德麗卡的墜飾",
		"Small Tablet": "小石板",
		"&quot;Glassware&quot; Recipe": "「玻璃製品」的配方",
		"&quot;Fairystone Wares&quot; Recipe": "「魔石製品」的配方",
		"&quot;Iridescent High-Purity Mucus&quot; Recipe": "「彩虹色的高純度黏液」的配方",
		"&quot;Scintilla Glass&quot; Recipe": "「火花玻璃」的配方",
		"&quot;Lujada Crystal&quot; Recipe": "「露水結晶」的配方",
		"&quot;Fairystone Light&quot; Recipe": "「魔石光源」的配方",
		"&quot;Pristine Key&quot; Recipe": "「純淨鑰匙」的配方",
		"&quot;Disturbing Bell&quot; Recipe": "「干擾鈴」的配方",
		"&quot;Seeds of Light EX&quot; Recipe": "「光之種‧改」的配方",
		"&quot;Emil's Tablet&quot; Recipe": "「埃米爾之石盤」的配方",
		"&quot;Duet Solvent Solution EX&quot; Recipe": "「二重奏溶劑‧改」的配方",
		"&quot;Fairystone Compass&quot; Recipe": "「魔石指針」的配方",
		"&quot;Hammer Brooch&quot; Recipe": "「錘形胸針」的配方",
		"&quot;Flame Hair Clip&quot; Recipe": "「火炎髮簪」的配方",
		"&quot;Shiny Necklace&quot; Recipe": "「亮晶晶項鍊」的配方",
		"&quot;Dancing Bird Pinwheel&quot; Recipe": "「舞鳥風車」的配方",
		"&quot;Silver Crystal&quot; Recipe": "「真銀結晶體」的配方",
		"&quot;Globe of Another Sky&quot; Recipe": "「異空天球儀」的配方",
		"&quot;Light and Sturdy Hoe&quot; Recipe": "「輕巧堅固的鋤頭」的配方",
		"&quot;Puppet Liquid&quot; Recipe": "「傀儡液」的配方",
		"&quot;Flint Charcoal&quot; Recipe": "「打火炭」的配方",
		"&quot;Solid Ice Fuel&quot; Recipe": "「可燃冰」的配方",
		"&quot;Four Seasons Dome&quot; Recipe": "「四季球」的配方",
		"&quot;Mage's Robe&quot; Recipe": "「術者長袍」的配方",
		"&quot;Soldier's Cuirass&quot; Recipe": "「士兵鐵甲」的配方",
		"&quot;Radiant Plate&quot; Recipe": "「光輝板甲」的配方",
		"&quot;Elven Robe&quot; Recipe": "「精靈法衣」的配方",
		"&quot;Moonlight Cloak&quot; Recipe": "「月影外套」的配方",
		"&quot;Dragoon Mail&quot; Recipe": "「龍騎兵鎖子甲」的配方",
		"&quot;Summoner's Bell&quot; Recipe": "「召喚師之鈴」的配方",
		"&quot;Sturdy Wood&quot; Recipe": "「堅固的加工木材」的配方",
		"&quot;New Purifier&quot; Recipe": "「新‧淨化裝置」的配方",
		"&quot;Lamp of the Beginning&quot; Recipe": "「起源燈」的配方",
		"&quot;Age of God Manual&quot; Recipe": "「機械教科書神話時代之章」的配方",
		"&quot;Ancient Dragon Gem&quot; Recipe": "「古龍寶石」的配方",
		"&quot;Indestructible Box&quot; Recipe": "「不朽箱」的配方",
		"&quot;Wild Meat on the Bone&quot; Recipe": "「狂野帶骨肉」的配方",
		"&quot;Desalination Equipment EX&quot; Recipe": "「淡水化裝置‧改」的配方",
		"&quot;Grace Nero&quot; Recipe": "「黑色恩惠」的配方",
		"&quot;Two-handed Staff&quot; Recipe": "「雙手杖」的配方",
		"&quot;Bow&quot; Recipe": "「弓」的配方",
		"&quot;Great Sword&quot; Recipe": "「大劍」的配方",
		"&quot;Double Sword&quot; Recipe": "「雙劍」的配方",
		"&quot;Long Sword&quot; Recipe": "「長刀」的配方",
		"&quot;Single-handed Staff&quot; Recipe": "「單手杖」的配方",
		"&quot;Claw&quot; Recipe": "「鉤爪」的配方",
		"&quot;Single-handed Sword&quot; Recipe": "「單手劍」的配方",
		"&quot;Fan&quot; Recipe": "「扇子」的配方",
		"&quot;Axe&quot; Recipe": "「斧頭」的配方",
		"&quot;War Hammer&quot; Recipe": "「錘子」的配方",
		"&quot;Legendary Sword&quot; Recipe": "「歷經百戰的名劍」的配方",
		"&quot;Plant Seeds&quot; Recipe": "「植物種子」的配方",
		"&quot;Stone Seeds&quot; Recipe": "「石之種子」的配方",
		"&quot;Fire Seeds&quot; Recipe": "「火之種子」的配方",
		"&quot;Water Seeds&quot; Recipe": "「水之種子」的配方",
		"&quot;Mystic Seeds&quot; Recipe": "「神秘種子」的配方",
		"&quot;Poison Seeds&quot; Recipe": "「毒之種子」的配方",
		"&quot;Golden Seeds&quot; Recipe": "「金色種子」的配方",
		"Packed Rice": "炸彈飯",
		"Roasted Chicken": "火烤雞肉串",
		"Gibier Burger": "野味漢堡",
		"Mixed Sandwich": "輕便總匯三明治",
		"Smoked Meat": "冒險者製煙燻肉",
		"Dried Meat Pizza": "肉乾起司披薩",
		"Fresh Fish Carpaccio": "冷盤生魚片",
		"Summer Veggie Stew": "夏季蔬菜鍋",
		"Forest Green Pasta": "森林青醬麵",
		"Seafood Paella": "海鮮燉飯",
		"Red Chili Soup": "紅辣椒湯",
		"Steak on Crystal": "結晶板煎肉排",
		"Roasted Monster Fish": "烤怪魚",
		"Beef Omelette Rice": "牛肉醬蛋包飯",
		"White Sauce Ragu": "白醬燉菜",
		"Observing Hut": "觀測小屋",
		"Farm": "農園",
		"Laboratory": "研究所",
		"Room Extension 1": "擴建房間1",
		"Room Extension 2": "擴建房間2",
		"Build Observing Hut": "建造觀測小屋",
		"Build Lookout": "建造瞭望台",
		"Build Windmill": "建造風車",
		"Build Greenhouse": "建造溫室",
		"Build Celestial Globe": "建造天球儀",
		"Build Laboratory": "建造研究所",
		"Rebuild (Observing Hut)": "改建（觀測小屋）",
		"Rebuild (Farm)": "改建（農園）",
		"Rebuild (Laboratory)": "改建（研究所）",
		"Chick Doll": "小雞布偶",
		"Crystal Object": "水晶裝飾品",
		"Fairy Doll": "妖精布偶",
		"Puni Jelly": "噗尼果凍",
		"Puni Doll": "噗尼布偶",
		"Exhibition Stand": "展示台",
		"Hanging Lantern": "燈籠裝飾",
		"Round Table": "圓桌",
		"Leather Sofa": "皮革沙發",
		"Chic Sofa": "典雅的沙發",
		"Elegant Low Table": "高級的矮桌",
		"Pendulum Clock": "擺鐘",
		"Piano": "鋼琴",
		"Cute Bed": "可愛的床鋪",
		"Extravagant Bed": "豪華的床鋪",
		"Barrel": "木桶",
		"Fashionable Bench": "時髦的長凳",
		"Garden Table": "庭園桌",
		"Potted Plant": "彩花盆栽",
		"Oren Doll": "歐蘭族布偶",
		"Dinner Bell": "晚餐鈴",
		"Decorative Sword": "大劍裝飾",
		"Resort Bed": "渡假勝地的床鋪",
		"Resort Sofa": "渡假勝地的沙發",
		"Table with Tablecloth": "附桌巾的桌子",
		"Potted Palm": "棕櫚盆栽",
		"Music Stand": "譜架",
		"Giant Manuscript": "巨大抄本",
		"Pixie Pot": "小妖精的盆栽",
		"Great Elemental's Chair": "大精靈的椅子",
		"Celestial Body Model": "浮游天球",
		"Farm Photo": "農村的照片",
		"Countryside Photo": "鄉村的照片",
		"Rocking Chair": "搖椅",
		"Cute Sofa": "可愛的沙發",
		"Blackboard": "黑板",
		"Blacksmith Statue": "武器工匠的雕像",
		"Goat": "山羊",
		"Crisp Bun": "烤吐司",
		"Pumpkin Doll": "南瓜布偶",
		"Globe": "地球儀",
		"Transport Cannon": "送貨用大砲",
		"Ashra Donut": "阿斯拉甜甜圈",
		"Giant Luceaux Seed": "巨大龍子果",
		"Mountain of Sweets": "點心山",
		"Exotic Horn": "異國角笛",
		"Apple Basket": "蘋果籃",
		"Knight's Armor": "騎士盔甲",
		"Teddy Bear": "泰迪熊",
		"Beautiful Picture Frame": "精緻的相框",
		"Mysterious Broom": "神奇掃帚",
		"Phonograph": "留聲機",
		"Weasel Doll": "鼬的布偶",
		"Shiny Bust": "輝煌胸像",
		"Sparkling Bust": "閃耀胸像",
		"Photo of the Capital": "王都的照片",
		"Fi Doll": "菲布偶",
		"Candy House": "糖果屋",
		"Mini Cork Board": "迷你軟木板",
		"Books And Bookends": "書與書擋",
		"Tea Set": "茶具組",
		"Synthesis Eqp Set": "調合器材組",
		"Basket of Uni": "海膽山",
		"Mushroom Shaped Lamp": "菌菇造型燈",
		"Small Devil Doll": "小惡魔布偶",
		"Downwind": "順風鏢",
		"Rainbow Lapis": "七彩石",
		"Cerberus Spirit": "三頭犬之靈",
		"Draconic Arrow": "龍之箭",
		"Maleficus": "邪惡飛刀",
		"Calamity Code": "災禍暗碼",
		"Sugar Drip": "砂糖之滴",
		"Eternal Spring": "永恆藥泉",
		"Suonare": "奏響之器",
		"Voltage Liberator": "熱力釋放",
		"Windsong Fowl": "閱風鳥像",
		"Bell of Tranquility": "沉靜之鈴",
		"Lovely Blossom": "迷人花朵",
		"Neutronenstern": "中子星",
		"Violet Cauldron": "紫黑色大壺",
		"Seal Branch": "封印樹枝",
		"Old Dragon's Claw": "古龍鉤爪",
		"Water Stone": "水環石",
		"Silence Steel": "靜寂金屬",
		"Verdant Moonflower": "深綠之月華",
		"Heavenly Seawater": "天海水",
		"Clearfish": "六花魚",
		"Pine Fruit": "鵬梨果實",
		"Melocotone": "桃色岩鹽",
		"Star Clam": "星形蜆",
		"Gemeater": "食寶石蟲",
		"Tsurugi Mushroom": "劍菇",
		"Floating Petal Stone": "漂浮花石",
		"Verdeum Metal": "碧綠金屬",
		"Wool Flower": "乘風之花",
		"Cleaner Plant": "消毒草",
		"Medicinal Sap": "藥樹液",
		"Immortal Sapling": "不朽林木",
		"Blessed Clouds": "恩惠積雲",
		"Carved Relic": "木雕遺物",
		"Reaper's Scythe": "死神大鐮",
		"Heavenly Rain Thread": "天梅雨之絲",
		"Unstable Lump": "不穩定的聚合體",
		"Ignis Nut": "火焰毬果",
		"Ancient Scroll": "古風卷軸",
		"Edelhard": "高貴之心",
		"Medica Solution": "醫藥溶液",
		"Toxited": "赤毒液",
		"Jelly Sandwich": "果凍砂",
		"Crimson Birth": "緋紅降生",
		"Riot Coal": "爆燃石炭",
		"Vajra Wire": "金剛線",
		"Lumiere Potpourri": "聖光香料",
		"Ideal Unit": "理想元件",
		"Dragon's Tears": "龍之淚",
	},
	"monster": {
		"Blue Puni": "藍噗尼",
		"Green Puni": "綠噗尼",
		"Red Puni": "紅噗尼",
		"Flower Puni": "花噗尼",
		"Black Puni": "黑噗尼",
		"Silver Puni": "銀噗尼",
		"Gold Puni": "金噗尼",
		"Lavender Puni": "薰衣草噗尼",
		"Big Puni": "巨大噗尼",
		"Shining Puni": "發光噗尼",
		"Rafflesia Puni": "大王花噗尼",
		"Darkness Puni": "暗黑噗尼",
		"Precious Puni": "珍奇噗尼",
		"Giant Weasel": "大鼬",
		"Bluefin": "藍鰭鼬",
		"Silky Fur": "柔滑皮鼬",
		"Scarf Bunny": "圍巾兔",
		"Night Hunter": "暗夜獵人",
		"Ruined Corrupter": "毀滅的侵蝕者",
		"Hide Stalker": "暗地追跡者",
		"Loppy Ear": "垂耳兔",
		"Mother Weasel": "大鼬媽媽",
		"Savage Assassin": "野性刺客",
		"Hex Rabbit": "咒術兔",
		"Large Antler": "巨大鹿角",
		"Holy Beast of the Stars": "星辰聖獸",
		"Flower Pixie": "花精",
		"Illuminated Sylph": "微光靈者",
		"Flower Gardener": "護花園丁",
		"Zephyr Pixie": "微風仙子",
		"Eternal Guardian": "悠久守護者",
		"Blazing Maiden": "光熱少女",
		"Hallowed Spirit": "聖光靈體",
		"Plumed Lorelei": "羽毛女妖",
		"Elder Fairy": "妖精長老",
		"Mirage Master": "控幻者",
		"Lunaria Angel": "月光天使",
		"Nightmare Spirit": "惡夢之靈",
		"Schwarzwraith": "黑色巨靈",
		"Sweet Nocturnal ": "美好之夜",
		"Moon Veil": "月之面紗",
		"Stone Golem": "硬石魔巨人",
		"Rock Puppet": "石傀儡",
		"Jewel Guard": "寶石衛兵",
		"Fairystone Puppet": "魔石傀儡",
		"Metal Golem": "金屬魔巨人",
		"Meteorite Doll": "隕石魔偶",
		"Earth Master": "土塊使役者",
		"Rusty Onyx": "鏽瑪瑙巨魔",
		"Colossus Golem": "巨像魔巨人",
		"Eternal Sculpture": "不朽雕像",
		"Boulder Soldier": "巨石士兵",
		"Darkomaton": "暗黑魔巨人",
		"Noir Doll": "漆黑魔偶",
		"Cramberry": "蔓越莓",
		"Harvest Prayer": "祈求豐收者",
		"Horned Sheep": "角綿羊",
		"Ashen Wool": "灰毛綿羊",
		"Fluffy Sheep": "柔毛綿羊",
		"Dreamcatcher": "捕夢者",
		"Giant Sheep": "巨大綿羊",
		"Mindlurker": "灰暗回憶之獸",
		"Mad Beast": "狂暴猛獸",
		"Scaled Armadillo": "鱗甲犰狳",
		"Intact Carapace": "完美甲殼",
		"Tiny Devil": "迷你惡魔",
		"Blue Fiend": "藍惡魔",
		"Hot Evil": "炙熱惡魔",
		"Ash Demon": "灰惡魔",
		"King Devil": "大惡魔",
		"Storm Elemental ": "風暴元素",
		"Icy Crystal": "寒冰水晶",
		"Spirit of Nature": "自然精靈",
		"Scrambled Energy": "能量爭奪者",
		"Disaster Core": "災難核心",
		"Earth Plant": "大地草",
		"Root Spreader": "根莖傳播者",
		"Great Tree Messenger": "大樹使者",
		"Great Mistread": "閃霧狂暴",
		"Yggdrasil": "世界樹",
		"Rageness": "怠惰者",
		"Ground Builder": "大地建築工",
		"Ruler of the Forest": "森林支配者",
		"Spark Riser": "閃耀統籌者",
		"Giant Sloth": "巨大樹懶",
		"Feral Crow": "兇猛鉤爪",
		"Smart Ripper": "狡猾開膛手",
		"Ferocious Hopper": "卑鄙跳躍者",
		"Fierce Hunter": "凶猛獵人",
		"Tyrant": "狂怒暴君",
		"Living Armor": "移動盔甲",
		"Ghost Armor": "鬼魂鎧甲",
		"Honor Guard Armor": "亡國的近衛鎧",
		"Gladiator": "角鬥士",
		"Legendary Warrior": "傳承古強者",
		"Immortal Knight": "不朽騎士",
		"Royal Admiral": "皇家上將",
		"Heavy Warrior Armor": "戰士的大鎧",
		"Noble Paladin": "貴族聖騎士",
		"Great Guardian": "偉大守護者",
		"Demonic Phantom": "幻影幽鬼",
		"Berserker Shadow": "狂戰士之影",
		"Temple Warrior": "神殿戰士",
		"Shattered Breaker": "粉碎破壞者",
		"Stinger": "毒刺",
		"Sharpened Scissors": "銳剪",
		"Pile Bunker": "貫釘",
		"Parching Demon": "旱季惡魔",
		"Dark Scout": "常闇斥候",
		"Spine Rat": "脊柱鼠",
		"Ogre Head": "巨獸首領",
		"Shadow Vanguard": "魅影尖兵",
		"Thrust Hedge": "猛刺之蝟",
		"Shadow Eater": "食影者",
		"Legion Needle": "針山刺蝟",
		"Mini Wyvern": "迷你雙足飛龍",
		"Zephyr Feather": "風羽",
		"Evil Orchis": "惡魔蘭龍",
		"Stout Drake": "大肚龍",
		"Mach Hawk": "馬赫飛翼",
		"Watcher": "守望者",
		"Draconic Lord": "飛龍領主",
		"Giant Maw": "巨咽龍",
		"Mega Wyvern": "巨型雙足飛龍",
		"King of Storms": "風暴之王",
		"Cloud Liner": "雲端行者",
		"Landbound Dragon": "地縛龍",
		"Cursed Wing": "詛咒之翼",
		"Armored Wing": "鎧甲之翼",
		"Steel Raptor": "鋼鐵猛禽",
		"Sprinting Bird": "快跑鳥",
		"Massive Beak": "巨喙鳥",
		"Albatross": "信天翁",
		"Wild Crest": "野生大冠雞",
		"Overwhelming Bird": "狂奔怪鳥",
		"Twilight Songbird": "宵鳴鳥",
		"Lifeless Shadow": "死亡巨鳥之影",
		"Twilight Assassin": "宵闇刺客",
		"Cloak-in-dagger": "身披短刃者",
		"Shadow Assassin ": "暗影刺客",
		"Cipher Code": "暗號代碼",
		"Hell Keeper": "地獄守衛",
		"Slashblader": "斬擊劍狼",
		"Crimson Arms": "緋紅刃狼",
		"Spellblade Wielder": "魔劍好手",
		"Demon Slayer Wolf": "破邪月狼",
		"Sleipnir": "斯雷普尼爾",
		"Hide Shark": "暗穴鯊魚",
		"Megamouth": "大顎鮫",
		"Spinal Fin": "尖晶鰭鯊",
		"Grand Tusk": "巨型獠牙",
		"Sandstorm Tyrant": "砂塵暴君",
		"Desert Lagoon": "沙漠潟湖鯊",
		"Mind Ravager": "思念捕食者",
		"Land Crawler": "盤踞大地的大魚",
		"Soul Cleaver": "斷魂者",
		"Dark General": "常闇將軍",
		"Cluster Beetle": "地殼甲蟲",
		"Shadow Commander": "魅影司令",
		"Horned Demon": "巨角惡魔",
		"Rhino Fiend": "犀角魔鬼",
		"Old Castle Dragon": "古城飛龍",
		"Dragon Lord": "統天霸龍",
		"Dragon of Light": "撕裂黑暗的光龍",
		"Ravaging Queen": "常闇女王",
		"Queen of Shadows": "魅影女王",
		"Crownless Queen": "無冠女王",
		"Floating Skeleton": "懸浮屍骸",
		"Skeleton Emperor ": "骷髏皇帝",
		"Automaton": "自動機器人",
		"Sentry Guard": "哨衛",
		"Elder Treant": "樹人長老",
		"Ancient Dragon": "古代巨龍",
		"Deranged King": "癲狂之王",
		"Gatekeeper": "守門人",
		"Code of the Universe": "萬象大典",
		"Code of the Universe - Final": "萬象大典‧終章",
		"Colossus Soldier": "巨像士兵",
		"Code of the Universe (Arm)": "萬象大典‧巨臂",
		"Weasel Roast": "烤羊肉2號",
		"Lamb Roast": "烤羊肉3號",
	}
}