localization["kor"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "라이자의 아틀리에3 소재 배포 문의",
		"Choose a language:": "언어 선택:",
		"Choose a map:": "지도 선택:",
		"Kurken": "쿠켄 섬",
		"Mainland": "쿠켄 섬 주변지역",
		"Cleria": "클레리아 지방",
		"Nemed": "네메드 지방",
		"Orim": "이계 오림",
		"Code": "만상의 대전",
		"Choose an item:": "소재 선택:",
		"Filter Gathering Tool:": "선별 채집 도구:",
		"Hand Maximum Rank": "맨손채집 최대 순위",
		"None": "없음",
		"Rank One": "순위 1",
		"Rank Two": "순위 2",
		"Rank Three": "순위 3",
		"Rod Maximum Rank": "지팡이채집 최대 순위",
		"Sickle Maximum Rank": "낫채집 최대 순위",
		"Axe Maximum Rank": "도끼채집 최대 순위",
		"Hammer Maximum Rank": "망치채집 최대 순위",
		"Net Maximum Rank": "그물채집 최대 순위",
		"Alchemy Mysteries DLC": "DLC 연금술의 신비",
		"Art of Adventure DLC": "DLC 모험의 극의",
		"Search": "찾다",
		"Number found:": "결과 찾기:",
		"$1 in $2": "$1 in $2",
		"Hand Gathering": "맨손채집",
		"Rod Gathering": "지팡이채집",
		"Sickle Gathering": "낫채집",
		"Axe Gathering": "도끼채집",
		"Hammer Gathering": "망치채집",
		"Net Gathering": "그물채집",
	},
	"item": {
		"Clean Water": "깨끗한 물",
		"Goats Milk": "염소 우유",
		"Water Bamboo": "대나무 물통",
		"Plant Essence": "식물 농축액",
		"Roteswasser Tonic": "로테스바서 광수",
		"Rapwar Water": "라프와르 물",
		"Foamy Water": "부글거리는 물",
		"Jade Water": "비취의 황수",
		"Ancient Blue Water": "태고의 창수",
		"Curious Aqua": "큐리어스 아쿠아",
		"Black Water": "검은 물",
		"Nameless Grass": "이름 없는 풀",
		"Wasser Wheat": "바서 보리",
		"Dry Grass": "마른풀",
		"Hill Lettuce": "언덕 양상추",
		"Blue Herb": "블루 허브",
		"Rishikelp": "리시리코",
		"Chomping Grass": "덥석초",
		"Sweet Leaf": "스위트 리프",
		"Ancient Branch": "고대수의 가지",
		"Campanula": "초롱꽃",
		"Glowing Diatom": "광규조",
		"Lucky Clover": "행운의 클로버",
		"Blue Clover": "푸른 토끼풀",
		"Light Absorbing Grass": "흡광초",
		"Rosen Leaf": "로젠 리프",
		"Uni": "성게",
		"Ancient Uni": "고대 성게",
		"Water Uni": "물 성게",
		"Charcoal Uni": "숯 성게",
		"Gold Uni": "황금 성게",
		"Demon Uni": "도깨비가시 성게",
		"Emperor Uni": "대왕 성게",
		"Health Flower": "병망화",
		"Northern Wind Flower": "북풍화",
		"Sunny Honey Flower": "양기의 밀화",
		"Bubble Grass": "방울초",
		"Stained Flower": "스테인드 플라워",
		"Caged Flower": "감옥의 요화",
		"Spring Princess": "청수의 백희",
		"Soul Flower": "산화의 꽃",
		"Rose Crystal": "로즈 크리스털",
		"Delphi Rose": "델포이 로즈",
		"Polar Cactus": "극지 선인장",
		"Timeteller": "시간알리미",
		"Taun": "톤",
		"Tall Taun": "거대 톤",
		"Sapling Branch": "어린 가지 잎",
		"Medicinal Moss": "의약용 이끼",
		"Fertile Soil": "비옥한 흙",
		"Dry Incense": "건조향",
		"Bitter Root": "씁쓸한 뿌리",
		"Crimson Grass": "홍초",
		"Earth's Secret Oils": "대지의 비유",
		"Sage Grass": "선인초",
		"Life Leaf": "생명의 잎",
		"Refueling Extract": "리퓨르 농축액",
		"Yugdore Water": "유그돌 용수",
		"Stinky Trash": "음식물 쓰레기",
		"Mushroom Powder": "버섯 파우더",
		"Mispel Seed": "미스펠 씨앗",
		"Resentful Scream": "원망의 외침",
		"Blessing of Delusion": "허망의 축복",
		"Dragon Flower": "용장란",
		"Demon Blood": "데몬 블러드",
		"Forest Sage": "숲의 현자",
		"Celestial Tears": "천궁의 눈물",
		"Solflower": "태양의 꽃",
		"Dunkelheit": "던켈하이트",
		"Soft Sand": "부드러운 모래",
		"Burning Sand": "가연성 모래",
		"Corail Saber": "코라이유서블",
		"Polluted Humus": "오염된 부엽토",
		"Emerald Glass": "에메랄드 풀",
		"Seafloor Soil": "수저의 흙",
		"Black Muck": "검은 진흙",
		"Vortex Sand": "소용돌이 모래",
		"Glittering Sand": "글리터 샌드",
		"Eroded Stone": "풍화된 석재",
		"Nectar Rock": "감로 바위",
		"Nepheline": "네펠라이트",
		"Waterside Moss Stone": "물가의 이끼돌",
		"Ethereal Stone": "백령암",
		"Ancient Pillar": "고대의 석주",
		"Coral Stone": "산호석",
		"Breeze Stone": "브리즈 스톤",
		"Riverstone": "리버 스톤",
		"Blue Flame Riverstone": "리버 스톤 창염",
		"Hot Saltpeter": "열초석",
		"Arknite": "아크나이트",
		"Crimson Ore": "적열광",
		"Aqua Ore": "아쿠아광",
		"Lightning Ore": "번개광",
		"Wind Ore": "빈트광",
		"Amatite Ore": "아마타이트광",
		"Luminous Rock": "야광암",
		"Pentanite": "펜트나이트",
		"Mordenite": "몰디나이트",
		"Goldinite": "골디나이트",
		"Degenesis Stone": "창생의 역석",
		"Septrin": "셉트리엔",
		"Adamant": "아다만트",
		"Eternal Crystal": "영원결정",
		"Small Crystals": "조그마한 결정",
		"Unknown Gemstone": "정체불명의 원석",
		"Glowing Coral": "빛나는 산호",
		"White Shell Pearl": "대왕조개의 진주",
		"Black Shell Pearl": "대왕조개의 흑진주",
		"Amber Fragment": "호박 파편",
		"Amber Crystal": "호박 수정",
		"Three-Colored Stone": "삼색혼석",
		"Clear Branch": "클리어 브랜치",
		"Holy Arbor Crystal": "성수 결정",
		"Underworld Crystal": "이계 결정",
		"Black Glitter Stone": "흑황석",
		"Rainbow Gemstone": "칠황 원석",
		"Dried Lumber": "마른 톱밥",
		"Flint Pepper": "플린트 페퍼",
		"Explosive Vine": "작렬 덩굴풀",
		"Flaming Black Sand": "불꽃의 검은 모래",
		"Magma Powder": "마그마 파우더",
		"Scrap Paper": "종잇조각",
		"Flammable Bark": "가연성 나무껍질",
		"Palma Bark": "팔마 나무껍질",
		"Fuel Coconut": "퓨얼 코코넛",
		"Natural Oil": "천연기름",
		"Amber Oil": "호박유",
		"Fire and Ice Crystal": "염빙결정",
		"Eternal Fire": "영세의 불꽃",
		"Beast Meat": "짐승 고기",
		"Fresh Meat": "신선한 고기",
		"Some Kind of Egg": "무언가의 알",
		"Oil Tree Fruit": "오일 나무 열매",
		"Nectar Fruit": "감로의 열매",
		"Wild Potato": "야생감자",
		"Portpea": "포르트콩",
		"Red Devil": "붉은 악마",
		"Clenoko": "쿠레노코",
		"Red King Apple": "왕사과",
		"Skull Pumpkin": "스컬 펌프킨",
		"Venom Nut": "베놈 너트",
		"Palma Fruit": "팔마의 열매",
		"Fresh Berry": "프레스 베리",
		"Werder Nut": "베르다 너트",
		"Kurken Fruit": "쿠켄 프루트",
		"Fortune Fruit": "포춘 프루트",
		"Rainbow Grapevine": "무지갯빛 포도",
		"Summer Gem": "서머 젬",
		"Softtail": "소프테일",
		"Beehive": "벌집",
		"Silver Beehive": "백은 벌집",
		"Gold Beehive": "황금 벌집",
		"Bee Haven": "비 하이븐",
		"Honey Ball": "허니볼",
		"Eicheloa": "아이페 로아",
		"Mushroom Colony": "군체 버섯",
		"Brodenbits": "브로든 비츠",
		"Utopiechampignon": "유피토니언",
		"Jellyfish Mushroom": "해파리 버섯",
		"Stool of Nature": "걸상 버섯",
		"Dusk Mushroom": "밤의 귀부인",
		"Danger Mushroom": "극위험 버섯",
		"Jewel Mushroom": "결정 버섯",
		"Golden Crown": "골든 크라운",
		"Sardine": "정어리",
		"Seriole": "방어",
		"Pourpremoule": "풀무르",
		"Crab": "슈랍",
		"Pretty Shells": "예쁜 조개껍질",
		"Spikey": "가시돔",
		"Uni Starfish": "성게 불가사리",
		"Chestnut": "밤",
		"Rainbow Fish": "무지갯빛 생선",
		"Mace Fish": "메이스 피시",
		"Stingray": "스팅 레이",
		"Myria Fish": "만년어",
		"Lake Master": "호수의 지배자",
		"Dragonpalace Nautilus": "용궁 앵무조개",
		"Crown Shellfish": "왕관 소라",
		"Imperial Fish": "황어",
		"Seven Stars": "칠성무당벌레",
		"Honey Ant": "꿀단지개미",
		"Narwhal Grasshopper": "외뿔 메뚜기",
		"Lantern Fly": "등롱 반딧불",
		"Rose Bee": "로즈 비",
		"Giant Beetle": "왕투구풍뎅이",
		"Baby Wyrm": "베이비 블룸",
		"Crimson Cloak": "크림슨 사마귀",
		"Spirit Isopod": "스피릿 모르그",
		"Amber Fly": "앰버 플라이",
		"Lapis Papillion": "라피스 파피용",
		"Trihorn": "트라이혼",
		"Ancient Bug": "왕고충",
		"Rock Schloss": "바위게",
		"Restraint Silk": "속박의 강실",
		"Cotton Grass": "솜털풀",
		"Tough Vine": "튼튼한 덩굴",
		"Arbor Ivy": "거목 담쟁이덩굴",
		"Queen Spider Web": "여왕거미의 집",
		"Hug of Arachne": "아라크네의 포옹",
		"Eiche": "아이페",
		"Tough Log": "튼튼한 통나무",
		"Mossy Driftwood": "이끼 낀 유목",
		"Holy Arbor Branch": "성수의 큰 가지",
		"Palma": "팔마",
		"Fossil Tree": "화석나무",
		"Miasma Log": "맹독 나무",
		"Lightning Tree": "축전 나무",
		"Ancient Log": "태고의 고목",
		"Millennial Tree": "천년수의 유목",
		"Wing Plant": "윙 플랜트",
		"Smoke Signal Flower": "봉화초",
		"Crispy Mushroom": "바삭바삭한 버섯",
		"Sky Bubble": "스카이 버블",
		"Rotwood Miasma": "부목의 독무",
		"Water Holy Branch": "수성수의 가지",
		"Dragon Breath": "화룡의 숨결",
		"Fairystone Fragment": "마석 파편",
		"Dark Crystal Fragment": "암수정 파편",
		"Holy Stone Fragment": "성석 파편",
		"Rainbow Wing Fragment": "홍익의 파편",
		"Magic Tome Piece": "마도서 조각",
		"Old Magic Tome": "낡은 마도서",
		"Holy Tree Leaf": "성수의 잎",
		"Mystic Sphere": "플로트 스피어",
		"Ancient Fossil": "고대생물의 화석",
		"Forever Ice Block": "영구빙괴",
		"Decayed Iron Pieces": "썩은 쇳조각",
		"Rusted Sword": "녹슨 검",
		"Broken Tools": "망가진 도구",
		"Liquid Metal": "액체금속",
		"Ancient Sword": "낡은 투검",
		"Blue Puniball": "푸니푸니 구슬 청",
		"Green Puniball": "푸니푸니 구슬 녹",
		"Red Puniball": "푸니푸니 구슬 적",
		"Black Puniball": "푸니푸니 구슬 흑",
		"Silver Puniball": "푸니푸니 구슬 은",
		"Gold Puniball": "푸니푸니 구슬 금",
		"Animal Hide": "동물 모피",
		"Mythical Hide": "환수 모피",
		"Large Bone": "커다란 뼈",
		"Beast Fossil": "거대 짐승의 화석",
		"Water Beast Fossil": "물짐승의 거대화석",
		"Water Beast Scale": "물짐승의 비늘",
		"Cave Bat Wing": "동굴박쥐의 날개",
		"White Swallow's Nest": "흰 제비의 둥지",
		"Beast Fin": "마수의 등지느러미",
		"Beast Shell": "마수의 갑각",
		"Beast Scales": "마수의 비늘",
		"Giant Bird Feather": "거대새의 풍절우",
		"Giant Bird Egg": "거대새의 대란",
		"Goat Horn": "염소 뿔",
		"Demon Claws": "마조",
		"Fluffy Wool": "푹신푹신한 울",
		"Poison Needle": "가느다란 독침",
		"Dragon Wing": "익룡의 날개",
		"Dragon Egg": "익룡의 알",
		"Dragon Eye": "용의 눈",
		"Dragon Bone": "용골",
		"Dragon Meat": "용 고기",
		"Guardian Armor": "수호자의 견갑",
		"Heroic Spirit": "영령의 혼",
		"Giant Puniball": "왕 푸니 구슬",
		"Fairy Horn Adornment": "요정의 대각장식",
		"Giant Claws": "거대한 발톱",
		"Golem Core": "골렘 코어",
		"Inverted Scale": "역린",
		"Ether Core": "에텔 코어",
		"Imp's Lost Item": "소악마의 분실물",
		"Elemental Force": "엘리먼트 포스",
		"Twisted Thorns": "덩굴 뿌리",
		"Curved Long Nails": "길게 굽은 발톱",
		"Running Beast Crest": "들짐승의 볏",
		"Phantom Color Tail": "환색 꼬리",
		"Wolf Beast's Blade": "늑대의 사냥칼",
		"Duet Stock Solution": "두엣 원액",
		"Scintilla Ore": "신티라 광석",
		"Lujada's Fairystone": "루지아다 마석",
		"Pink Puniball": "푸니푸니 구슬 앵",
		"Giant Kurken Fruit": "거대 쿠켄 프루트",
		"Cow Milk": "우유",
		"Thick Reference Book": "두꺼운 참고서",
		"Giant Claws": "거대한 발톱",
		"White Swallow's Nest": "흰 제비의 둥지",
		"Water Beast Scale": "물짐승의 비늘",
		"Mythical Hide": "환수 모피",
		"Dragon Meat": "용 고기",
		"Heroic Spirit": "영령의 혼",
		"Dragon Wing": "익룡의 날개",
		"Demon Claws": "마조",
		"Dragon Bone": "용골",
		"Dragon Eye": "용의 눈",
		"Spirit Catalysts": "정령 촉매",
		"Ether Core": "에텔 코어",
		"Spirit Catalysts": "정령 촉매",
		"Guiding Bird Feather": "길잡이새의 날개",
		"Gnade Ring": "그나데링",
		"Phantom Scarf": "팬텀 스카프",
		"Chick Doll": "병아리 인형",
		"Myria Fish": "만년어",
		"Summer Gem": "서머 젬",
		"Spring Princess": "청수의 백희",
		"Giant Beetle": "왕투구풍뎅이",
		"Corail Saber": "코라이유서블",
		"Celestial Tears": "천궁의 눈물",
		"Sky Bubble": "스카이 버블",
		"Rainbow Fish": "무지갯빛 생선",
		"Red Devil": "붉은 악마",
		"Chomping Grass": "덥석초",
		"Solflower": "태양의 꽃",
		"Dark Crystal Fragment": "암수정 파편",
		"Campanula": "초롱꽃",
		"Earth's Secret Oils": "대지의 비유",
		"Softtail": "소프테일",
		"Dunkelheit": "던켈하이트",
		"Emperor Uni": "대왕 성게",
		"Light Absorbing Grass": "흡광초",
		"Black Muck": "검은 진흙",
		"Fire and Ice Crystal": "염빙결정",
		"Explosive Uni": "폭발가루 성게",
		"Craft": "크래프트",
		"Bomb": "프람",
		"Ice Bomb": "레헤른",
		"Plajig": "플래직",
		"Luft": "루프트",
		"Trio Craft": "크래프트리오",
		"Anemo Bomb": "아네모 프람",
		"Melting Ice Bomb": "멜트 레헤른",
		"Lia Plajig": "리어 플래직",
		"Edle Luft": "에델프트",
		"Lunar Lamp": "루나 램프",
		"Astro Rose": "아스트 로즈",
		"Lavinage": "라비네주",
		"Grazeit": "그랜 차이트",
		"Himmel Feather": "힘멜 페더",
		"Forbidden Spell Book": "금기의 비술서",
		"Zwei Resonance": "츠바이 레저넌스",
		"Cross Judgement": "크로스 저지먼트",
		"Sourcebook of Acacia": "아카시아 원서",
		"Grass Beans": "그래스 빈즈",
		"Dry Biscuit": "드라이 비스킷",
		"Nectar": "넥타르",
		"Elixir": "엘릭시르제",
		"Hermit Ointment": "은둔자의 연고",
		"Fairy Elixir": "요정의 비약",
		"Mist of Silence": "정적의 미스트",
		"Golden Heart": "골드 하트",
		"Mythic Nectar": "미솔로지 넥타르",
		"Eternal Holy Grail": "영겁회귀의 성배",
		"Fish Oil": "생선기름",
		"War Powder": "워 파우더",
		"Energianica": "에너지아니카",
		"Mystic Robe": "신비한 우의",
		"Miracle Ebonyal": "요약 에보니알",
		"Astronomical Clock": "시공의 천문시계",
		"Fake Bouquet": "허구의 부케",
		"Haze Breath": "헤이즈 블레스",
		"Prison of Decline": "말세의 감옥",
		"Barbaric Horn Whistle": "만용의 뿔피리",
		"Depiction of a Devil": "악마의 초상화",
		"Hourglass of Origin": "시작의 모래시계",
		"Cantera of Calamity": "재앙의 칸델라",
		"Prelude of the Gods": "신들의 서곡",
		"Call of Abyss": "에이비스 콜",
		"Grass Sickle": "풀베기 낫",
		"Silent Sickle": "사일런트 시클",
		"Woodcutter's Axe": "장작용 도끼",
		"Golden Axe": "골든 액스",
		"Hammer": "해머",
		"Ravage Hammer": "래비지 해머",
		"Fishing Rod": "낚싯대",
		"Divine Fishing Rod": "신의 낚싯대 바름헬",
		"Catcher's Net": "포획망",
		"Master Catcher's Net": "달인의 포획망",
		"Wind Shoes": "바람정령의 신발",
		"Emerald Band": "에메랄드 밴드",
		"Air Drop": "에어드롭",
		"Summoner's Bell": "서머너즈 벨",
		"Red Neutralizer": "중화제 적",
		"Blue Neutralizer": "중화제 청",
		"Yellow Neutralizer": "중화제 황",
		"Green Neutralizer": "중화제 녹",
		"Rainbow Neutralizer": "중화제 홍",
		"Honey": "꿀",
		"Berry Syrup": "베리 시럽",
		"Flour": "밀가루",
		"Devil's Breath": "데빌즈 브레스",
		"Puppet Liquid": "퍼핏 리퀴드",
		"Super Pure Water": "초순수",
		"Traveler's Water Orb": "여행자의 물구슬",
		"Medica Powder": "메디카 파우더",
		"Doctor's Bottle": "독토르 보틀",
		"Holy Drop": "성스러운 물방울",
		"Taboo Drop": "금기의 물방울",
		"Zettel": "제텔",
		"Reinforced Zettel": "강화 제텔",
		"Pearl Crystal": "펄 크리스털",
		"Amberlite": "앰버라이트",
		"Spirinite": "스피리나이트",
		"Waking Emerald": "웨이크 에메랄드",
		"Arc en Ciel": "아크 앙 시엘",
		"Dark Glittering Oval": "황흑의 곡옥",
		"Nitro Chips": "니트로 칩",
		"Donour Powder": "도너 파우더",
		"Blue Flame Ember": "창염의 불씨",
		"Mixing Oil": "믹스 오일",
		"Flint Charcoal": "부싯목",
		"Colorful Oil": "컬러풀 오일",
		"Solid Ice Fuel": "고형 연빙",
		"Feather Draft": "페더 드래프트",
		"Ingot": "잉곳",
		"Startium": "스탈티움",
		"Creaminea": "크리미네아",
		"Goldoterion": "골드테리온",
		"Grand Orgen": "글란즈 오르겐",
		"Alchemy Fibers": "연금 섬유",
		"Himmel Schulwa": "힘멜 슈르와",
		"Eternal Firo": "이터널 필로",
		"Cloth": "클로스",
		"Bestial Air": "비스트 에어",
		"Sorcery Rose": "소서리 로즈",
		"Royal Cloth": "로열 클로스",
		"Sage Coat": "세이지 코트",
		"Puni Leather": "푸니 레더",
		"Master Leather": "마스터 레더",
		"Dread Leather": "드레드 레더",
		"Grace Nero": "그레이스 네로",
		"Philosopher's Stone": "현자의 돌",
		"Olden Philosopher's Stone": "고대 현자의 돌",
		"Honey Crystal": "꿀의 결정",
		"Glass Flower": "유리꽃",
		"Wind Crystal Ball": "풍정옥",
		"Growing Quartz": "글로우스 쿼츠",
		"Spirit Bottle": "정령의 작은 병",
		"Crystal Element": "크리스털 엘리먼트",
		"Poisonous Liquid": "포이즌 리퀴드",
		"The Grim Reaper": "그림 리퍼",
		"Polishing Powder": "연마제",
		"Rose Perfume": "로즈 퍼퓸",
		"Spring Wind Pinwheel": "봄바람의 바람개비",
		"Luft Atomizer": "루프트 애터마이저",
		"Exotic Lantern": "이국의 랜턴",
		"Four Seasons Dome": "사계절 돔",
		"Magna Mater": "마그나 마텔",
		"Polishing Sand": "연마 모래",
		"Marblestone": "마블 스톤",
		"Eternal Monolith": "유구의 모노리스",
		"Plant Seeds": "식물의 씨앗",
		"Stone Seeds": "돌의 씨앗",
		"Fire Seeds": "불의 씨앗",
		"Water Seeds": "물의 씨앗",
		"Mystic Seeds": "신비의 씨앗",
		"Poison Seeds": "독의 씨앗",
		"Golden Seeds": "황금 씨앗",
		"Duet Solvent Solution": "두엣 용매",
		"Fairystone Compass": "마석의 지침",
		"Scintilla Glass": "신티라 유리",
		"Lujada Crystals": "루지아다 결정",
		"Glass Goblet": "유리 고블릿",
		"Fairystone Pendant": "마석 펜던트",
		"Hollow Key": "허무의 열쇠",
		"The Starting Key": "최초의 열쇠",
		"Castle Door Key": "성문의 열쇠",
		"Blockade Key": "봉쇄구역의 열쇠",
		"Key of Honor": "영예의 열쇠",
		"Pristine Key": "무구의 열쇠",
		"Red Stone Key": "적석의 열쇠",
		"Blue Stone Key": "청석의 열쇠",
		"Yellow Stone Key": "황석의 열쇠",
		"Green Stone Key": "녹석의 열쇠",
		"Red Iron Key": "홍철의 열쇠",
		"Blue Iron Key": "창철의 열쇠",
		"Orange Iron Key": "등철의 열쇠",
		"Jade Iron Key": "벽철의 열쇠",
		"White Silver Key": "백은의 열쇠",
		"Golden Key": "황금의 열쇠",
		"Rainbow Key": "홍강정의 열쇠",
		"Red Wing Key": "주우의 열쇠",
		"Blue Wing Key": "감우의 열쇠",
		"Light Wing Key": "광우의 열쇠",
		"Leaf Wing Key": "엽우의 열쇠",
		"Scarlet Wing Key": "비익의 열쇠",
		"Cloud Wing Key": "운익의 열쇠",
		"Wing Key": "섬익의 열쇠",
		"Tree Wing Key": "수익의 열쇠",
		"Firebird Key": "봉황의 열쇠",
		"Phoenix Key": "불사조의 열쇠",
		"Phantom Wing Key": "환익의 군주의 열쇠",
		"Fire Gear Key": "화차의 열쇠",
		"Water Gear Key": "수차의 열쇠",
		"Gear Key": "치차의 열쇠",
		"Wind Gear Key": "풍차의 열쇠",
		"Fire Clock Key": "불시계의 열쇠",
		"Water Clock Key": "물시계의 열쇠",
		"Hourglass Key": "모래시계의 열쇠",
		"Gear Gimmick Key": "톱니바퀴 장치 열쇠",
		"Key to the Future": "미래의 열쇠",
		"Key to the Past": "과거의 열쇠",
		"Key of All Times": "시간 지배자의 열쇠",
		"Key of Bright Sky": "밝은하늘의 열쇠",
		"Key of Blue Sky": "맑은하늘의 열쇠",
		"Key of Twilight Sky": "저녁하늘의 열쇠",
		"Key of Night Sky": "밤하늘의 열쇠",
		"Scarlet Key": "붉은별의 열쇠",
		"Dark Star Key": "검은별의 열쇠",
		"Bright Star Key": "밝은별의 열쇠",
		"Meteor Key": "유성의 열쇠",
		"Great Heavens Key": "대천양의 열쇠",
		"Moon Shadow Key": "소월영의 열쇠",
		"Soul Cradle Key": "혼의 요람의 열쇠",
		"Key of Truth": "진정한 열쇠",
		"Key of the End": "종극의 열쇠",
		"Shining Key": "빛나는 열쇠",
		"Alchemist's Staff": "연금술사의 지팡이",
		"Svate Rod": "스베트 로드",
		"Celestial Seeker": "셀레스티얼 시커",
		"Sparkling Reverie": "스파클 레버리에",
		"Agnes Luce": "아니에스 루체",
		"Ciel Shoot": "시엘 슈트",
		"Yale Soar": "에르소아",
		"Croiselt": "클루아젤트",
		"Astrumnox": "아스트룸 녹스",
		"Astral Regalia": "아스트랄 레갈리아",
		"Smite Blade": "스마이트 블레이드",
		"Sword of Rupture": "파리검",
		"Lord Guardian": "로드 가디언",
		"Demon Ender": "데몬 엔더",
		"Liese Divider": "리제 디바이더",
		"Sharp Edge": "샤프 에지",
		"Paradiera": "파라디에라",
		"Luna Solis": "루나 솔리스",
		"Amphisbaena": "암피스바에나",
		"Ifestio": "이페스티오",
		"Aristoclite": "아리스토 크라이트",
		"Herzog": "헤르초크",
		"Might of Heaven": "신위",
		"Edel Schwert": "에델 슈발트",
		"Efflorescence": "에플로레센스",
		"Wise Wand": "와이즈 완드",
		"Educator": "에듀케이터",
		"Occult Wisdom": "지혜의 지팡이",
		"Nachfolger": "나하홀거",
		"Genesis Staff": "창세의 빛지팡이",
		"Trisker": "트라이스카",
		"Aurora": "아우로라",
		"Oren Herald": "오렌 헬딘",
		"Ventiska": "벤티스카",
		"Nevernoche": "네벨 노체",
		"Onyx Blade": "오닉스 블레이드",
		"Lysil Edge": "리딜 에지",
		"Baron's Light": "바론드라이트",
		"Unfold": "언폴드",
		"Lost Alucard": "로스트 알카드",
		"Iron Fan": "철부채",
		"Purple Orchid": "자란",
		"Scarlet Heaven": "비천",
		"Jing Qing Fan": "경청선",
		"Shrine Maiden's Dance": "무녀 가구라",
		"Wild Axe": "와일드 액스",
		"Daybreak": "데이브레이크",
		"Estacado": "에스터 카드",
		"Elde Divide": "엘데 디바이드",
		"Diamantis": "디아만티스",
		"Moon Quake": "문 퀘이크",
		"Crepusclype": "크레프스 크라임",
		"Gravimarius": "그라비 마리우스",
		"Elder Lily": "엘더 릴리",
		"Raventoad": "레벤토아드",
		"Mistral Cane": "미스트랄 케인",
		"Etoile Filant": "에트왈 필란트",
		"Hashbringer": "해시 브링거",
		"Vita Reaper": "비타 리퍼",
		"Folklore": "폴크 롤",
		"Windword": "윈드워드",
		"Crimson Mist": "크림슨 미스트",
		"Void Punisher": "보이드 퍼니셔",
		"Self-defense Fans": "호신용 부채",
		"Brute Veil": "브루트 베일",
		"Solmarkt": "솔 마크트",
		"Noble Tunic": "노블 튜닉",
		"Leather Protector": "레더 프로텍터",
		"Bone Armor": "본 아머",
		"Mage's Robe": "마술사 로브",
		"Soldier's Cuirass": "솔저 큐라스",
		"Radiant Plate": "레디안 플레이트",
		"Fairy Cloak": "요정의 우의",
		"Chainmail Cloak": "체인 클로크",
		"Foreign Armor": "이국의 갑주",
		"Elven Robe": "엘프의 법의",
		"Moonlight Cloak": "월영의 외투",
		"Dragoon Mail": "드래군 메일",
		"Kruger Cloak": "크루거 클로크",
		"Meuchelmolder": "마이헬러이버",
		"Armanoir": "알마 누아르",
		"Uni Charm": "성게형 참",
		"Energy Pendant": "에너지 펜던트",
		"Gnade Ring": "그나데링",
		"Phantom Scarf": "팬텀 스카프",
		"Locket of Devotion": "헌신의 로켓",
		"Migratory Charm": "철새의 부적",
		"Quartz Necklace": "쿼츠 목걸이",
		"Warlock Ring": "워록 링",
		"Warrior Bangle": "투사의 뱅글",
		"Clairvoyance Monocle": "천리안 모노클",
		"Harnal Ring": "하날 링",
		"Warrior Choker": "책사의 초커",
		"Four Spirits Amulet": "4정령의 애뮬릿",
		"Cluster Cuffs": "클러스터 커프",
		"Baron's Crown": "바론즈 크라운",
		"Dragon Scale Necklace": "용린의 목걸이",
		"Broken Hoe": "부러진 괭이",
		"Light and Sturdy Hoe": "가볍고 튼튼한 괭이",
		"Fairystone Light": "마석의 광원",
		"Fairystone Light EX": "마석의 광원 개",
		"Scruffy Drawing": "엉터리 도면",
		"Flame Hair Clip": "불꽃 머리끈",
		"Hammer Brooch": "해머 브로치",
		"Duet Stock Solution+": "고농도 두엣 원액",
		"Duet Solvent Solution EX": "두엣 용매 개",
		"Seeds of Light": "빛의 씨앗",
		"Seeds of Light EX": "빛의 씨앗 개",
		"Disturbing Bell": "교란의 방울",
		"Emil's Tablet": "에밀의 석판",
		"Emil's Book": "에밀의 서",
		"True Silver": "순은",
		"Chart of Another Sky": "이공의 계도",
		"Fi's Necklace": "휘의 목걸이",
		"Shiny Necklace": "반짝이는 목걸이",
		"Dancing Bird Pinwheel": "춤추는새의 바람개비",
		"Silver Crystal": "순은의 결정체",
		"Celestial Globe of Another Sky": "이공의 천구의",
		"High Quality Wood": "고급 목재",
		"Sturdy Wood": "튼튼한 가공재",
		"Broken Ancient Artifact": "망가진 고식비구",
		"New Purifier": "신 정화장치",
		"Broken Light": "망가진 등불",
		"Lamp of the Beginning": "시작의 램프",
		"Age of God Manual": "기계교본 신대의 장",
		"Dragon Bone Fragment": "용골의 파편",
		"Ancient Dragon Gem": "고룡의 보석",
		"Indestructible Box": "썩지 않는 상자",
		"Auxiliary Prosthesis": "보조 의수",
		"Wild Meat on the Bone": "야성의 뼈고기",
		"Father's Album": "아버지의 도판첩",
		"Desalination Equipment EX": "담수화장치 개",
		"Iridescent Mucus": "무지개 점액",
		"Iridescent High-Purity Mucus": "무지개 고순도점액",
		"High Quality Coral Stone": "고급 산호석",
		"&quot;Agnes Luce&quot; Recipe": "「아니에스 루체」 레시피",
		"&quot;Astral Regalia&quot; Recipe": "「아스트랄 레갈리아」 레시피",
		"&quot;Ifestio&quot; Recipe": "「이페스티오」 레시피",
		"&quot;Efflorescence&quot; Recipe": "「에플로레센스」 레시피",
		"&quot;Genesis Staff&quot; Recipe": "「창세의 빛지팡이」 레시피",
		"&quot;Nevernoche&quot; Recipe": "「네벨 노체」 레시피",
		"&quot;Lost Alucard&quot; Recipe": "「로스트 알카드」 레시피",
		"&quot;Shrine Maiden's Dance&quot; Recipe": "「무녀 가구라」 레시피",
		"&quot;Diamantis&quot; Recipe": "「디아만티스」 레시피",
		"&quot;Raventoad&quot; Recipe": "「레벤토아드」 레시피",
		"Federica's Pendant": "페데리카의 펜던트",
		"Small Tablet": "작은 석판",
		"&quot;Glassware&quot; Recipe": "「유리제품」 레시피",
		"&quot;Fairystone Wares&quot; Recipe": "「마석제품」 레시피",
		"&quot;Iridescent High-Purity Mucus&quot; Recipe": "「무지개 고순도점액」 레시피",
		"&quot;Scintilla Glass&quot; Recipe": "「신티라 유리」 레시피",
		"&quot;Lujada Crystal&quot; Recipe": "「루지아다 결정」 레시피",
		"&quot;Fairystone Light&quot; Recipe": "「마석의 광원」 레시피",
		"&quot;Pristine Key&quot; Recipe": "「무구의 열쇠」 레시피",
		"&quot;Disturbing Bell&quot; Recipe": "「교란의 방울」 레시피",
		"&quot;Seeds of Light EX&quot; Recipe": "「빛의 씨앗 개」 레시피",
		"&quot;Emil's Tablet&quot; Recipe": "「에밀의 석판」 레시피",
		"&quot;Duet Solvent Solution EX&quot; Recipe": "「두엣 용매 개」 레시피",
		"&quot;Fairystone Compass&quot; Recipe": "「마석의 지침」 레시피",
		"&quot;Hammer Brooch&quot; Recipe": "「해머 브로치」 레시피",
		"&quot;Flame Hair Clip&quot; Recipe": "「불꽃 머리끈」 레시피",
		"&quot;Shiny Necklace&quot; Recipe": "「반짝이는 목걸이」 레시피",
		"&quot;Dancing Bird Pinwheel&quot; Recipe": "「춤추는새의 바람개비」 레시피",
		"&quot;Silver Crystal&quot; Recipe": "「순은의 결정체」 레시피",
		"&quot;Globe of Another Sky&quot; Recipe": "「이공의 천구의」 레시피",
		"&quot;Light and Sturdy Hoe&quot; Recipe": "「가볍고 튼튼한 괭이」 레시피",
		"&quot;Puppet Liquid&quot; Recipe": "「퍼핏 리퀴드」 레시피",
		"&quot;Flint Charcoal&quot; Recipe": "「부싯목」 레시피",
		"&quot;Solid Ice Fuel&quot; Recipe": "「고형 연빙」 레시피",
		"&quot;Four Seasons Dome&quot; Recipe": "「사계절 돔」 레시피",
		"&quot;Mage's Robe&quot; Recipe": "「마술사 로브」 레시피",
		"&quot;Soldier's Cuirass&quot; Recipe": "「솔저 큐라스」레시피",
		"&quot;Radiant Plate&quot; Recipe": "「레디안 플레이트」 레시피",
		"&quot;Elven Robe&quot; Recipe": "「엘프의 법의」 레시피",
		"&quot;Moonlight Cloak&quot; Recipe": "「월영의 외투」 레시피",
		"&quot;Dragoon Mail&quot; Recipe": "「드래곤 메일」 레시피",
		"&quot;Summoner's Bell&quot; Recipe": "「서머너즈 벨」 레시피",
		"&quot;Sturdy Wood&quot; Recipe": "「튼튼한 가공재」 레시피",
		"&quot;New Purifier&quot; Recipe": "「신 정화장치」 레시피",
		"&quot;Lamp of the Beginning&quot; Recipe": "「시작의 램프」 레시피",
		"&quot;Age of God Manual&quot; Recipe": "「기계교본 신대의 장」 레시피",
		"&quot;Ancient Dragon Gem&quot; Recipe": "「고룡의 보석」 레시피",
		"&quot;Indestructible Box&quot; Recipe": "「썩지 않는 상자」 레시피",
		"&quot;Wild Meat on the Bone&quot; Recipe": "「야성의 뼈고기」 레시피",
		"&quot;Desalination Equipment EX&quot; Recipe": "「담수화장치 개」 레시피",
		"&quot;Grace Nero&quot; Recipe": "「그레이스 네로」 레시피",
		"&quot;Two-handed Staff&quot; Recipe": "「양손지팡이」 레시피",
		"&quot;Bow&quot; Recipe": "「활」 레시피",
		"&quot;Great Sword&quot; Recipe": "「대검」 레시피",
		"&quot;Double Sword&quot; Recipe": "「쌍검」 레시피",
		"&quot;Long Sword&quot; Recipe": "「나가마키」 레시피",
		"&quot;Single-handed Staff&quot; Recipe": "「한손지팡이」 레시피",
		"&quot;Claw&quot; Recipe": "「손톱」 레시피",
		"&quot;Single-handed Sword&quot; Recipe": "「한손검」 레시피",
		"&quot;Fan&quot; Recipe": "「부채」 레시피",
		"&quot;Axe&quot; Recipe": "「도끼」 레시피",
		"&quot;War Hammer&quot; Recipe": "「망치」 레시피",
		"&quot;Legendary Sword&quot; Recipe": "「역전의 명검」 레시피",
		"&quot;Plant Seeds&quot; Recipe": "「식물의 씨앗」 레시피",
		"&quot;Stone Seeds&quot; Recipe": "「돌의 씨앗」 레시피",
		"&quot;Fire Seeds&quot; Recipe": "「불의 씨앗」 레시피",
		"&quot;Water Seeds&quot; Recipe": "「물의 씨앗」 레시피",
		"&quot;Mystic Seeds&quot; Recipe": "「신비의 씨앗」 레시피",
		"&quot;Poison Seeds&quot; Recipe": "「독의 씨앗」 레시피",
		"&quot;Golden Seeds&quot; Recipe": "「황금 씨앗」 레시피",
		"Packed Rice": "폭탄밥",
		"Roasted Chicken": "닭꼬치 직화구이",
		"Gibier Burger": "사냥고기 버거",
		"Mixed Sandwich": "간편식 샌드위치",
		"Smoked Meat": "모험가의 훈제고기",
		"Dried Meat Pizza": "건조육치즈피자",
		"Fresh Fish Carpaccio": "생선 카르파초",
		"Summer Veggie Stew": "여름채소 포토푀",
		"Forest Green Pasta": "삼림 그린파스타",
		"Seafood Paella": "해산물 파에야",
		"Red Chili Soup": "레드칠리 스프",
		"Steak on Crystal": "결정판구이 스테이크",
		"Roasted Monster Fish": "괴어 통구이",
		"Beef Omelette Rice": "비프 오므라이스",
		"White Sauce Ragu": "화이트 라구",
		"Observing Hut": "관측소",
		"Farm": "농원",
		"Laboratory": "연구소",
		"Room Extension 1": "방의 증축1",
		"Room Extension 2": "방의 증축2",
		"Build Observing Hut": "관측소 건축",
		"Build Lookout": "감시탑 건축",
		"Build Windmill": "풍차 건축",
		"Build Greenhouse": "온실 건축",
		"Build Celestial Globe": "천구의 건축",
		"Build Laboratory": "연구소 건축",
		"Rebuild (Observing Hut)": "재건축(관측소)",
		"Rebuild (Farm)": "재건축(농원)",
		"Rebuild (Laboratory)": "재건축(연구소)",
		"Chick Doll": "병아리 인형",
		"Crystal Object": "크리스털 장식품",
		"Fairy Doll": "요정 인형",
		"Puni Jelly": "푸니 젤리",
		"Puni Doll": "푸니 인형",
		"Exhibition Stand": "전시대",
		"Hanging Lantern": "랜턴 장식",
		"Round Table": "원형 테이블",
		"Leather Sofa": "가죽 소파",
		"Chic Sofa": "세련된 소파",
		"Elegant Low Table": "고급 테이블",
		"Pendulum Clock": "추시계",
		"Piano": "피아노",
		"Cute Bed": "예쁜 침대",
		"Extravagant Bed": "화려한 침대",
		"Barrel": "통",
		"Fashionable Bench": "세련된 벤치",
		"Garden Table": "정원 테이블",
		"Potted Plant": "꽃 화분",
		"Oren Doll": "오렌 인형",
		"Dinner Bell": "디너 벨",
		"Decorative Sword": "대검 장식",
		"Resort Bed": "리조트 침대",
		"Resort Sofa": "리조트 소파",
		"Table with Tablecloth": "클로스 테이블",
		"Potted Palm": "야자 화분",
		"Music Stand": "보면대",
		"Giant Manuscript": "거대 사본",
		"Pixie Pot": "작은 요정의 화분",
		"Great Elemental's Chair": "대정령의 의자",
		"Celestial Body Model": "부유천구",
		"Farm Photo": "농촌의 사진",
		"Countryside Photo": "시골의 사진",
		"Rocking Chair": "흔들의자",
		"Cute Sofa": "예쁜 소파",
		"Blackboard": "칠판",
		"Blacksmith Statue": "어느 장인의 상",
		"Goat": "염소",
		"Crisp Bun": "노릇노릇한 식빵",
		"Pumpkin Doll": "호박 인형",
		"Globe": "지구의",
		"Transport Cannon": "배달용 대포",
		"Ashra Donut": "아슬라 도넛",
		"Giant Luceaux Seed": "거대 루크 열매",
		"Mountain of Sweets": "수북이 담은 과자",
		"Exotic Horn": "이국의 뿔피리",
		"Apple Basket": "사과 바구니",
		"Knight's Armor": "기사의 갑주",
		"Teddy Bear": "테디 베어",
		"Beautiful Picture Frame": "근사한 액자",
		"Mysterious Broom": "신비한 빗자루",
		"Phonograph": "축음기",
		"Weasel Doll": "족제비 인형",
		"Shiny Bust": "휘황찬란한 흉상",
		"Sparkling Bust": "찬란한 흉상",
		"Photo of the Capital": "왕도의 사진",
		"Fi Doll": "휘 인형",
		"Candy House": "과자의 집",
		"Mini Cork Board": "미니 코르크판",
		"Books And Bookends": "책과 책꽃이",
		"Tea Set": "티 세트",
		"Synthesis Eqp Set": "조합도구 세트",
		"Basket of Uni": "수북이 담은 성게",
		"Mushroom Shaped Lamp": "버섯 모양 램프",
		"Small Devil Doll": "소악마 인형",
		"Downwind": "다운윈드",
		"Rainbow Lapis": "레인보우 라피스",
		"Cerberus Spirit": "케르베로스 스피릿",
		"Draconic Arrow": "드래고닉 애로우",
		"Maleficus": "말레피쿠스",
		"Calamity Code": "캘러미티 코드",
		"Sugar Drip": "슈거 드립",
		"Eternal Spring": "불변의 약천",
		"Suonare": "수오나레",
		"Voltage Liberator": "볼트 리베레이트",
		"Windsong Fowl": "노래하는 새의 상",
		"Bell of Tranquility": "잠잠한 방울",
		"Lovely Blossom": "러블리 블로섬",
		"Neutronenstern": "나이트로슈테른",
		"Violet Cauldron": "자흑빛의 항아리",
		"Seal Branch": "실 그레인",
		"Old Dragon's Claw": "고룡의 발톱",
		"Water Stone": "수환석",
		"Silence Steel": "사일레스틸",
		"Verdant Moonflower": "심록빛의 월화",
		"Heavenly Seawater": "천해수",
		"Clearfish": "육화어",
		"Pine Fruit": "봉리 열매",
		"Melocotone": "멜로코톤",
		"Star Clam": "별 조개",
		"Gemeater": "젬 이터",
		"Tsurugi Mushroom": "검 버섯",
		"Floating Petal Stone": "부상 화석",
		"Verdeum Metal": "베르데움 금속",
		"Wool Flower": "풍매화",
		"Cleaner Plant": "랄코초",
		"Medicinal Sap": "약수액",
		"Immortal Sapling": "불후의 산목",
		"Blessed Clouds": "은혜로운 뭉게구름",
		"Carved Relic": "목제 유물",
		"Reaper's Scythe": "사신의 대낫",
		"Heavenly Rain Thread": "단비의 실",
		"Unstable Lump": "불안정한 덩어리",
		"Ignis Nut": "이그니스 너트",
		"Ancient Scroll": "고풍스러운 스크롤",
		"Edelhard": "에델 하르트",
		"Medica Solution": "메디카 용액",
		"Toxited": "트키시 티드",
		"Jelly Sandwich": "젤리 샌드",
		"Crimson Birth": "크림슨 버스",
		"Riot Coal": "라이어트 콜",
		"Vajra Wire": "금강선",
		"Lumiere Potpourri": "뤼미에르 포푸리",
		"Ideal Unit": "아이디얼 유닛",
		"Dragon's Tears": "용의 눈물",
	},
	"monster": {
		"Blue Puni": "파랑 푸니",
		"Green Puni": "초록 푸니",
		"Red Puni": "빨강 푸니",
		"Flower Puni": "꽃 푸니",
		"Black Puni": "블랙 푸니",
		"Silver Puni": "실버 푸니",
		"Gold Puni": "골드 푸니",
		"Lavender Puni": "라벤더 푸니",
		"Big Puni": "거대 푸니",
		"Shining Puni": "샤이닝 푸니",
		"Rafflesia Puni": "라플레시아 푸니",
		"Darkness Puni": "다크니스 푸니",
		"Precious Puni": "프레셔스 푸니",
		"Giant Weasel": "왕족제비",
		"Bluefin": "블루핀",
		"Silky Fur": "실키 퍼",
		"Scarf Bunny": "스카프 버니",
		"Night Hunter": "나이트 헌터",
		"Ruined Corrupter": "루인 커럽터",
		"Hide Stalker": "하이드 스토커",
		"Loppy Ear": "롭 이어",
		"Mother Weasel": "어미 왕족제비",
		"Savage Assassin": "새비지 어쌔신",
		"Hex Rabbit": "헥스 래빗",
		"Large Antler": "라지 앤틀러",
		"Holy Beast of the Stars": "별의 성수",
		"Flower Pixie": "꽃의 요정",
		"Illuminated Sylph": "일루미네이트 실프",
		"Flower Gardener": "플라워 가드너",
		"Zephyr Pixie": "제퍼 픽시",
		"Eternal Guardian": "유구의 수호자",
		"Blazing Maiden": "광열의 소녀",
		"Hallowed Spirit": "홀리 스피릿",
		"Plumed Lorelei": "플룸 로렐라이",
		"Elder Fairy": "엘더 페어리",
		"Mirage Master": "환영의 지배자",
		"Lunaria Angel": "루나리아 엔젤",
		"Nightmare Spirit": "악몽의 정령",
		"Schwarzwraith": "슈바르츠 레이스",
		"Sweet Nocturnal ": "스위트 녹터널",
		"Moon Veil": "문 베일",
		"Stone Golem": "스톤 골렘",
		"Rock Puppet": "록 퍼핏",
		"Jewel Guard": "쥬얼 가드",
		"Fairystone Puppet": "마석의 괴뢰",
		"Metal Golem": "메탈 골렘",
		"Meteorite Doll": "메테오라이트 돌",
		"Earth Master": "토괴의 사역자",
		"Rusty Onyx": "러스티 오닉스",
		"Colossus Golem": "콜로서스 골렘",
		"Eternal Sculpture": "불후의 조각상",
		"Boulder Soldier": "거석 병사",
		"Darkomaton": "다크마타",
		"Noir Doll": "느와 돌",
		"Cramberry": "크랜베리",
		"Harvest Prayer": "풍작을 바라는 자",
		"Horned Sheep": "뿔 양",
		"Ashen Wool": "애쉬 울",
		"Fluffy Sheep": "플러피 십",
		"Dreamcatcher": "드림 캐처",
		"Giant Sheep": "거대 양",
		"Mindlurker": "어두운 추억의 짐승",
		"Mad Beast": "광기에 물든 짐승",
		"Scaled Armadillo": "스케일 아르마딜로",
		"Intact Carapace": "인택트 캐러페이스",
		"Tiny Devil": "타이니 데빌",
		"Blue Fiend": "블루 핀드",
		"Hot Evil": "핫 이빌",
		"Ash Demon": "애시 데몬",
		"King Devil": "대악마",
		"Storm Elemental ": "스톰 엘리먼트",
		"Icy Crystal": "아이시 크리스털",
		"Spirit of Nature": "자연의 정령",
		"Scrambled Energy": "스크램블 에너지",
		"Disaster Core": "디재스터 코어",
		"Earth Plant": "어스 플랜트",
		"Root Spreader": "루트 스프레더",
		"Great Tree Messenger": "거목의 사자",
		"Great Mistread": "그림 미스트루드",
		"Yggdrasil": "위그드라실",
		"Rageness": "레이지니스",
		"Ground Builder": "그랜드 빌더",
		"Ruler of the Forest": "숲의 지배자",
		"Spark Riser": "슈퍼 크라이저",
		"Giant Sloth": "거대 나무늘보",
		"Feral Crow": "페럴 크로우",
		"Smart Ripper": "스마트 리퍼",
		"Ferocious Hopper": "배드애스 호퍼",
		"Fierce Hunter": "영악한 사냥꾼",
		"Tyrant": "타이런트",
		"Living Armor": "움직이는 갑주",
		"Ghost Armor": "고스트 아머",
		"Honor Guard Armor": "망국의 근위갑옷",
		"Gladiator": "글래디에이터",
		"Legendary Warrior": "전승의 전사",
		"Immortal Knight": "불멸의 나이트",
		"Royal Admiral": "로열 애드미럴",
		"Heavy Warrior Armor": "전사의 대갑옷",
		"Noble Paladin": "노블 팔라딘",
		"Great Guardian": "그레이트 가디언",
		"Demonic Phantom": "허상의 망령",
		"Berserker Shadow": "광전사의 그림자",
		"Temple Warrior": "템플 워리어",
		"Shattered Breaker": "셰터드 브레이커",
		"Stinger": "스팅거",
		"Sharpened Scissors": "샤프 시저스",
		"Pile Bunker": "파일 벙커",
		"Parching Demon": "굶주린 악마",
		"Dark Scout": "암흑의 척후",
		"Spine Rat": "스파인 래트",
		"Ogre Head": "오거 헤드",
		"Shadow Vanguard": "그림자 첨병",
		"Thrust Hedge": "스러스트 헤지",
		"Shadow Eater": "섀도우 이터",
		"Legion Needle": "리전 니들",
		"Mini Wyvern": "미니 와이번",
		"Zephyr Feather": "윈드 페더",
		"Evil Orchis": "이블 오키스",
		"Stout Drake": "팻 드레이크",
		"Mach Hawk": "마하 호크",
		"Watcher": "워처",
		"Draconic Lord": "드래고닉 로드",
		"Giant Maw": "자이언트 모",
		"Mega Wyvern": "메가 와이번",
		"King of Storms": "킹 오브 스톰",
		"Cloud Liner": "클라우드 라이너",
		"Landbound Dragon": "지박룡",
		"Cursed Wing": "저주받은 날개",
		"Armored Wing": "아머 윙",
		"Steel Raptor": "강철 맹금",
		"Sprinting Bird": "스프린트 버드",
		"Massive Beak": "매시브 비크",
		"Albatross": "알바트로스",
		"Wild Crest": "와일드 크레스트",
		"Overwhelming Bird": "광분하는 괴조",
		"Twilight Songbird": "소명조",
		"Lifeless Shadow": "죽은 새의 그림자",
		"Twilight Assassin": "황혼의 자객",
		"Cloak-in-dagger": "클록 인 더거",
		"Shadow Assassin ": "그림자 암살자",
		"Cipher Code": "사이퍼 코드",
		"Hell Keeper": "지옥의 파수꾼",
		"Slashblader": "슬래시 블레이더",
		"Crimson Arms": "크림슨 암스",
		"Spellblade Wielder": "마검의 사자",
		"Demon Slayer Wolf": "파사의 월랑",
		"Sleipnir": "슬레이프니르",
		"Hide Shark": "하이드 샤크",
		"Megamouth": "대악교",
		"Spinal Fin": "스피넬 핀",
		"Grand Tusk": "그랜 터스커",
		"Sandstorm Tyrant": "모래의 폭군",
		"Desert Lagoon": "데저트 라군",
		"Mind Ravager": "사념 포식자",
		"Land Crawler": "대지를 기는 생선",
		"Soul Cleaver": "소울 클리버",
		"Dark General": "어둠의 장군",
		"Cluster Beetle": "클러스트 비틀",
		"Shadow Commander": "그림자 사령",
		"Horned Demon": "혼 데몬",
		"Rhino Fiend": "라이노 핀드",
		"Old Castle Dragon": "고성의 익룡",
		"Dragon Lord": "하늘의 지배자",
		"Dragon of Light": "어둠을 가르는 광룡",
		"Ravaging Queen": "침식의 여왕",
		"Queen of Shadows": "그림자 여왕",
		"Crownless Queen": "무관의 여왕",
		"Floating Skeleton": "부유하는 뼈",
		"Skeleton Emperor ": "황제 스켈레톤",
		"Automaton": "오토마톤",
		"Sentry Guard": "센트리 가드",
		"Elder Treant": "엘더 트렌트",
		"Ancient Dragon": "에인션트 드래곤",
		"Deranged King": "광기의 왕",
		"Gatekeeper": "게이트 키퍼",
		"Code of the Universe": "만상의 대전",
		"Code of the Universe - Final": "만상의 대전ㆍ종장",
		"Colossus Soldier": "거상의 병사",
		"Code of the Universe (Arm)": "만상의 대전ㆍ팔",
		"Weasel Roast": "램 로스트 2호",
		"Lamb Roast": "램 로스트 3호",
	}
}