localization["chs"] = {
  "ui": {
    "Ryza 3 Material Map Finder": "莱莎的炼金工房3 素材分布查询",
    "Choose a map:": "选择地图：",
    "Kurken": "库肯岛",
    "Mainland": "库肯岛周边地区",
    "Cleria": "克莱莉亚地区",
    "Nemed": "内米德地区",
    "Orim": "异界奥灵",
    "Code": "万象大典",
    "Choose an item:": "选择道具：",
    "Filter Gathering Tool:": "筛选采集工具：",
    "Hand Maximum Rank": "徒手等级",
    "None": "无",
    "Rank One": "等级1",
    "Rank Two": "等级2",
    "Rank Three": "等级3",
    "Rod Maximum Rank": "手杖等级",
    "Sickle Maximum Rank": "镰刀等级",
    "Axe Maximum Rank": "斧头等级",
    "Hammer Maximum Rank": "锤子等级",
    "Net Maximum Rank": "捕捉网等级",
    "Alchemy Mysteries DLC": "DLC 炼金术之神秘",
    "Art of Adventure DLC": "DLC 冒险之精髓",
    "Search": "搜索",
    "Number found:": "查找结果：",
    "$1 in $2": "$2有 $1 处",
    "Hand Gathering": "徒手采集",
    "Rod Gathering": "手杖采集",
    "Sickle Gathering": "镰刀采集",
    "Axe Gathering": "斧头采集",
    "Hammer Gathering": "锤子采集",
    "Net Gathering": "捕捉网采集",
  },
  "item": {
    "Clean Water": "清澈的水",
    "Goats Milk": "山羊奶",
    "Water Bamboo": "储水竹",
    "Plant Essence": "植物精华",
    "Roteswasser Tonic": "洛特斯瓦萨矿水",
    "Rapwar Water": "梨花水",
    "Foamy Water": "起泡水",
    "Jade Water": "翡翠煌水",
    "Ancient Blue Water": "太古苍水",
    "Curious Aqua": "神秘液体",
    "Black Water": "黑水",
    "Nameless Grass": "无名草",
    "Wasser Wheat": "瓦塞麦",
    "Dry Grass": "焦草",
    "Hill Lettuce": "丘陵生菜",
    "Blue Herb": "蓝色香草",
    "Rishikelp": "利西利藻",
    "Chomping Grass": "咬人草",
    "Sweet Leaf": "甜叶",
    "Ancient Branch": "古树枝",
    "Campanula": "吊钟草",
    "Glowing Diatom": "光硅藻",
    "Lucky Clover": "幸运四叶草",
    "Blue Clover": "蓝诘草",
    "Light Absorbing Grass": "吸光草",
    "Rosen Leaf": "玫瑰叶",
    "Uni": "海胆",
    "Ancient Uni": "古代海胆",
    "Water Uni": "水海胆",
    "Charcoal Uni": "炭海胆",
    "Gold Uni": "黄金海胆",
    "Demon Uni": "鬼角海胆",
    "Emperor Uni": "大王海胆",
    "Health Flower": "忘忧花",
    "Northern Wind Flower": "北风之花",
    "Sunny Honey Flower": "阳气蜜花",
    "Bubble Grass": "肥皂草",
    "Stained Flower": "彩光之花",
    "Caged Flower": "树笼妖花",
    "Spring Princess": "清水白姬",
    "Soul Flower": "散命花",
    "Rose Crystal": "玫瑰水晶",
    "Delphi Rose": "德尔福玫瑰",
    "Polar Cactus": "极地仙人掌",
    "Timeteller": "报时花",
    "Taun": "唐木叶",
    "Tall Taun": "长颈通草",
    "Sapling Branch": "幼树枝叶",
    "Medicinal Moss": "药苔",
    "Fertile Soil": "肥土",
    "Dry Incense": "干燥香",
    "Bitter Root": "苦根",
    "Crimson Grass": "红草",
    "Earth's Secret Oils": "大地秘油",
    "Sage Grass": "仙人草",
    "Life Leaf": "生命叶片",
    "Refueling Extract": "补给精华",
    "Yugdore Water": "优古多尔的涌水",
    "Stinky Trash": "厨余垃圾",
    "Mushroom Powder": "蘑菇孢子",
    "Mispel Seed": "欧楂种子",
    "Resentful Scream": "怨嗟悲鸣",
    "Blessing of Delusion": "虚妄祝福",
    "Dragon Flower": "龙葬兰",
    "Demon Blood": "恶魔之血",
    "Forest Sage": "森林智草",
    "Celestial Tears": "天宫之泪",
    "Solflower": "太阳花",
    "Dunkelheit": "一夜花",
    "Soft Sand": "软砂",
    "Burning Sand": "可燃之砂",
    "Corail Saber": "珊瑚砂",
    "Polluted Humus": "受污染的腐叶土",
    "Emerald Glass": "翡翠玻璃",
    "Seafloor Soil": "水底土",
    "Black Muck": "黑泥",
    "Vortex Sand": "漩涡流砂",
    "Glittering Sand": "闪耀砂粒",
    "Eroded Stone": "风化石材",
    "Nectar Rock": "甘露岩",
    "Nepheline": "霞石",
    "Waterside Moss Stone": "水边苔石",
    "Ethereal Stone": "白灵岩",
    "Ancient Pillar": "古代石柱",
    "Coral Stone": "珊瑚石",
    "Breeze Stone": "微风石",
    "Riverstone": "河石",
    "Blue Flame Riverstone": "河石·苍炎",
    "Hot Saltpeter": "热硝石",
    "Arknite": "方舟夜石",
    "Crimson Ore": "赤热矿",
    "Aqua Ore": "海蓝石矿",
    "Lightning Ore": "闪电矿",
    "Wind Ore": "风矿",
    "Amatite Ore": "赤铁矿",
    "Luminous Rock": "夜光岩",
    "Pentanite": "派恩特夜石",
    "Mordenite": "毛尔迪夜石",
    "Goldinite": "戈尔迪夜石",
    "Degenesis Stone": "创生逆石",
    "Septrin": "圣石",
    "Adamant": "金刚石",
    "Eternal Crystal": "永恒结晶",
    "Small Crystals": "小晶石",
    "Unknown Gemstone": "未知的原石",
    "Glowing Coral": "发光珊瑚",
    "White Shell Pearl": "大贝白珍珠",
    "Black Shell Pearl": "大贝黑珍珠",
    "Amber Fragment": "琥珀碎片",
    "Amber Crystal": "琥珀水晶",
    "Three-Colored Stone": "三色石",
    "Clear Branch": "清莹树枝",
    "Holy Arbor Crystal": "圣树结晶",
    "Underworld Crystal": "异界结晶",
    "Black Glitter Stone": "黑煌石",
    "Rainbow Gemstone": "七煌原石",
    "Dried Lumber": "干燥木屑",
    "Flint Pepper": "燧石胡椒",
    "Explosive Vine": "炸裂藤",
    "Flaming Black Sand": "焰之黑砂",
    "Magma Powder": "岩浆粉",
    "Scrap Paper": "纸屑",
    "Flammable Bark": "易燃树皮",
    "Palma Bark": "帕尔马树皮",
    "Fuel Coconut": "燃料椰子",
    "Natural Oil": "天然油",
    "Amber Oil": "琥珀油",
    "Fire and Ice Crystal": "炎冰结晶",
    "Eternal Fire": "永世之焰",
    "Beast Meat": "兽肉",
    "Fresh Meat": "新鲜的肉",
    "Some Kind of Egg": "未知的蛋",
    "Oil Tree Fruit": "油木果实",
    "Nectar Fruit": "甘露果实",
    "Wild Potato": "野生土豆",
    "Portpea": "波多豆",
    "Red Devil": "红恶魔",
    "Clenoko": "余晖笋",
    "Red King Apple": "王玉苹果",
    "Skull Pumpkin": "颅骨南瓜",
    "Venom Nut": "猛毒果",
    "Palma Fruit": "帕尔马果实",
    "Fresh Berry": "莓果",
    "Werder Nut": "森林核果",
    "Kurken Fruit": "库肯果",
    "Fortune Fruit": "幸运果实",
    "Rainbow Grapevine": "七色葡萄",
    "Summer Gem": "夏季宝石",
    "Softtail": "柔软奶油果",
    "Beehive": "蜂巢",
    "Silver Beehive": "银色蜂巢",
    "Gold Beehive": "金色蜂巢",
    "Bee Haven": "叠层蜂蜜块",
    "Honey Ball": "蜜蜂球巢",
    "Eicheloa": "橡树菇",
    "Mushroom Colony": "群生蘑菇",
    "Brodenbits": "布罗登皮特菇",
    "Utopiechampignon": "尤皮特齿菇",
    "Jellyfish Mushroom": "水母菇",
    "Stool of Nature": "椅菇",
    "Dusk Mushroom": "暗夜贵妇人",
    "Danger Mushroom": "极其危险菇",
    "Jewel Mushroom": "宝晶塞欧伊菇",
    "Golden Crown": "金色王冠",
    "Sardine": "沙丁鱼",
    "Seriole": "黄尾鱼",
    "Pourpremoule": "普鲁姆鲁螺",
    "Crab": "灌木蟹",
    "Pretty Shells": "美丽贝壳",
    "Spikey": "刺刺鱼",
    "Uni Starfish": "海胆海星",
    "Chestnut": "栗子",
    "Rainbow Fish": "彩虹鱼",
    "Mace Fish": "钉锤鱼",
    "Stingray": "污浊魔鬼鱼",
    "Myria Fish": "万年鱼",
    "Lake Master": "湖底之主",
    "Dragonpalace Nautilus": "龙宫鹦鹉螺",
    "Crown Shellfish": "王冠海螺",
    "Imperial Fish": "皇鱼",
    "Seven Stars": "七星虫",
    "Honey Ant": "蜜蚁",
    "Narwhal Grasshopper": "独角蚱蜢",
    "Lantern Fly": "灯笼萤火虫",
    "Rose Bee": "玫瑰蜂",
    "Giant Beetle": "甲虫",
    "Baby Wyrm": "幼虹虫",
    "Crimson Cloak": "绯红斗篷",
    "Spirit Isopod": "灵团虫",
    "Amber Fly": "琥珀飞虫",
    "Lapis Papillion": "娜匹斯蝶",
    "Trihorn": "三角甲虫",
    "Ancient Bug": "王古虫",
    "Rock Schloss": "岩城蟹",
    "Restraint Silk": "钢化蛛丝",
    "Cotton Grass": "绵毛草",
    "Tough Vine": "强韧藤蔓",
    "Arbor Ivy": "大树常春藤",
    "Queen Spider Web": "女王蜘蛛网",
    "Hug of Arachne": "阿拉克妮的拥抱",
    "Eiche": "橡木",
    "Tough Log": "结实的圆木",
    "Mossy Driftwood": "长苔藓的流木",
    "Holy Arbor Branch": "圣树大枝",
    "Palma": "帕尔马木",
    "Fossil Tree": "化石树",
    "Miasma Log": "释放瘴气的倒木",
    "Lightning Tree": "蓄雷树",
    "Ancient Log": "太古老柴",
    "Millennial Tree": "千年树幼树",
    "Wing Plant": "翼叶草",
    "Smoke Signal Flower": "狼烟草",
    "Crispy Mushroom": "焦菇",
    "Sky Bubble": "天空泡沫",
    "Rotwood Miasma": "朽木毒雾",
    "Water Holy Branch": "水圣树树枝",
    "Dragon Breath": "火龙吐息",
    "Fairystone Fragment": "魔石碎片",
    "Dark Crystal Fragment": "暗水晶碎片",
    "Holy Stone Fragment": "圣石碎片",
    "Rainbow Wing Fragment": "虹翼碎片",
    "Magic Tome Piece": "魔导书残页",
    "Old Magic Tome": "陈旧的魔导书",
    "Holy Tree Leaf": "圣树叶",
    "Mystic Sphere": "漂浮球体",
    "Ancient Fossil": "古代生物化石",
    "Forever Ice Block": "永恒冰块",
    "Decayed Iron Pieces": "锈蚀铁片",
    "Rusted Sword": "生锈的剑",
    "Broken Tools": "坏掉的道具",
    "Liquid Metal": "液态金属",
    "Ancient Sword": "古老斗剑",
    "Blue Puniball": "噗尼噗尼珠·蓝",
    "Green Puniball": "噗尼噗尼珠·绿",
    "Red Puniball": "噗尼噗尼珠·红",
    "Black Puniball": "噗尼噗尼珠·黑",
    "Silver Puniball": "噗尼噗尼珠·银",
    "Gold Puniball": "噗尼噗尼珠·金",
    "Animal Hide": "动物毛皮",
    "Mythical Hide": "幻兽毛皮",
    "Large Bone": "大骨",
    "Beast Fossil": "巨兽化石",
    "Water Beast Fossil": "水兽巨大化石",
    "Water Beast Scale": "水兽鳞片",
    "Cave Bat Wing": "洞窟蝙蝠翅膀",
    "White Swallow's Nest": "白燕旧巢",
    "Beast Fin": "魔兽背鳍",
    "Beast Shell": "魔兽甲壳",
    "Beast Scales": "魔兽鳞片",
    "Giant Bird Feather": "巨鸟破风羽",
    "Giant Bird Egg": "巨鸟蛋",
    "Goat Horn": "山羊角",
    "Demon Claws": "魔爪",
    "Fluffy Wool": "柔软羊毛",
    "Poison Needle": "剧毒细针",
    "Dragon Wing": "翼龙之翼",
    "Dragon Egg": "翼龙之蛋",
    "Dragon Eye": "龙之眼",
    "Dragon Bone": "龙骨",
    "Dragon Meat": "龙肉",
    "Guardian Armor": "守护者硬甲",
    "Heroic Spirit": "英灵之魂",
    "Giant Puniball": "大噗尼珠",
    "Fairy Horn Adornment": "妖精的大角饰",
    "Giant Claws": "巨大的爪子",
    "Golem Core": "魔巨人核心",
    "Inverted Scale": "逆鳞",
    "Ether Core": "以太核",
    "Imp's Lost Item": "小恶魔的遗失物",
    "Elemental Force": "元素之力",
    "Twisted Thorns": "交缠之根",
    "Curved Long Nails": "弯曲长爪",
    "Running Beast Crest": "走兽肉冠",
    "Phantom Color Tail": "幻色尾",
    "Wolf Beast's Blade": "狼兽的猎刃",
    "Duet Stock Solution": "二重奏原液",
    "Scintilla Ore": "火花矿石",
    "Lujada's Fairystone": "露水魔石",
    "Pink Puniball": "噗尼噗尼珠·樱",
    "Giant Kurken Fruit": "巨大库肯果",
    "Cow Milk": "牛奶",
    "Thick Reference Book": "厚重的参考书",
    "Giant Claws": "巨大的爪子",
    "White Swallow's Nest": "白燕旧巢",
    "Water Beast Scale": "水兽鳞片",
    "Mythical Hide": "幻兽毛皮",
    "Dragon Meat": "龙肉",
    "Heroic Spirit": "英灵之魂",
    "Dragon Wing": "翼龙之翼",
    "Demon Claws": "魔爪",
    "Dragon Bone": "龙骨",
    "Dragon Eye": "龙之眼",
    "Spirit Catalysts": "精灵触媒",
    "Ether Core": "以太核",
    "Spirit Catalysts": "精灵触媒",
    "Guiding Bird Feather": "引导之鸟的羽毛",
    "Gnade Ring": "恩典戒指",
    "Phantom Scarf": "幻影丝巾",
    "Chick Doll": "小鸡布偶",
    "Myria Fish": "万年鱼",
    "Summer Gem": "夏季宝石",
    "Spring Princess": "清水白姬",
    "Giant Beetle": "甲虫",
    "Corail Saber": "珊瑚砂",
    "Celestial Tears": "天宫之泪",
    "Sky Bubble": "天空泡沫",
    "Rainbow Fish": "彩虹鱼",
    "Red Devil": "红恶魔",
    "Chomping Grass": "咬人草",
    "Solflower": "太阳花",
    "Dark Crystal Fragment": "暗水晶碎片",
    "Campanula": "吊钟草",
    "Earth's Secret Oils": "大地秘油",
    "Softtail": "柔软奶油果",
    "Dunkelheit": "一夜花",
    "Emperor Uni": "大王海胆",
    "Light Absorbing Grass": "吸光草",
    "Black Muck": "黑泥",
    "Fire and Ice Crystal": "炎冰结晶",
    "Explosive Uni": "爆裂海胆",
    "Craft": "诡雷",
    "Bomb": "炎烧",
    "Ice Bomb": "冰精",
    "Plajig": "雷球",
    "Luft": "风精",
    "Trio Craft": "诡雷三重奏",
    "Anemo Bomb": "银莲花炎烧",
    "Melting Ice Bomb": "雪融冰精",
    "Lia Plajig": "雷球罐",
    "Edle Luft": "高贵风精",
    "Lunar Lamp": "夜月灯",
    "Astro Rose": "玫瑰枝",
    "Lavinage": "活雪结晶",
    "Grazeit": "闪耀时光",
    "Himmel Feather": "天国羽毛",
    "Forbidden Spell Book": "禁忌秘术书",
    "Zwei Resonance": "双重共振",
    "Cross Judgement": "十字审判",
    "Sourcebook of Acacia": "金合欢原典",
    "Grass Beans": "草豆",
    "Dry Biscuit": "饼干",
    "Nectar": "琼浆玉液",
    "Elixir": "万灵药剂",
    "Hermit Ointment": "隐者软膏",
    "Fairy Elixir": "妖精秘药",
    "Mist of Silence": "静寂轻雾",
    "Golden Heart": "黄金之心",
    "Mythic Nectar": "神话琼浆玉液",
    "Eternal Holy Grail": "永劫回归之圣杯",
    "Fish Oil": "液体鱼油",
    "War Powder": "金创粉",
    "Energianica": "形意口琴",
    "Mystic Robe": "神秘的羽衣",
    "Miracle Ebonyal": "黑檀妖药",
    "Astronomical Clock": "时空天文钟",
    "Fake Bouquet": "虚假花束",
    "Haze Breath": "雾霾吐息",
    "Prison of Decline": "衰势牢狱",
    "Barbaric Horn Whistle": "蛮勇角笛",
    "Depiction of a Devil": "恶魔的肖像画",
    "Hourglass of Origin": "起源沙漏",
    "Cantera of Calamity": "灾厄油灯",
    "Prelude of the Gods": "众神的前奏曲",
    "Call of Abyss": "深渊呼唤",
    "Grass Sickle": "割草镰",
    "Silent Sickle": "寂静镰刀",
    "Woodcutter's Axe": "劈柴斧",
    "Golden Axe": "黄金之斧",
    "Hammer": "锤子",
    "Ravage Hammer": "毁灭之锤",
    "Fishing Rod": "钓竿",
    "Divine Fishing Rod": "神竿慈悲",
    "Catcher's Net": "捕捉网",
    "Master Catcher's Net": "高手捕捉网",
    "Wind Shoes": "风精灵之靴",
    "Emerald Band": "翠绿绸带",
    "Air Drop": "空气糖",
    "Summoner's Bell": "召唤师之铃",
    "Red Neutralizer": "中和剂·红",
    "Blue Neutralizer": "中和剂·蓝",
    "Yellow Neutralizer": "中和剂·黄",
    "Green Neutralizer": "中和剂·绿",
    "Rainbow Neutralizer": "中和剂·七彩",
    "Honey": "蜂蜜",
    "Berry Syrup": "莓果糖浆",
    "Flour": "面粉",
    "Devil's Breath": "恶魔吐息",
    "Puppet Liquid": "傀儡液",
    "Super Pure Water": "超纯水",
    "Traveler's Water Orb": "旅人的水珠",
    "Medica Powder": "药粉",
    "Doctor's Bottle": "药草瓶",
    "Holy Drop": "神圣水滴",
    "Taboo Drop": "禁忌之滴",
    "Zettel": "泽特尔纸",
    "Reinforced Zettel": "强化泽特尔纸",
    "Pearl Crystal": "珍珠核水晶",
    "Amberlite": "琥珀晶石",
    "Spirinite": "精神夜石",
    "Waking Emerald": "觉醒翡翠",
    "Arc en Ciel": "七光宝石",
    "Dark Glittering Oval": "煌黑勾玉",
    "Nitro Chips": "硝基片",
    "Donour Powder": "雷粉",
    "Blue Flame Ember": "苍炎火种",
    "Mixing Oil": "混合油",
    "Flint Charcoal": "打火炭",
    "Colorful Oil": "彩色油",
    "Solid Ice Fuel": "可燃冰",
    "Feather Draft": "轻羽水晶",
    "Ingot": "金属块",
    "Startium": "星铁矿",
    "Creaminea": "创生铁矿",
    "Goldoterion": "金矿",
    "Grand Orgen": "闪耀钢块",
    "Alchemy Fibers": "炼金纤维",
    "Himmel Schulwa": "天丝",
    "Eternal Firo": "永恒之丝",
    "Cloth": "布料",
    "Bestial Air": "兽布",
    "Sorcery Rose": "巫术玫瑰布",
    "Royal Cloth": "皇家布料",
    "Sage Coat": "贤者皮料",
    "Puni Leather": "噗尼皮甲",
    "Master Leather": "大师皮甲",
    "Dread Leather": "恐惧皮革",
    "Grace Nero": "黑色恩惠",
    "Philosopher's Stone": "贤者之石",
    "Olden Philosopher's Stone": "古代贤者之石",
    "Honey Crystal": "蜜结晶",
    "Glass Flower": "玻璃花",
    "Wind Crystal Ball": "风晶玉",
    "Growing Quartz": "成长水晶",
    "Spirit Bottle": "精灵的小瓶",
    "Crystal Element": "核水晶元素",
    "Poisonous Liquid": "毒液",
    "The Grim Reaper": "死神剧毒",
    "Polishing Powder": "研磨剂",
    "Rose Perfume": "玫瑰香水",
    "Spring Wind Pinwheel": "春风风车",
    "Luft Atomizer": "风精喷雾器",
    "Exotic Lantern": "异国灯笼",
    "Four Seasons Dome": "四季球",
    "Magna Mater": "地母板",
    "Polishing Sand": "研磨砂",
    "Marblestone": "大理石",
    "Eternal Monolith": "悠久磐石",
    "Plant Seeds": "植物种子",
    "Stone Seeds": "石之种子",
    "Fire Seeds": "火之种子",
    "Water Seeds": "水之种子",
    "Mystic Seeds": "神秘种子",
    "Poison Seeds": "毒之种子",
    "Golden Seeds": "金色种子",
    "Duet Solvent Solution": "二重奏溶剂",
    "Fairystone Compass": "魔石指针",
    "Scintilla Glass": "火花玻璃",
    "Lujada Crystals": "露水结晶",
    "Glass Goblet": "玻璃高脚杯",
    "Fairystone Pendant": "魔石坠饰",
    "Hollow Key": "虚空钥匙",
    "The Starting Key": "初始钥匙",
    "Castle Door Key": "城门钥匙",
    "Blockade Key": "封锁区域钥匙",
    "Key of Honor": "荣誉钥匙",
    "Pristine Key": "纯净钥匙",
    "Red Stone Key": "赤石钥匙",
    "Blue Stone Key": "青石钥匙",
    "Yellow Stone Key": "黄石钥匙",
    "Green Stone Key": "绿石钥匙",
    "Red Iron Key": "红铁钥匙",
    "Blue Iron Key": "苍铁钥匙",
    "Orange Iron Key": "橙铁钥匙",
    "Jade Iron Key": "碧铁钥匙",
    "White Silver Key": "白银钥匙",
    "Golden Key": "黄金钥匙",
    "Rainbow Key": "虹刚晶钥匙",
    "Red Wing Key": "朱羽钥匙",
    "Blue Wing Key": "蓝羽钥匙",
    "Light Wing Key": "光羽钥匙",
    "Leaf Wing Key": "叶羽钥匙",
    "Scarlet Wing Key": "绯翼钥匙",
    "Cloud Wing Key": "云翼钥匙",
    "Wing Key": "闪翼钥匙",
    "Tree Wing Key": "树翼钥匙",
    "Firebird Key": "凤凰钥匙",
    "Phoenix Key": "不死鸟钥匙",
    "Phantom Wing Key": "幻翼支配者钥匙",
    "Fire Gear Key": "火轮钥匙",
    "Water Gear Key": "水轮钥匙",
    "Gear Key": "齿轮钥匙",
    "Wind Gear Key": "风轮钥匙",
    "Fire Clock Key": "火钟钥匙",
    "Water Clock Key": "水钟钥匙",
    "Hourglass Key": "砂钟钥匙",
    "Gear Gimmick Key": "齿轮机关钥匙",
    "Key to the Future": "未来钥匙",
    "Key to the Past": "过去钥匙",
    "Key of All Times": "时空统治者钥匙",
    "Key of Bright Sky": "明空钥匙",
    "Key of Blue Sky": "苍空钥匙",
    "Key of Twilight Sky": "暮空钥匙",
    "Key of Night Sky": "夜空钥匙",
    "Scarlet Key": "绯星钥匙",
    "Dark Star Key": "暗星钥匙",
    "Bright Star Key": "辉星钥匙",
    "Meteor Key": "流星钥匙",
    "Great Heavens Key": "大天阳钥匙",
    "Moon Shadow Key": "小月影钥匙",
    "Soul Cradle Key": "灵魂摇篮钥匙",
    "Key of Truth": "真实钥匙",
    "Key of the End": "终结钥匙",
    "Shining Key": "发光钥匙",
    "Alchemist's Staff": "炼金术士之杖",
    "Svate Rod": "光辉短杖",
    "Celestial Seeker": "冰蓝弦月杖",
    "Sparkling Reverie": "闪耀梦想",
    "Agnes Luce": "贞洁光杖",
    "Ciel Shoot": "击空之弓",
    "Yale Soar": "翅翼飞弓",
    "Croiselt": "十叉之弓",
    "Astrumnox": "暗夜星矢",
    "Astral Regalia": "星辰徽章",
    "Smite Blade": "重击之剑",
    "Sword of Rupture": "破离剑",
    "Lord Guardian": "守道者",
    "Demon Ender": "恶魔终结者",
    "Liese Divider": "誓裂者",
    "Sharp Edge": "锋利之刃",
    "Paradiera": "天堂纪元",
    "Luna Solis": "日月双剑",
    "Amphisbaena": "双头龙牙剑",
    "Ifestio": "火山双刃",
    "Aristoclite": "贵族长刀",
    "Herzog": "公爵长刀",
    "Might of Heaven": "神威",
    "Edel Schwert": "爱瑟尔剑",
    "Efflorescence": "白华绽放",
    "Wise Wand": "睿智权杖",
    "Educator": "教育者",
    "Occult Wisdom": "幽玄睿智之杖",
    "Nachfolger": "继承者",
    "Genesis Staff": "创世辉杖",
    "Trisker": "三痕裂爪",
    "Aurora": "极光幻爪",
    "Oren Herald": "幽蓝爪",
    "Ventiska": "飞雪夜爪",
    "Nevernoche": "迷雾暗夜",
    "Onyx Blade": "缟玛瑙刀",
    "Lysil Edge": "里迪尔之剑",
    "Baron's Light": "豪族之光",
    "Unfold": "示展长剑",
    "Lost Alucard": "失落阿尔卡多",
    "Iron Fan": "铁扇",
    "Purple Orchid": "紫兰",
    "Scarlet Heaven": "绯天",
    "Jing Qing Fan": "景清扇",
    "Shrine Maiden's Dance": "巫女神乐",
    "Wild Axe": "狂野之斧",
    "Daybreak": "黎明之斧",
    "Estacado": "奋力一搏",
    "Elde Divide": "裂地战斧",
    "Diamantis": "璀璨钻石",
    "Moon Quake": "月震之锤",
    "Crepusclype": "暮光之罪",
    "Gravimarius": "重力武锤",
    "Elder Lily": "百合长老",
    "Raventoad": "部落复兴",
    "Mistral Cane": "寒风之杖",
    "Etoile Filant": "流星之弓",
    "Hashbringer": "碎斩大剑",
    "Vita Reaper": "生命收割者",
    "Folklore": "民谣金刀",
    "Windword": "风之言",
    "Crimson Mist": "绯红雾爪",
    "Void Punisher": "虚无制裁者",
    "Self-defense Fans": "护身扇",
    "Brute Veil": "赤血面纱",
    "Solmarkt": "太阳王国",
    "Noble Tunic": "贵族外衣",
    "Leather Protector": "护身皮甲",
    "Bone Armor": "骸骨铠甲",
    "Mage's Robe": "术者长袍",
    "Soldier's Cuirass": "士兵铁甲",
    "Radiant Plate": "光辉板甲",
    "Fairy Cloak": "妖精羽衣",
    "Chainmail Cloak": "锁链大衣",
    "Foreign Armor": "异国盔甲",
    "Elven Robe": "精灵法衣",
    "Moonlight Cloak": "月影外套",
    "Dragoon Mail": "龙骑兵铠甲",
    "Kruger Cloak": "聪慧大衣",
    "Meuchelmolder": "刺客大衣",
    "Armanoir": "黑魂盔甲",
    "Uni Charm": "海胆挂饰",
    "Energy Pendant": "能量坠饰",
    "Gnade Ring": "恩典戒指",
    "Phantom Scarf": "幻影丝巾",
    "Locket of Devotion": "奉献相框坠",
    "Migratory Charm": "候鸟护身符",
    "Quartz Necklace": "石英项链",
    "Warlock Ring": "术士戒指",
    "Warrior Bangle": "斗士手环",
    "Clairvoyance Monocle": "千里眼单片眼镜",
    "Harnal Ring": "灵巧戒指",
    "Warrior Choker": "军师颈带",
    "Four Spirits Amulet": "四精灵护身符",
    "Cluster Cuffs": "聚合袖扣",
    "Baron's Crown": "男爵冠",
    "Dragon Scale Necklace": "龙鳞首饰",
    "Broken Hoe": "断掉的锄头",
    "Light and Sturdy Hoe": "轻巧坚固的锄头",
    "Fairystone Light": "魔石光源",
    "Fairystone Light EX": "魔石光源·改",
    "Scruffy Drawing": "拙劣的构造图",
    "Flame Hair Clip": "火炎发簪",
    "Hammer Brooch": "锤形胸针",
    "Duet Stock Solution+": "高浓度二重奏原液",
    "Duet Solvent Solution EX": "二重奏溶剂·改",
    "Seeds of Light": "光之种",
    "Seeds of Light EX": "光之种·改",
    "Disturbing Bell": "干扰铃",
    "Emil's Tablet": "埃米尔之石盘",
    "Emil's Book": "埃米尔之书",
    "True Silver": "真银",
    "Chart of Another Sky": "异空界图",
    "Fi's Necklace": "菲的项链",
    "Shiny Necklace": "亮晶晶项链",
    "Dancing Bird Pinwheel": "舞鸟风车",
    "Silver Crystal": "真银结晶体",
    "Celestial Globe of Another Sky": "异空天球仪",
    "High Quality Wood": "高品质木材",
    "Sturdy Wood": "坚固的加工木材",
    "Broken Ancient Artifact": "损坏的古式神器",
    "New Purifier": "新·净化装置",
    "Broken Light": "坏掉的灯具",
    "Lamp of the Beginning": "起源灯",
    "Age of God Manual": "机械教科书神话时代之章",
    "Dragon Bone Fragment": "龙骨碎片",
    "Ancient Dragon Gem": "古龙宝石",
    "Indestructible Box": "不朽箱",
    "Auxiliary Prosthesis": "辅助假手",
    "Wild Meat on the Bone": "狂野带骨肉",
    "Father's Album": "父亲的图稿集",
    "Desalination Equipment EX": "淡水化装置·改",
    "Iridescent Mucus": "彩虹色黏液",
    "Iridescent High-Purity Mucus": "彩虹色的高纯度黏液",
    "High Quality Coral Stone": "高品质珊瑚石",
    "&quot;Agnes Luce&quot; Recipe": "“贞洁光杖”的配方",
    "&quot;Astral Regalia&quot; Recipe": "“星辰徽章”的配方",
    "&quot;Ifestio&quot; Recipe": "“火山双刃”的配方",
    "&quot;Efflorescence&quot; Recipe": "“白华绽放”的配方",
    "&quot;Genesis Staff&quot; Recipe": "“创世辉杖”的配方",
    "&quot;Nevernoche&quot; Recipe": "“迷雾暗夜”的配方",
    "&quot;Lost Alucard&quot; Recipe": "“失落阿尔卡多”的配方",
    "&quot;Shrine Maiden's Dance&quot; Recipe": "“巫女神乐”的配方",
    "&quot;Diamantis&quot; Recipe": "“璀璨钻石”的配方",
    "&quot;Raventoad&quot; Recipe": "“部落复兴”的配方",
    "Federica's Pendant": "菲德丽卡的坠饰",
    "Small Tablet": "小石板",
    "&quot;Glassware&quot; Recipe": "“玻璃制品”的配方",
    "&quot;Fairystone Wares&quot; Recipe": "“魔石制品”的配方",
    "&quot;Iridescent High-Purity Mucus&quot; Recipe": "“彩虹色的高纯度黏液”的配方",
    "&quot;Scintilla Glass&quot; Recipe": "“火花玻璃”的配方",
    "&quot;Lujada Crystal&quot; Recipe": "“露水结晶”的配方",
    "&quot;Fairystone Light&quot; Recipe": "“魔石光源”的配方",
    "&quot;Pristine Key&quot; Recipe": "“纯净钥匙”的配方",
    "&quot;Disturbing Bell&quot; Recipe": "“干扰铃”的配方",
    "&quot;Seeds of Light EX&quot; Recipe": "“光之种·改”的配方",
    "&quot;Emil's Tablet&quot; Recipe": "“埃米尔之石盘”的配方",
    "&quot;Duet Solvent Solution EX&quot; Recipe": "“二重奏溶剂·改”的配方",
    "&quot;Fairystone Compass&quot; Recipe": "“魔石指针”的配方",
    "&quot;Hammer Brooch&quot; Recipe": "“锤形胸针”的配方",
    "&quot;Flame Hair Clip&quot; Recipe": "“火炎发簪”的配方",
    "&quot;Shiny Necklace&quot; Recipe": "“亮晶晶项链”的配方",
    "&quot;Dancing Bird Pinwheel&quot; Recipe": "“舞鸟风车”的配方",
    "&quot;Silver Crystal&quot; Recipe": "“真银结晶体”的配方",
    "&quot;Globe of Another Sky&quot; Recipe": "“异空天球仪”的配方",
    "&quot;Light and Sturdy Hoe&quot; Recipe": "“轻巧坚固的锄头”的配方",
    "&quot;Puppet Liquid&quot; Recipe": "“傀儡液”的配方",
    "&quot;Flint Charcoal&quot; Recipe": "“打火炭”的配方",
    "&quot;Solid Ice Fuel&quot; Recipe": "“可燃冰”的配方",
    "&quot;Four Seasons Dome&quot; Recipe": "“四季球”的配方",
    "&quot;Mage's Robe&quot; Recipe": "“术者长袍”的配方",
    "&quot;Soldier's Cuirass&quot; Recipe": "“士兵铁甲”的配方",
    "&quot;Radiant Plate&quot; Recipe": "“光辉板甲”的配方",
    "&quot;Elven Robe&quot; Recipe": "“精灵法衣”的配方",
    "&quot;Moonlight Cloak&quot; Recipe": "“月影外套”的配方",
    "&quot;Dragoon Mail&quot; Recipe": "“龙骑兵锁子甲”的配方",
    "&quot;Summoner's Bell&quot; Recipe": "“召唤师之铃”的配方",
    "&quot;Sturdy Wood&quot; Recipe": "“坚固的加工木材”的配方",
    "&quot;New Purifier&quot; Recipe": "“新·净化装置”的配方",
    "&quot;Lamp of the Beginning&quot; Recipe": "“起源灯”的配方",
    "&quot;Age of God Manual&quot; Recipe": "“机械教科书神话时代之章”的配方",
    "&quot;Ancient Dragon Gem&quot; Recipe": "“古龙宝石”的配方",
    "&quot;Indestructible Box&quot; Recipe": "“不朽箱”的配方",
    "&quot;Wild Meat on the Bone&quot; Recipe": "“狂野带骨肉”的配方",
    "&quot;Desalination Equipment EX&quot; Recipe": "“淡水化装置·改”的配方",
    "&quot;Grace Nero&quot; Recipe": "“黑色恩惠”的配方",
    "&quot;Two-handed Staff&quot; Recipe": "“双手杖”的配方",
    "&quot;Bow&quot; Recipe": "“弓”的配方",
    "&quot;Great Sword&quot; Recipe": "“大剑”的配方",
    "&quot;Double Sword&quot; Recipe": "“双剑”的配方",
    "&quot;Long Sword&quot; Recipe": "“长刀”的配方",
    "&quot;Single-handed Staff&quot; Recipe": "“单手杖”的配方",
    "&quot;Claw&quot; Recipe": "“钩爪”的配方",
    "&quot;Single-handed Sword&quot; Recipe": "“单手剑”的配方",
    "&quot;Fan&quot; Recipe": "“扇子”的配方",
    "&quot;Axe&quot; Recipe": "“斧头”的配方",
    "&quot;War Hammer&quot; Recipe": "“锤子”的配方",
    "&quot;Legendary Sword&quot; Recipe": "“历经百战的名剑”的配方",
    "&quot;Plant Seeds&quot; Recipe": "“植物种子”的配方",
    "&quot;Stone Seeds&quot; Recipe": "“石之种子”的配方",
    "&quot;Fire Seeds&quot; Recipe": "“火之种子”的配方",
    "&quot;Water Seeds&quot; Recipe": "“水之种子”的配方",
    "&quot;Mystic Seeds&quot; Recipe": "“神秘种子”的配方",
    "&quot;Poison Seeds&quot; Recipe": "“毒之种子”的配方",
    "&quot;Golden Seeds&quot; Recipe": "“金色种子”的配方",
    "Packed Rice": "炸弹饭",
    "Roasted Chicken": "火烤鸡肉串",
    "Gibier Burger": "野味汉堡",
    "Mixed Sandwich": "轻便混合三明治",
    "Smoked Meat": "冒险者制烟熏肉",
    "Dried Meat Pizza": "肉干芝士披萨",
    "Fresh Fish Carpaccio": "冷盘生鱼片",
    "Summer Veggie Stew": "夏季蔬菜锅",
    "Forest Green Pasta": "森林青酱面",
    "Seafood Paella": "海鲜烩饭",
    "Red Chili Soup": "红辣椒汤",
    "Steak on Crystal": "结晶板煎肉排",
    "Roasted Monster Fish": "烤怪鱼",
    "Beef Omelette Rice": "牛肉酱蛋包饭",
    "White Sauce Ragu": "白酱炖菜",
    "Observing Hut": "观测小屋",
    "Farm": "农园",
    "Laboratory": "研究所",
    "Room Extension 1": "扩建房间1",
    "Room Extension 2": "扩建房间2",
    "Build Observing Hut": "建造观测小屋",
    "Build Lookout": "建造瞭望台",
    "Build Windmill": "建造风车",
    "Build Greenhouse": "建造温室",
    "Build Celestial Globe": "建造天球仪",
    "Build Laboratory": "建造研究所",
    "Rebuild (Observing Hut)": "改建（观测小屋）",
    "Rebuild (Farm)": "改建（农园）",
    "Rebuild (Laboratory)": "改建（研究所）",
    "Chick Doll": "小鸡布偶",
    "Crystal Object": "水晶装饰品",
    "Fairy Doll": "妖精布偶",
    "Puni Jelly": "噗尼果冻",
    "Puni Doll": "噗尼布偶",
    "Exhibition Stand": "展示台",
    "Hanging Lantern": "灯笼装饰",
    "Round Table": "圆桌",
    "Leather Sofa": "皮革沙发",
    "Chic Sofa": "典雅的沙发",
    "Elegant Low Table": "高级的矮桌",
    "Pendulum Clock": "摆钟",
    "Piano": "钢琴",
    "Cute Bed": "可爱的床铺",
    "Extravagant Bed": "豪华的床铺",
    "Barrel": "木桶",
    "Fashionable Bench": "时髦的长凳",
    "Garden Table": "庭园桌",
    "Potted Plant": "彩花盆栽",
    "Oren Doll": "欧兰族布偶",
    "Dinner Bell": "晚餐铃",
    "Decorative Sword": "大剑装饰",
    "Resort Bed": "渡假胜地的床铺",
    "Resort Sofa": "渡假胜地的沙发",
    "Table with Tablecloth": "附桌巾的桌子",
    "Potted Palm": "棕榈盆栽",
    "Music Stand": "谱架",
    "Giant Manuscript": "巨大抄本",
    "Pixie Pot": "小妖精的盆栽",
    "Great Elemental's Chair": "大精灵的椅子",
    "Celestial Body Model": "浮游天球",
    "Farm Photo": "农村的照片",
    "Countryside Photo": "乡村的照片",
    "Rocking Chair": "摇椅",
    "Cute Sofa": "可爱的沙发",
    "Blackboard": "黑板",
    "Blacksmith Statue": "武器工匠的雕像",
    "Goat": "山羊",
    "Crisp Bun": "烤吐司",
    "Pumpkin Doll": "南瓜布偶",
    "Globe": "地球仪",
    "Transport Cannon": "送货用大炮",
    "Ashra Donut": "阿斯拉甜甜圈",
    "Giant Luceaux Seed": "巨大龙子果",
    "Mountain of Sweets": "点心山",
    "Exotic Horn": "异国角笛",
    "Apple Basket": "苹果篮",
    "Knight's Armor": "骑士盔甲",
    "Teddy Bear": "泰迪熊",
    "Beautiful Picture Frame": "漂亮的相框",
    "Mysterious Broom": "神奇扫帚",
    "Phonograph": "留声机",
    "Weasel Doll": "鼬的布偶",
    "Shiny Bust": "辉煌胸像",
    "Sparkling Bust": "闪耀胸像",
    "Photo of the Capital": "王都的照片",
    "Fi Doll": "菲布偶",
    "Candy House": "糖果屋",
    "Mini Cork Board": "迷你软木板",
    "Books And Bookends": "书与书挡",
    "Tea Set": "茶具组",
    "Synthesis Eqp Set": "调合器材组",
    "Basket of Uni": "海胆山",
    "Mushroom Shaped Lamp": "菌菇造型灯",
    "Small Devil Doll": "小恶魔布偶",
    "Downwind": "顺风镖",
    "Rainbow Lapis": "七彩石",
    "Cerberus Spirit": "三头犬之灵",
    "Draconic Arrow": "龙之箭",
    "Maleficus": "邪恶飞刀",
    "Calamity Code": "灾祸暗码",
    "Sugar Drip": "砂糖之滴",
    "Eternal Spring": "永恒药泉",
    "Suonare": "奏响之器",
    "Voltage Liberator": "热力释放",
    "Windsong Fowl": "阅风鸟像",
    "Bell of Tranquility": "沉静之铃",
    "Lovely Blossom": "迷人花朵",
    "Neutronenstern": "中子星",
    "Violet Cauldron": "紫黑色大壶",
    "Seal Branch": "封印树枝",
    "Old Dragon's Claw": "古龙钩爪",
    "Water Stone": "水环石",
    "Silence Steel": "静寂金属",
    "Verdant Moonflower": "深绿之月华",
    "Heavenly Seawater": "天海水",
    "Clearfish": "六花鱼",
    "Pine Fruit": "鹏梨果实",
    "Melocotone": "桃色岩盐",
    "Star Clam": "星形蚬",
    "Gemeater": "食宝石虫",
    "Tsurugi Mushroom": "剑菇",
    "Floating Petal Stone": "漂浮花石",
    "Verdeum Metal": "碧绿金属",
    "Wool Flower": "乘风之花",
    "Cleaner Plant": "消毒草",
    "Medicinal Sap": "药树液",
    "Immortal Sapling": "不朽林木",
    "Blessed Clouds": "恩惠积云",
    "Carved Relic": "木雕遗物",
    "Reaper's Scythe": "死神大镰",
    "Heavenly Rain Thread": "天梅雨之丝",
    "Unstable Lump": "不稳定的聚合体",
    "Ignis Nut": "火焰松果",
    "Ancient Scroll": "古风卷轴",
    "Edelhard": "高贵之心",
    "Medica Solution": "医药溶液",
    "Toxited": "赤毒液",
    "Jelly Sandwich": "果冻砂",
    "Crimson Birth": "绯红降生",
    "Riot Coal": "爆燃石炭",
    "Vajra Wire": "金刚线",
    "Lumiere Potpourri": "圣光香料",
    "Ideal Unit": "理想元件",
    "Dragon's Tears": "龙之泪",
  },
  "monster": {
    "Blue Puni": "蓝噗尼",
    "Green Puni": "绿噗尼",
    "Red Puni": "红噗尼",
    "Flower Puni": "花噗尼",
    "Black Puni": "黑噗尼",
    "Silver Puni": "银噗尼",
    "Gold Puni": "金噗尼",
    "Lavender Puni": "薰衣草噗尼",
    "Big Puni": "巨大噗尼",
    "Shining Puni": "发光噗尼",
    "Rafflesia Puni": "大王花噗尼",
    "Darkness Puni": "暗黑噗尼",
    "Precious Puni": "珍奇噗尼",
    "Giant Weasel": "大鼬",
    "Bluefin": "蓝鳍鼬",
    "Silky Fur": "柔滑皮鼬",
    "Scarf Bunny": "围巾兔",
    "Night Hunter": "夜猎人",
    "Ruined Corrupter": "毁灭的侵蚀者",
    "Hide Stalker": "暗地追迹者",
    "Loppy Ear": "垂耳兔",
    "Mother Weasel": "大鼬妈妈",
    "Savage Assassin": "野性刺客",
    "Hex Rabbit": "咒术兔",
    "Large Antler": "巨大鹿角",
    "Holy Beast of the Stars": "星辰圣兽",
    "Flower Pixie": "花精",
    "Illuminated Sylph": "微光灵者",
    "Flower Gardener": "护花园丁",
    "Zephyr Pixie": "微风仙子",
    "Eternal Guardian": "悠久守护者",
    "Blazing Maiden": "光热少女",
    "Hallowed Spirit": "神圣鬼魂",
    "Plumed Lorelei": "羽毛女妖",
    "Elder Fairy": "年长妖精",
    "Mirage Master": "控幻者",
    "Lunaria Angel": "露娜莉亚天使",
    "Nightmare Spirit": "恶梦之灵",
    "Schwarzwraith": "黑色巨灵",
    "Sweet Nocturnal ": "美好之夜",
    "Moon Veil": "月之面纱",
    "Stone Golem": "硬石魔巨人",
    "Rock Puppet": "石傀儡",
    "Jewel Guard": "宝石卫兵",
    "Fairystone Puppet": "魔石傀儡",
    "Metal Golem": "金属魔巨人",
    "Meteorite Doll": "陨石魔偶",
    "Earth Master": "土块使役者",
    "Rusty Onyx": "锈玛瑙巨魔",
    "Colossus Golem": "巨像魔巨人",
    "Eternal Sculpture": "不朽雕像",
    "Boulder Soldier": "巨石士兵",
    "Darkomaton": "暗黑魔巨人",
    "Noir Doll": "漆黑魔偶",
    "Cramberry": "蔓越莓",
    "Harvest Prayer": "祈求丰收者",
    "Horned Sheep": "角绵羊",
    "Ashen Wool": "灰毛绵羊",
    "Fluffy Sheep": "柔毛绵羊",
    "Dreamcatcher": "捕梦者",
    "Giant Sheep": "巨大绵羊",
    "Mindlurker": "灰暗回忆之兽",
    "Mad Beast": "狂暴猛兽",
    "Scaled Armadillo": "鳞甲犰狳",
    "Intact Carapace": "完美甲壳",
    "Tiny Devil": "迷你恶魔",
    "Blue Fiend": "蓝恶魔",
    "Hot Evil": "炙热恶魔",
    "Ash Demon": "灰恶魔",
    "King Devil": "大恶魔",
    "Storm Elemental ": "风暴元素",
    "Icy Crystal": "寒冰水晶",
    "Spirit of Nature": "自然精灵",
    "Scrambled Energy": "能量争夺者",
    "Disaster Core": "灾难核心",
    "Earth Plant": "大地草",
    "Root Spreader": "根茎传播者",
    "Great Tree Messenger": "大树使者",
    "Great Mistread": "闪雾狂暴",
    "Yggdrasil": "世界树",
    "Rageness": "怠惰者",
    "Ground Builder": "大地建筑工",
    "Ruler of the Forest": "森林支配者",
    "Spark Riser": "闪耀统筹者",
    "Giant Sloth": "巨大树懒",
    "Feral Crow": "凶猛钩爪",
    "Smart Ripper": "狡猾开膛手",
    "Ferocious Hopper": "卑鄙跳跃者",
    "Fierce Hunter": "凶猛猎人",
    "Tyrant": "狂怒暴君",
    "Living Armor": "移动盔甲",
    "Ghost Armor": "鬼魂铠甲",
    "Honor Guard Armor": "亡国的近卫铠",
    "Gladiator": "角斗士",
    "Legendary Warrior": "传说的古代勇士",
    "Immortal Knight": "永世的骑士",
    "Royal Admiral": "皇家上将",
    "Heavy Warrior Armor": "战士的大铠",
    "Noble Paladin": "贵族圣骑士",
    "Great Guardian": "伟大守护者",
    "Demonic Phantom": "幻影幽鬼",
    "Berserker Shadow": "狂战士之影",
    "Temple Warrior": "神殿战士",
    "Shattered Breaker": "粉碎破坏者",
    "Stinger": "毒刺",
    "Sharpened Scissors": "锐剪",
    "Pile Bunker": "贯钉",
    "Parching Demon": "干渴的恶魔",
    "Dark Scout": "常暗的斥候",
    "Spine Rat": "脊柱鼠",
    "Ogre Head": "巨人兽首领",
    "Shadow Vanguard": "魅影尖兵",
    "Thrust Hedge": "猛刺之猬",
    "Shadow Eater": "食影者",
    "Legion Needle": "针山刺猬",
    "Mini Wyvern": "迷你双足飞龙",
    "Zephyr Feather": "风羽",
    "Evil Orchis": "邪恶的兰花",
    "Stout Drake": "大肚龙",
    "Mach Hawk": "马赫飞翼",
    "Watcher": "守望者",
    "Draconic Lord": "龙之君王",
    "Giant Maw": "巨咽龙",
    "Mega Wyvern": "巨型双足飞龙",
    "King of Storms": "风暴之王",
    "Cloud Liner": "云轮",
    "Landbound Dragon": "地缚龙",
    "Cursed Wing": "诅咒之翼",
    "Armored Wing": "铠甲之翼",
    "Steel Raptor": "钢铁猛禽",
    "Sprinting Bird": "快跑鸟",
    "Massive Beak": "巨喙鸟",
    "Albatross": "信天翁",
    "Wild Crest": "野生大冠鸡",
    "Overwhelming Bird": "狂奔怪鸟",
    "Twilight Songbird": "宵鸣鸟",
    "Lifeless Shadow": "死亡巨鸟之影",
    "Twilight Assassin": "宵暗刺客",
    "Cloak-in-dagger": "身披短刃者",
    "Shadow Assassin ": "暗影刺客",
    "Cipher Code": "暗号代码",
    "Hell Keeper": "地狱守卫",
    "Slashblader": "斩击剑狼",
    "Crimson Arms": "绯红刃狼",
    "Spellblade Wielder": "魔剑好手",
    "Demon Slayer Wolf": "破邪月狼",
    "Sleipnir": "斯雷普尼尔",
    "Hide Shark": "暗穴鲨鱼",
    "Megamouth": "大颚鲛",
    "Spinal Fin": "尖晶鳍鲨",
    "Grand Tusk": "巨型獠牙",
    "Sandstorm Tyrant": "砂尘暴君",
    "Desert Lagoon": "沙漠潟湖鲨",
    "Mind Ravager": "思念捕食者",
    "Land Crawler": "盘踞大地的大鱼",
    "Soul Cleaver": "断魂者",
    "Dark General": "常暗将军",
    "Cluster Beetle": "地壳甲虫",
    "Shadow Commander": "魅影司令",
    "Horned Demon": "巨角恶魔",
    "Rhino Fiend": "犀角魔鬼",
    "Old Castle Dragon": "古城飞龙",
    "Dragon Lord": "统天霸龙",
    "Dragon of Light": "撕裂黑暗的光龙",
    "Ravaging Queen": "常暗女王",
    "Queen of Shadows": "魅影女王",
    "Crownless Queen": "无冠女王",
    "Floating Skeleton": "悬浮尸骸",
    "Skeleton Emperor ": "骷髅皇帝",
    "Automaton": "自动机器人",
    "Sentry Guard": "哨卫",
    "Elder Treant": "树人长老",
    "Ancient Dragon": "古代巨龙",
    "Deranged King": "癫狂之王",
    "Gatekeeper": "守门人",
    "Code of the Universe": "万象大典",
    "Code of the Universe - Final": "万象大典·终章",
    "Colossus Soldier": "巨像士兵",
    "Code of the Universe (Arm)": "万象大典·巨臂",
    "Weasel Roast": "烤羊肉2号",
    "Lamb Roast": "烤羊肉3号",
  }
}