availableItems = [
	"Adamant",
	"Amatite Ore",
	"Amber Crystal",
	"Amber Fly",
	"Amber Fragment",
	"Amber Oil",
	"Ametrite",
	"Ancient Blue Water",
	"Ancient Branch",
	"Ancient Bug",
	"Ancient Fossil",
	"Ancient Log",
	"Ancient Pillar",
	"Ancient Scroll",
	"Ancient Sword",
	"Ancient Uni",
	"Animal Hide",
	"Aqua Ore",
	"Arbor Ivy",
	"Arknite",
	"Baby Wyrm",
	"Beast Fin",
	"Beast Fossil",
	"Beast Meat",
	"Beast Scales",
	"Beast Shell",
	"Bee Haven",
	"Beehive",
	"Bitter Root",
	"Black Glitter Stone",
	"Black Muck",
	"Black Puniball",
	"Black Shell Pearl",
	"Black Water",
	"Blessed Clouds",
	"Blessing of Delusion",
	"Blue Clover",
	"Blue Flame Riverstone",
	"Blue Herb",
	"Blue Puniball",
	"Breeze Stone",
	"Brodenbits",
	"Broken Tools",
	"Bubble Grass",
	"Burning Sand",
	"Cactus Blossom",
	"Caged Flower",
	"Campanula",
	"Carved Relic",
	"Cave Bat Wing",
	"Celestial Tears",
	"Charcoal Uni",
	"Chestnut",
	"Chomping Grass",
	"Clean Water",
	"Cleaner Plant",
	"Clear Branch",
	"Clearfish",
	"Clenoko",
	"Corail Saber",
	"Coral Stone",
	"Cotton Grass",
	"Cow Milk",
	"Crab",
	"Crimson Cloak",
	"Crimson Grass",
	"Crimson Ore",
	"Crispy Mushroom",
	"Crown Shellfish",
	"Curious Aqua",
	"Curved Long Nails",
	"Danger Mushroom",
	"Dark Crystal Fragment",
	"Decayed Iron Pieces",
	"Degenesis Stone",
	"Delphi Rose",
	"Demon Blood",
	"Demon Claws",
	"Demon Uni",
	"Desert Cleaner",
	"Dragon Bone",
	"Dragon Breath",
	"Dragon Egg",
	"Dragon Eye",
	"Dragon Flower",
	"Dragon Meat",
	"Dragon Wing",
	"Dragonpalace Nautilus",
	"Dried Lumber",
	"Dry Grass",
	"Dry Incense",
	"Duet Stock Solution",
	"Dunkelheit",
	"Dusk Mushroom",
	"Earth's Secret Oils",
	"Eiche",
	"Eicheloa",
	"Elemental Force",
	"Emerald Glass",
	"Emperor Uni",
	"Eroded Stone",
	"Eternal Crystal",
	"Eternal Fire",
	"Ether Core",
	"Ethereal Stone",
	"Exotic Meat",
	"Explosive Vine",
	"Fairy Horn Adornment",
	"Fairystone Fragment",
	"Fertile Soil",
	"Fire and Ice Crystal",
	"Flaming Black Sand",
	"Flammable Bark",
	"Flint Pepper",
	"Floating Petal Stone",
	"Fluffy Wool",
	"Foamy Water",
	"Forest Sage",
	"Forever Ice Block",
	"Forgotten Pottery",
	"Fortune Fruit",
	"Fossil Tree",
	"Fresh Berry",
	"Fresh Meat",
	"Fuel Coconut",
	"Gemeater",
	"Giant Beetle",
	"Giant Bird Egg",
	"Giant Bird Feather",
	"Giant Claws",
	"Giant Kurken Fruit",
	"Giant Puniball",
	"Glittering Sand",
	"Glowing Coral",
	"Glowing Diatom",
	"Goat Horn",
	"Goats Milk",
	"Gold Beehive",
	"Gold Puniball",
	"Gold Uni",
	"Golden Crown",
	"Golden Puniball",
	"Goldinite",
	"Golem Core",
	"Green Puniball",
	"Guardian Armor",
	"Health Flower",
	"Heavenly Rain Thread",
	"Heavenly Seawater",
	"Heroic Spirit",
	"Hill Lettuce",
	"Holy Arbor Branch",
	"Holy Arbor Crystal",
	"Holy Stone Fragment",
	"Holy Tree Leaf",
	"Honey Ant",
	"Honey Ball",
	"Hot Saltpeter",
	"Hug of Arachne",
	"Ignis Nut",
	"Immortal Sapling",
	"Imp's Lost Item",
	"Imperial Fish",
	"Inverted Scale",
	"Jade Water",
	"Jellyfish Mushroom",
	"Jewel Mushroom",
	"Kala's Translated Texts (Copy)",
	"Kurken Fruit",
	"Lake Master",
	"Lantern Fly",
	"Lapis Papillion",
	"Large Bone",
	"Life Leaf",
	"Light Absorbing Grass",
	"Lightning Ore",
	"Lightning Tree",
	"Liquid Metal",
	"Lucky Clover",
	"Lujada's Fairystone",
	"Luminous Rock",
	"Mace Fish",
	"Magic Tome Piece",
	"Magma Powder",
	"Medicinal Moss",
	"Medicinal Sap",
	"Melocotone",
	"Miasma Log",
	"Millennial Tree",
	"Mispel Seed",
	"Mordenite",
	"Mortal Anima",
	"Mossy Driftwood",
	"Mushroom Colony",
	"Mushroom Powder",
	"Myria Fish",
	"Mystic Sphere",
	"Mythical Hide",
	"Nameless Grass",
	"Narwhal Grasshopper",
	"Natural Oil",
	"Nectar Fruit",
	"Nectar Rock",
	"Nepheline",
	"Northern Wind Flower",
	"Oil Tree Fruit",
	"Old Dragon's Claw",
	"Old Magic Tome",
	"Palma",
	"Palma Bark",
	"Palma Fruit",
	"Pentanite",
	"Phantom Color Tail",
	"Pine Fruit",
	"Pink Puniball",
	"Plant Essence",
	"Poison Needle",
	"Polar Cactus",
	"Polluted Humus",
	"Portpea",
	"Pourpremoule",
	"Pretty Shells",
	"Queen Spider Web",
	"Rainbow Fish",
	"Rainbow Gemstone",
	"Rainbow Grapevine",
	"Rainbow Wing Fragment",
	"Rapwar Water",
	"Reaper's Scythe",
	"Red Devil",
	"Red King Apple",
	"Red Puniball",
	"Refueling Extract",
	"Resentful Scream",
	"Restraint Silk",
	"Rishikelp",
	"Riverstone",
	"Rock Schloss",
	"Rose Bee",
	"Rose Crystal",
	"Rosen Leaf",
	"Roteswasser Tonic",
	"Rotwood Miasma",
	"Royal Spun Thread",
	"Running Beast Crest",
	"Rusted Sword",
	"Sage Grass",
	"Sandstorm Crystal",
	"Sapling Branch",
	"Sardine",
	"Scintilla Ore",
	"Scrap Paper",
	"Seafloor Soil",
	"Seal Branch",
	"Septrin",
	"Seriole",
	"Seven Stars",
	"Shark Bone",
	"Silence Steel",
	"Silver Beehive",
	"Silver Puniball",
	"Skull Pumpkin",
	"Sky Bubble",
	"Small Crystals",
	"Smoke Signal Flower",
	"Soft Sand",
	"Softtail",
	"Solflower",
	"Some Kind of Egg",
	"Soul Flower",
	"Spikey",
	"Spirit Isopod",
	"Spring Princess",
	"Stained Flower",
	"Star Clam",
	"Stingray",
	"Stinky Trash",
	"Stool of Nature",
	"Summer Gem",
	"Sunny Honey Flower",
	"Sweet Leaf",
	"Tall Taun",
	"Taun",
	"Three-Colored Stone",
	"Timeteller",
	"Torch of the Ages",
	"Tough Log",
	"Tough Vine",
	"Traveling Grass",
	"Trifruit",
	"Trihorn",
	"Tsurugi Mushroom",
	"Twisted Thorns",
	"Underworld Crystal",
	"Uni",
	"Uni Starfish",
	"Unknown Gemstone",
	"Unstable Lump",
	"Utopiechampignon",
	"Venom Nut",
	"Verdant Moonflower",
	"Verdeum Metal",
	"Vortex Sand",
	"Wasser Wheat",
	"Water Bamboo",
	"Water Beast Fossil",
	"Water Beast Scale",
	"Water Holy Branch",
	"Water Stone",
	"Water Uni",
	"Waterside Moss Stone",
	"Werder Nut",
	"White Sand Metal",
	"White Sand of Eternity",
	"White Shell Pearl",
	"White Swallow's Nest",
	"Wild Potato",
	"Wind Ore",
	"Wing Plant",
	"Wolf Beast's Blade",
	"Wool Flower",
	"Yugdore Water"
];