localization["jpn"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "ライザのアトリエ3 素材マップ",
		"Choose a language:": "言語:",
		"Choose a map:": "マップ:",
		"Kurken": "クーケン島",
		"Mainland": "クーケン島周辺地域",
		"Cleria": "クレリア地方",
		"Nemed": "ネメド地方",
		"Orim": "異界オーリム",
		"Code": "万象の大典",
		"Rosca": "ロスカ島",
		"Rosca Control Tower": "ロスカ島中央制御塔",
		"Ashra-am Baird Outskirts": "王都アスラ・アム・バート辺境",
		"Choose an item:": "素材:",
		"Filter Gathering Tool:": "採取道具:",
		"Hand Maximum Rank": "通常採取ランク",
		"None": "なし",
		"Rank One": "ランク1",
		"Rank Two": "ランク2",
		"Rank Three": "ランク3",
		"Rod Maximum Rank": "杖採取ランク",
		"Sickle Maximum Rank": "鎌採取ランク",
		"Axe Maximum Rank": "斧採取ランク",
		"Hammer Maximum Rank": "鎚採取ランク",
		"Net Maximum Rank": "網採取ランク",
		"Alchemy Mysteries DLC": "錬金術の神秘 DLC",
		"Art of Adventure DLC": "冒険の極意 DLC",
		"Search": "検索",
		"Number found:": "見つかった数:",
		"$1 in $2": "$1 in $2",
		"Hand Gathering": "通常採取",
		"Rod Gathering": "杖採取",
		"Sickle Gathering": "鎌採取",
		"Axe Gathering": "斧採取",
		"Hammer Gathering": "鎚採取",
		"Net Gathering": "網採取",
	},
	"item": {
		"Clean Water": "きれいな水",
		"Goats Milk": "ヤギミルク",
		"Water Bamboo": "貯水竹",
		"Plant Essence": "植物エキス",
		"Roteswasser Tonic": "ロテスヴァッサ鉱水",
		"Rapwar Water": "ラプワール水",
		"Foamy Water": "泡立つ水",
		"Jade Water": "翡翠の煌水",
		"Ancient Blue Water": "太古の蒼水",
		"Curious Aqua": "キュリオスアクア",
		"Black Water": "黒水",
		"Nameless Grass": "ナナシ草",
		"Wasser Wheat": "ヴァッサ麦",
		"Dry Grass": "コゲクサ",
		"Hill Lettuce": "丘レタス",
		"Blue Herb": "ブルーハーブ",
		"Rishikelp": "リシリコ",
		"Chomping Grass": "かみつき草",
		"Sweet Leaf": "スイートリーフ",
		"Ancient Branch": "古代樹の枝",
		"Campanula": "釣鐘草",
		"Glowing Diatom": "光珪藻",
		"Lucky Clover": "幸せクローバー",
		"Blue Clover": "アオツメクサ",
		"Light Absorbing Grass": "光吸草",
		"Rosen Leaf": "ローゼンリーフ",
		"Uni": "うに",
		"Ancient Uni": "古代うに",
		"Water Uni": "ミズうに",
		"Charcoal Uni": "炭うに",
		"Gold Uni": "黄金うに",
		"Demon Uni": "鬼いがうに",
		"Emperor Uni": "大王うに",
		"Health Flower": "病忘れの花",
		"Northern Wind Flower": "北風の花",
		"Sunny Honey Flower": "陽気な蜜花",
		"Bubble Grass": "シャボン草",
		"Stained Flower": "ステンドフラワー",
		"Caged Flower": "檻の妖花",
		"Spring Princess": "清水の白姫",
		"Soul Flower": "散命の花",
		"Rose Crystal": "ローズクリスタル",
		"Delphi Rose": "デルフィローズ",
		"Polar Cactus": "極地サボテン",
		"Timeteller": "トキシラセ",
		"Taun": "トーン",
		"Tall Taun": "セイタカトーン",
		"Sapling Branch": "若木の枝葉",
		"Medicinal Moss": "クスリゴケ",
		"Fertile Soil": "肥沃な土壌",
		"Dry Incense": "乾燥香",
		"Bitter Root": "苦い根っこ",
		"Crimson Grass": "紅草",
		"Earth's Secret Oils": "大地の秘油",
		"Sage Grass": "仙人草",
		"Life Leaf": "生命の大葉",
		"Refueling Extract": "リフュールエキス",
		"Yugdore Water": "ユグドールの湧水",
		"Stinky Trash": "生ごみ",
		"Mushroom Powder": "キノコパウダー",
		"Mispel Seed": "ミスペルシード",
		"Resentful Scream": "怨嗟の叫び",
		"Blessing of Delusion": "虚妄の祝福",
		"Dragon Flower": "リュウソウラン",
		"Demon Blood": "デモンブラッド",
		"Forest Sage": "森の賢人",
		"Celestial Tears": "天宮の涙",
		"Solflower": "太陽の花",
		"Dunkelheit": "ドンケルハイト",
		"Soft Sand": "やわらかい砂",
		"Burning Sand": "燃える砂",
		"Corail Saber": "コライユサーブル",
		"Polluted Humus": "汚染された腐葉土",
		"Emerald Glass": "エメラルドグラス",
		"Seafloor Soil": "水底の土",
		"Black Muck": "黒泥",
		"Vortex Sand": "渦巻く流砂",
		"Glittering Sand": "グリッターサンド",
		"Eroded Stone": "風化した石材",
		"Nectar Rock": "甘露岩",
		"Nepheline": "霞石",
		"Waterside Moss Stone": "水辺の苔石",
		"Ethereal Stone": "白霊岩",
		"Ancient Pillar": "古代の石柱",
		"Coral Stone": "サンゴ石",
		"Breeze Stone": "ブリーズストーン",
		"Riverstone": "リバーストン",
		"Blue Flame Riverstone": "リバーストン・蒼炎",
		"Hot Saltpeter": "熱硝石",
		"Arknite": "アークナイト",
		"Crimson Ore": "セキネツ鉱",
		"Aqua Ore": "アクア鉱",
		"Lightning Ore": "イナズマ鉱",
		"Wind Ore": "ヴィント鉱",
		"Amatite Ore": "アマタイト鉱",
		"Luminous Rock": "夜光岩",
		"Pentanite": "ペントナイト",
		"Mordenite": "モルディナイト",
		"Goldinite": "ゴルディナイト",
		"Degenesis Stone": "創生の逆さ石",
		"Septrin": "セプトリエン",
		"Adamant": "アダマント",
		"Eternal Crystal": "永遠結晶",
		"Small Crystals": "小さな晶石",
		"Unknown Gemstone": "正体不明の原石",
		"Glowing Coral": "ヒカリサンゴ",
		"White Shell Pearl": "大貝の白玉",
		"Black Shell Pearl": "大貝の黒玉",
		"Amber Fragment": "琥珀の欠片",
		"Amber Crystal": "琥珀水晶",
		"Three-Colored Stone": "三色混石",
		"Clear Branch": "クリアブランチ",
		"Holy Arbor Crystal": "聖樹結晶",
		"Underworld Crystal": "異界結晶",
		"Black Glitter Stone": "黒煌石",
		"Rainbow Gemstone": "七煌原石",
		"Dried Lumber": "乾いた木くず",
		"Flint Pepper": "フリントペッパー",
		"Explosive Vine": "炸裂カズラ",
		"Flaming Black Sand": "焔の黒砂",
		"Magma Powder": "マグマパウダー",
		"Scrap Paper": "紙くず",
		"Flammable Bark": "よく燃える樹皮",
		"Palma Bark": "パルマ樹皮",
		"Fuel Coconut": "フューエルココナッツ",
		"Natural Oil": "自然油",
		"Amber Oil": "琥珀油",
		"Fire and Ice Crystal": "炎氷結晶",
		"Eternal Fire": "常世の焔",
		"Beast Meat": "ケモノ肉",
		"Fresh Meat": "新鮮な肉",
		"Some Kind of Egg": "何かの卵",
		"Oil Tree Fruit": "アブラ木の実",
		"Nectar Fruit": "甘露の実",
		"Wild Potato": "ノライモ",
		"Portpea": "ポルト豆",
		"Red Devil": "赤い悪魔",
		"Clenoko": "クレノコ",
		"Red King Apple": "王玉",
		"Skull Pumpkin": "スカルパンプキン",
		"Venom Nut": "ヴェノムナット",
		"Palma Fruit": "パルマの実",
		"Fresh Berry": "フレスベリー",
		"Werder Nut": "ヴェルダーナッツ",
		"Kurken Fruit": "クーケンフルーツ",
		"Fortune Fruit": "フォーチュンフルーツ",
		"Rainbow Grapevine": "七色葡萄",
		"Summer Gem": "サマージェム",
		"Softtail": "ソフテール",
		"Beehive": "ハチの巣",
		"Silver Beehive": "銀のハチの巣",
		"Gold Beehive": "金のハチの巣",
		"Bee Haven": "ビーハイブン",
		"Honey Ball": "ハニーボール",
		"Eicheloa": "アイヒェロア",
		"Mushroom Colony": "群体きのこ",
		"Brodenbits": "ブローデンビッツ",
		"Utopiechampignon": "ユピトピニオン",
		"Jellyfish Mushroom": "クラゲ茸",
		"Stool of Nature": "ヒトノコシカケ",
		"Dusk Mushroom": "ヨルノキフジン",
		"Danger Mushroom": "ゲキヤバイタケ",
		"Jewel Mushroom": "宝晶セオイダケ",
		"Golden Crown": "ゴールデンクラウン",
		"Sardine": "サルディン",
		"Seriole": "セリヨル",
		"Pourpremoule": "プルムル",
		"Crab": "シュラブ",
		"Pretty Shells": "きれいな貝殻",
		"Spikey": "トゲトゲ",
		"Uni Starfish": "ウニヒトデ",
		"Chestnut": "くり",
		"Rainbow Fish": "虹魚",
		"Mace Fish": "メイスフィッシュ",
		"Stingray": "スティンレイ",
		"Myria Fish": "万年魚",
		"Lake Master": "湖底のぬし",
		"Dragonpalace Nautilus": "リュウグウオウムガイ",
		"Crown Shellfish": "王冠サザエ",
		"Imperial Fish": "皇魚",
		"Seven Stars": "ナナホシ",
		"Honey Ant": "ハニーアント",
		"Narwhal Grasshopper": "イッカクバッタ",
		"Lantern Fly": "灯篭ホタル",
		"Rose Bee": "ローズビー",
		"Giant Beetle": "オオカブト",
		"Baby Wyrm": "ベビーヴルム",
		"Crimson Cloak": "クリムゾンマント",
		"Spirit Isopod": "スピリト・モルグ",
		"Amber Fly": "アンバーフライ",
		"Lapis Papillion": "ラピス・パピヨン",
		"Trihorn": "トライホーン",
		"Ancient Bug": "王古虫",
		"Rock Schloss": "ロックシュロス",
		"Restraint Silk": "束縛する鋼糸",
		"Cotton Grass": "綿毛草",
		"Tough Vine": "丈夫なつる",
		"Arbor Ivy": "大木のツタ",
		"Queen Spider Web": "女王グモの巣",
		"Hug of Arachne": "アラクネの抱擁",
		"Eiche": "アイヒェ",
		"Tough Log": "丈夫な丸太",
		"Mossy Driftwood": "苔むした流木",
		"Holy Arbor Branch": "聖樹の大枝",
		"Palma": "パルマ",
		"Fossil Tree": "化石樹",
		"Miasma Log": "瘴気を放つ倒木",
		"Lightning Tree": "蓄雷樹",
		"Ancient Log": "太古の老木",
		"Millennial Tree": "千年樹の幼木",
		"Wing Plant": "ウィングプラント",
		"Smoke Signal Flower": "狼煙草",
		"Crispy Mushroom": "こんがりきのこ",
		"Sky Bubble": "スカイバブル",
		"Rotwood Miasma": "腐木の毒霧",
		"Water Holy Branch": "水聖樹の枝",
		"Dragon Breath": "火竜の吐息",
		"Fairystone Fragment": "魔石の欠片",
		"Dark Crystal Fragment": "闇水晶の欠片",
		"Holy Stone Fragment": "聖石の欠片",
		"Rainbow Wing Fragment": "虹翼の欠片",
		"Magic Tome Piece": "魔導書の切れ端",
		"Old Magic Tome": "古びた魔導書",
		"Holy Tree Leaf": "聖樹の葉",
		"Mystic Sphere": "フロートスフィア",
		"Ancient Fossil": "古代生物の化石",
		"Forever Ice Block": "永久氷塊",
		"Decayed Iron Pieces": "朽ちた鉄片",
		"Rusted Sword": "サビついた剣",
		"Broken Tools": "壊れた道具",
		"Liquid Metal": "液体金属",
		"Ancient Sword": "古の闘剣",
		"Blue Puniball": "ぷにぷに玉・青",
		"Green Puniball": "ぷにぷに玉・緑",
		"Red Puniball": "ぷにぷに玉・赤",
		"Black Puniball": "ぷにぷに玉・黒",
		"Silver Puniball": "ぷにぷに玉・銀",
		"Gold Puniball": "ぷにぷに玉・金",
		"Animal Hide": "動物の毛皮",
		"Mythical Hide": "幻獣の毛皮",
		"Large Bone": "大きな骨",
		"Beast Fossil": "巨獣の化石",
		"Water Beast Fossil": "水獣の巨大化石",
		"Water Beast Scale": "水獣のウロコ",
		"Cave Bat Wing": "洞窟コウモリの羽",
		"White Swallow's Nest": "白ツバメの古巣",
		"Beast Fin": "魔獣の背びれ",
		"Beast Shell": "魔獣の甲殻",
		"Beast Scales": "魔獣のウロコ",
		"Giant Bird Feather": "巨鳥の風切羽",
		"Giant Bird Egg": "巨鳥の大卵",
		"Goat Horn": "ヤギ角",
		"Demon Claws": "魔爪",
		"Fluffy Wool": "モフモフウール",
		"Poison Needle": "毒の細針",
		"Dragon Wing": "翼竜の翼",
		"Dragon Egg": "翼竜の卵",
		"Dragon Eye": "竜眼",
		"Dragon Bone": "竜骨",
		"Dragon Meat": "竜肉",
		"Guardian Armor": "守護者の堅甲",
		"Heroic Spirit": "英霊の魂",
		"Giant Puniball": "大ぷに玉",
		"Fairy Horn Adornment": "妖精の大角飾り",
		"Giant Claws": "巨大な爪",
		"Golem Core": "ゴーレムコア",
		"Inverted Scale": "逆鱗",
		"Ether Core": "エーテルコア",
		"Imp's Lost Item": "小悪魔の落とし物",
		"Elemental Force": "エレメントフォース",
		"Twisted Thorns": "絡みつく根",
		"Curved Long Nails": "湾曲した長爪",
		"Running Beast Crest": "走獣のトサカ",
		"Phantom Color Tail": "幻色尾",
		"Wolf Beast's Blade": "狼獣の狩刃",
		"Duet Stock Solution": "ドゥエット原液",
		"Scintilla Ore": "シンティラ鉱石",
		"Lujada's Fairystone": "ルジャーダの魔石",
		"Pink Puniball": "ぷにぷに玉・桜",
		"Giant Kurken Fruit": "巨大クーケンフルーツ",
		"Cow Milk": "ウシミルク",
		"Thick Reference Book": "分厚い参考書",
		"Giant Claws": "巨大な爪",
		"White Swallow's Nest": "白ツバメの古巣",
		"Water Beast Scale": "水獣のウロコ",
		"Mythical Hide": "幻獣の毛皮",
		"Dragon Meat": "竜肉",
		"Heroic Spirit": "英霊の魂",
		"Dragon Wing": "翼竜の翼",
		"Demon Claws": "魔爪",
		"Dragon Bone": "竜骨",
		"Dragon Eye": "竜眼",
		"Spirit Catalysts": "精霊触媒",
		"Ether Core": "エーテルコア",
		"Spirit Catalysts": "精霊触媒",
		"Guiding Bird Feather": "導きの鳥の羽",
		"Gnade Ring": "グナーデリング",
		"Phantom Scarf": "ファントムスカーフ",
		"Chick Doll": "ひよこ人形",
		"Myria Fish": "万年魚",
		"Summer Gem": "サマージェム",
		"Spring Princess": "清水の白姫",
		"Giant Beetle": "オオカブト",
		"Corail Saber": "コライユサーブル",
		"Celestial Tears": "天宮の涙",
		"Sky Bubble": "スカイバブル",
		"Rainbow Fish": "虹魚",
		"Red Devil": "赤い悪魔",
		"Chomping Grass": "かみつき草",
		"Solflower": "太陽の花",
		"Dark Crystal Fragment": "闇水晶の欠片",
		"Campanula": "釣鐘草",
		"Earth's Secret Oils": "大地の秘油",
		"Softtail": "ソフテール",
		"Dunkelheit": "ドンケルハイト",
		"Emperor Uni": "大王うに",
		"Light Absorbing Grass": "光吸草",
		"Black Muck": "黒泥",
		"Fire and Ice Crystal": "炎氷結晶",
		"Explosive Uni": "爆粉うに",
		"Craft": "クラフト",
		"Bomb": "フラム",
		"Ice Bomb": "レヘルン",
		"Plajig": "プラジグ",
		"Luft": "ルフト",
		"Trio Craft": "クラフトリオ",
		"Anemo Bomb": "アネモフラム",
		"Melting Ice Bomb": "メルトレへルン",
		"Lia Plajig": "リアプラジグ",
		"Edle Luft": "エーデルフト",
		"Lunar Lamp": "ルナーランプ",
		"Astro Rose": "アストローズ",
		"Lavinage": "ラヴィネージュ",
		"Grazeit": "グランツァイト",
		"Himmel Feather": "ヒンメルフェザー",
		"Forbidden Spell Book": "禁忌の秘術書",
		"Zwei Resonance": "ツヴァイレゾナンス",
		"Cross Judgement": "クロスジャッジメント",
		"Sourcebook of Acacia": "アカシアの原典",
		"Grass Beans": "グラスビーンズ",
		"Dry Biscuit": "ドライビスク",
		"Nectar": "ネクタル",
		"Elixir": "エリキシル剤",
		"Hermit Ointment": "隠者の軟膏",
		"Fairy Elixir": "妖精の秘薬",
		"Mist of Silence": "静寂のミスト",
		"Golden Heart": "ゴールドハート",
		"Mythic Nectar": "ミソロジーネクタル",
		"Eternal Holy Grail": "永劫回帰の聖杯",
		"Fish Oil": "魚油リキッド",
		"War Powder": "ウォーパウダー",
		"Energianica": "エネルジアニカ",
		"Mystic Robe": "神秘の羽衣",
		"Miracle Ebonyal": "妖薬エボニアル",
		"Astronomical Clock": "時空の天文時計",
		"Fake Bouquet": "偽りのブーケ",
		"Haze Breath": "ヘイズブレス",
		"Prison of Decline": "衰勢の牢獄",
		"Barbaric Horn Whistle": "蛮勇の角笛",
		"Depiction of a Devil": "悪魔の写し絵",
		"Hourglass of Origin": "起源の砂時計",
		"Cantera of Calamity": "災いのカンテラ",
		"Prelude of the Gods": "神々のプレリュード",
		"Call of Abyss": "エイビスコール",
		"Grass Sickle": "草刈り鎌",
		"Silent Sickle": "サイレントシックル",
		"Woodcutter's Axe": "薪割り斧",
		"Golden Axe": "ゴールデンアックス",
		"Hammer": "ハンマー",
		"Ravage Hammer": "ラベッジハンマー",
		"Fishing Rod": "釣り竿",
		"Divine Fishing Rod": "神竿バルムヘル",
		"Catcher's Net": "捕獲網",
		"Master Catcher's Net": "達人の捕獲網",
		"Wind Shoes": "風の精の靴",
		"Emerald Band": "エメラルドバンド",
		"Air Drop": "エアドロップ",
		"Summoner's Bell": "サモナーズベル",
		"Red Neutralizer": "中和剤・赤",
		"Blue Neutralizer": "中和剤・青",
		"Yellow Neutralizer": "中和剤・黄",
		"Green Neutralizer": "中和剤・緑",
		"Rainbow Neutralizer": "中和剤・虹",
		"Honey": "ハチミツ",
		"Berry Syrup": "ベリーシロップ",
		"Flour": "小麦粉",
		"Devil's Breath": "デビルズブレス",
		"Puppet Liquid": "パペットリキッド",
		"Super Pure Water": "超純水",
		"Traveler's Water Orb": "旅人の水珠",
		"Medica Powder": "メディカパウダー",
		"Doctor's Bottle": "ドクトルボトル",
		"Holy Drop": "聖なる雫",
		"Taboo Drop": "禁忌の雫",
		"Zettel": "ゼッテル",
		"Reinforced Zettel": "強化ゼッテル",
		"Pearl Crystal": "パールクリスタル",
		"Amberlite": "アンバーライト",
		"Spirinite": "スピリナイト",
		"Waking Emerald": "ウェイクエメラルド",
		"Arc en Ciel": "アルクァンシェル",
		"Dark Glittering Oval": "煌黒の曲玉",
		"Nitro Chips": "ニトロチップ",
		"Donour Powder": "ドナーパウダー",
		"Blue Flame Ember": "蒼炎の種火",
		"Mixing Oil": "ミックスオイル",
		"Flint Charcoal": "火打炭",
		"Colorful Oil": "カラフルオイル",
		"Solid Ice Fuel": "固形燃氷",
		"Feather Draft": "フェザードラフト",
		"Ingot": "インゴット",
		"Startium": "スタルチウム",
		"Creaminea": "クリミネア",
		"Goldoterion": "ゴルドテリオン",
		"Grand Orgen": "グランツオルゲン",
		"Alchemy Fibers": "錬金繊維",
		"Himmel Schulwa": "ヒンメルシュルワー",
		"Eternal Firo": "エターナルフィーロ",
		"Cloth": "クロース",
		"Bestial Air": "ビーストエア",
		"Sorcery Rose": "ソーサリーローズ",
		"Royal Cloth": "ロイヤルクロース",
		"Sage Coat": "セージコート",
		"Puni Leather": "ぷにレザー",
		"Master Leather": "マスターレザー",
		"Dread Leather": "ドレッドレザー",
		"Grace Nero": "グレースネロ",
		"Philosopher's Stone": "賢者の石",
		"Olden Philosopher's Stone": "古の賢者の石",
		"Honey Crystal": "蜜結晶",
		"Glass Flower": "ガラスの花",
		"Wind Crystal Ball": "風晶玉",
		"Growing Quartz": "グロウスクォーツ",
		"Spirit Bottle": "精霊の小瓶",
		"Crystal Element": "クリスタルエレメント",
		"Poisonous Liquid": "ポイズンリキッド",
		"The Grim Reaper": "グリムリーパー",
		"Polishing Powder": "研磨剤",
		"Rose Perfume": "ローズパフューム",
		"Spring Wind Pinwheel": "春風の風車",
		"Luft Atomizer": "ルフトアトマイザー",
		"Exotic Lantern": "異国のランタン",
		"Four Seasons Dome": "四季のドーム",
		"Magna Mater": "マグナマーテル",
		"Polishing Sand": "磨き砂",
		"Marblestone": "マーブルストーン",
		"Eternal Monolith": "悠久のモノリス",
		"Plant Seeds": "植物の種",
		"Stone Seeds": "石の種",
		"Fire Seeds": "火の種",
		"Water Seeds": "水の種",
		"Mystic Seeds": "神秘の種",
		"Poison Seeds": "毒の種",
		"Golden Seeds": "金の種",
		"Duet Solvent Solution": "ドゥエット溶剤",
		"Fairystone Compass": "魔石の指針",
		"Scintilla Glass": "シンティラのガラス",
		"Lujada Crystals": "ルジャーダの結晶",
		"Glass Goblet": "ガラスのゴブレット",
		"Fairystone Pendant": "魔石のペンダント",
		"Hollow Key": "虚ろの鍵",
		"The Starting Key": "最初の鍵",
		"Castle Door Key": "城扉の鍵",
		"Blockade Key": "封鎖区画の鍵",
		"Key of Honor": "栄誉の鍵",
		"Pristine Key": "無垢の鍵",
		"Red Stone Key": "赤石の鍵",
		"Blue Stone Key": "青石の鍵",
		"Yellow Stone Key": "黄石の鍵",
		"Green Stone Key": "緑石の鍵",
		"Red Iron Key": "紅鉄の鍵",
		"Blue Iron Key": "蒼鉄の鍵",
		"Orange Iron Key": "橙鉄の鍵",
		"Jade Iron Key": "碧鉄の鍵",
		"White Silver Key": "白銀の鍵",
		"Golden Key": "黄金の鍵",
		"Rainbow Key": "虹剛晶の鍵",
		"Red Wing Key": "朱羽の鍵",
		"Blue Wing Key": "藍羽の鍵",
		"Light Wing Key": "光羽の鍵",
		"Leaf Wing Key": "葉羽の鍵",
		"Scarlet Wing Key": "緋翼の鍵",
		"Cloud Wing Key": "雲翼の鍵",
		"Wing Key": "閃翼の鍵",
		"Tree Wing Key": "樹翼の鍵",
		"Firebird Key": "鳳凰の鍵",
		"Phoenix Key": "不死鳥の鍵",
		"Phantom Wing Key": "幻翼の支配者の鍵",
		"Fire Gear Key": "火車の鍵",
		"Water Gear Key": "水車の鍵",
		"Gear Key": "歯車の鍵",
		"Wind Gear Key": "風車の鍵",
		"Fire Clock Key": "火時計の鍵",
		"Water Clock Key": "水時計の鍵",
		"Hourglass Key": "砂時計の鍵",
		"Gear Gimmick Key": "歯車仕掛けの鍵",
		"Key to the Future": "未来の鍵",
		"Key to the Past": "過去の鍵",
		"Key of All Times": "時を統べる者の鍵",
		"Key of Bright Sky": "明空の鍵",
		"Key of Blue Sky": "蒼空の鍵",
		"Key of Twilight Sky": "夕空の鍵",
		"Key of Night Sky": "夜空の鍵",
		"Scarlet Key": "緋星の鍵",
		"Dark Star Key": "暗星の鍵",
		"Bright Star Key": "輝星の鍵",
		"Meteor Key": "流星の鍵",
		"Great Heavens Key": "大天陽の鍵",
		"Moon Shadow Key": "小月影の鍵",
		"Soul Cradle Key": "魂のゆりかごの鍵",
		"Key of Truth": "ほんとうの鍵",
		"Key of the End": "おわりの鍵",
		"Shining Key": "かがやく鍵",
		"Alchemist's Staff": "錬金術士の杖",
		"Svate Rod": "スヴェートロッド",
		"Celestial Seeker": "セレスティアシーカー",
		"Sparkling Reverie": "スパークルレヴァリエ",
		"Agnes Luce": "アニエスルーチェ",
		"Ciel Shoot": "シエルシュート",
		"Yale Soar": "エールソアー",
		"Croiselt": "クロワゼルト",
		"Astrumnox": "アストルムノクス",
		"Astral Regalia": "アストラルレガリア",
		"Smite Blade": "スマイトブレード",
		"Sword of Rupture": "破離剣",
		"Lord Guardian": "ロードガーディアン",
		"Demon Ender": "デーモンエンダー",
		"Liese Divider": "リーゼディバイダー",
		"Sharp Edge": "シャープエッジ",
		"Paradiera": "パラディエラ",
		"Luna Solis": "ルナ・ソリス",
		"Amphisbaena": "アンフェスバエナ",
		"Ifestio": "イフェスティオ",
		"Aristoclite": "アリストクライト",
		"Herzog": "ヘルツォーク",
		"Might of Heaven": "神威",
		"Edel Schwert": "エーデルシュヴァルト",
		"Efflorescence": "エフロレッセンス",
		"Wise Wand": "ワイズワンド",
		"Educator": "エデュケーター",
		"Occult Wisdom": "幽玄なる叡智の杖",
		"Nachfolger": "ナーハフォルガー",
		"Genesis Staff": "創世の輝杖",
		"Trisker": "トライスカー",
		"Aurora": "アウローラ",
		"Oren Herald": "オーレンヘルディン",
		"Ventiska": "ヴェンティスカ",
		"Nevernoche": "ネーヴェルノーチェ",
		"Onyx Blade": "オニキスブレイド",
		"Lysil Edge": "リジルエッジ",
		"Baron's Light": "バロンドライト",
		"Unfold": "アンフォールド",
		"Lost Alucard": "ロストアルカード",
		"Iron Fan": "鉄扇",
		"Purple Orchid": "紫蘭",
		"Scarlet Heaven": "緋天",
		"Jing Qing Fan": "景清扇",
		"Shrine Maiden's Dance": "巫女神楽",
		"Wild Axe": "ワイルドアックス",
		"Daybreak": "デイブレイク",
		"Estacado": "エスタカード",
		"Elde Divide": "エルデディバイド",
		"Diamantis": "ディアマンティス",
		"Moon Quake": "ムーンクエイク",
		"Crepusclype": "クレプスクライム",
		"Gravimarius": "グラヴィマリウス",
		"Elder Lily": "エルダーリリー",
		"Raventoad": "レーヴェントアード",
		"Mistral Cane": "ミストラルケーン",
		"Etoile Filant": "エトワールフィラント",
		"Hashbringer": "ハッシュブリンガー",
		"Vita Reaper": "ヴィータリーパー",
		"Folklore": "フォルクロール",
		"Windword": "ウインドワード",
		"Crimson Mist": "クリムゾンミスト",
		"Void Punisher": "ヴォイドパニッシャー",
		"Self-defense Fans": "護身扇",
		"Brute Veil": "ブルートベイル",
		"Solmarkt": "ソルマルクト",
		"Noble Tunic": "ノーブルチュニック",
		"Leather Protector": "レザープロテクター",
		"Bone Armor": "ボーンアーマー",
		"Mage's Robe": "術者のローブ",
		"Soldier's Cuirass": "ソルジャーキュイラス",
		"Radiant Plate": "レディアントプレート",
		"Fairy Cloak": "妖精の羽衣",
		"Chainmail Cloak": "チェインクローク",
		"Foreign Armor": "異国の甲冑",
		"Elven Robe": "エルフの法衣",
		"Moonlight Cloak": "月影の外套",
		"Dragoon Mail": "ドラグーンメイル",
		"Kruger Cloak": "クルーガークローク",
		"Meuchelmolder": "モイヒェルメルダー",
		"Armanoir": "アルマノワール",
		"Uni Charm": "うに型チャーム",
		"Energy Pendant": "エナジーペンダント",
		"Gnade Ring": "グナーデリング",
		"Phantom Scarf": "ファントムスカーフ",
		"Locket of Devotion": "献身のロケット",
		"Migratory Charm": "渡り鳥のお守り",
		"Quartz Necklace": "クオーツネックレス",
		"Warlock Ring": "ウォーロックリング",
		"Warrior Bangle": "闘士のバングル",
		"Clairvoyance Monocle": "千里眼のモノクル",
		"Harnal Ring": "ハーナルリング",
		"Warrior Choker": "軍師のチョーカー",
		"Four Spirits Amulet": "四精霊のアミュレット",
		"Cluster Cuffs": "クラスタカフ",
		"Baron's Crown": "バロンズクラウン",
		"Dragon Scale Necklace": "竜鱗の首飾り",
		"Broken Hoe": "折れたクワ",
		"Light and Sturdy Hoe": "軽くて丈夫なクワ",
		"Fairystone Light": "魔石の光源",
		"Fairystone Light EX": "魔石の光源・改",
		"Scruffy Drawing": "へたくそな図面",
		"Flame Hair Clip": "炎の髪留め",
		"Hammer Brooch": "ハンマーのブローチ",
		"Duet Stock Solution+": "高濃度のドゥエット原液",
		"Duet Solvent Solution EX": "ドゥエット溶剤・改",
		"Seeds of Light": "光の種",
		"Seeds of Light EX": "光の種・改",
		"Disturbing Bell": "かく乱の鈴",
		"Emil's Tablet": "エミルの石盤",
		"Emil's Book": "エミルの書",
		"True Silver": "真の銀",
		"Chart of Another Sky": "異空の界図",
		"Fi's Necklace": "フィーの首飾り",
		"Shiny Necklace": "ピカピカの首飾り",
		"Dancing Bird Pinwheel": "舞鳥の風車",
		"Silver Crystal": "真銀の結晶体",
		"Celestial Globe of Another Sky": "異空の天球儀",
		"High Quality Wood": "高品質な木材",
		"Sturdy Wood": "頑丈な加工木材",
		"Broken Ancient Artifact": "壊れた古式秘具",
		"New Purifier": "新・浄化装置",
		"Broken Light": "壊れた灯り",
		"Lamp of the Beginning": "始まりのランプ",
		"Age of God Manual": "機械教本神代の章",
		"Dragon Bone Fragment": "竜骨の欠片",
		"Ancient Dragon Gem": "古竜の宝石",
		"Indestructible Box": "朽ち果てぬ箱",
		"Auxiliary Prosthesis": "補助義手",
		"Wild Meat on the Bone": "野性的な骨付き肉",
		"Father's Album": "父の図版帖",
		"Desalination Equipment EX": "淡水化装置・改",
		"Iridescent Mucus": "虹色の粘液",
		"Iridescent High-Purity Mucus": "虹色の高純度粘液",
		"High Quality Coral Stone": "高品質なサンゴ石",
		"&quot;Agnes Luce&quot; Recipe": "「アニエスルーチェ」のレシピ",
		"&quot;Astral Regalia&quot; Recipe": "「アストラルレガリア」のレシピ",
		"&quot;Ifestio&quot; Recipe": "「イフェスティオ」のレシピ",
		"&quot;Efflorescence&quot; Recipe": "「エフロレッセンス」のレシピ",
		"&quot;Genesis Staff&quot; Recipe": "「創世の輝杖」のレシピ",
		"&quot;Nevernoche&quot; Recipe": "「ネーヴェルノーチェ」のレシピ",
		"&quot;Lost Alucard&quot; Recipe": "「ロストアルカード」のレシピ",
		"&quot;Shrine Maiden's Dance&quot; Recipe": "「巫女神楽」のレシピ",
		"&quot;Diamantis&quot; Recipe": "「ディアマンティス」のレシピ",
		"&quot;Raventoad&quot; Recipe": "「レーヴェントアード」のレシピ",
		"Federica's Pendant": "フェデリーカのペンダント",
		"Small Tablet": "小さな石板",
		"&quot;Glassware&quot; Recipe": "「ガラス製品」のレシピ",
		"&quot;Fairystone Wares&quot; Recipe": "「魔石製品」のレシピ",
		"&quot;Iridescent High-Purity Mucus&quot; Recipe": "「虹色の高純度粘液」のレシピ",
		"&quot;Scintilla Glass&quot; Recipe": "「シンティラのガラス」のレシピ",
		"&quot;Lujada Crystal&quot; Recipe": "「ルジャーダの結晶」のレシピ",
		"&quot;Fairystone Light&quot; Recipe": "「魔石の光源」のレシピ",
		"&quot;Pristine Key&quot; Recipe": "「無垢の鍵」のレシピ",
		"&quot;Disturbing Bell&quot; Recipe": "「かく乱の鈴」のレシピ",
		"&quot;Seeds of Light EX&quot; Recipe": "「光の種・改」のレシピ",
		"&quot;Emil's Tablet&quot; Recipe": "「エミルの石盤」のレシピ",
		"&quot;Duet Solvent Solution EX&quot; Recipe": "「ドゥエット溶剤・改」のレシピ",
		"&quot;Fairystone Compass&quot; Recipe": "「魔石の指針」のレシピ",
		"&quot;Hammer Brooch&quot; Recipe": "「ハンマーのブローチ」のレシピ",
		"&quot;Flame Hair Clip&quot; Recipe": "「炎の髪留め」のレシピ",
		"&quot;Shiny Necklace&quot; Recipe": "「ピカピカの首飾り」のレシピ",
		"&quot;Dancing Bird Pinwheel&quot; Recipe": "「舞鳥の風車」のレシピ",
		"&quot;Silver Crystal&quot; Recipe": "「真銀の結晶体」のレシピ",
		"&quot;Globe of Another Sky&quot; Recipe": "「異空の天球儀」のレシピ",
		"&quot;Light and Sturdy Hoe&quot; Recipe": "「軽くて丈夫なクワ」のレシピ",
		"&quot;Puppet Liquid&quot; Recipe": "「パペットリキッド」のレシピ",
		"&quot;Flint Charcoal&quot; Recipe": "「火打炭」のレシピ",
		"&quot;Solid Ice Fuel&quot; Recipe": "「固形燃氷」のレシピ",
		"&quot;Four Seasons Dome&quot; Recipe": "「四季のドーム」のレシピ",
		"&quot;Mage's Robe&quot; Recipe": "「術者のローブ」のレシピ",
		"&quot;Soldier's Cuirass&quot; Recipe": "「ソルジャーキュイラス」のレシピ",
		"&quot;Radiant Plate&quot; Recipe": "「レディアントプレート」のレシピ",
		"&quot;Elven Robe&quot; Recipe": "「エルフの法衣」のレシピ",
		"&quot;Moonlight Cloak&quot; Recipe": "「月影の外套」のレシピ",
		"&quot;Dragoon Mail&quot; Recipe": "「ドラグーンメイル」のレシピ",
		"&quot;Summoner's Bell&quot; Recipe": "「サモナーズベル」のレシピ",
		"&quot;Sturdy Wood&quot; Recipe": "「頑丈な加工木材」のレシピ",
		"&quot;New Purifier&quot; Recipe": "「新・浄化装置」のレシピ",
		"&quot;Lamp of the Beginning&quot; Recipe": "「始まりのランプ」のレシピ",
		"&quot;Age of God Manual&quot; Recipe": "「機械教本神代の章」のレシピ",
		"&quot;Ancient Dragon Gem&quot; Recipe": "「古竜の宝石」のレシピ",
		"&quot;Indestructible Box&quot; Recipe": "「朽ち果てぬ箱」のレシピ",
		"&quot;Wild Meat on the Bone&quot; Recipe": "「野性的な骨付き肉」のレシピ",
		"&quot;Desalination Equipment EX&quot; Recipe": "「淡水化装置・改」のレシピ",
		"&quot;Grace Nero&quot; Recipe": "「グレースネロ」のレシピ",
		"&quot;Two-handed Staff&quot; Recipe": "「両手杖」のレシピ",
		"&quot;Bow&quot; Recipe": "「弓」のレシピ",
		"&quot;Great Sword&quot; Recipe": "「大剣」のレシピ",
		"&quot;Double Sword&quot; Recipe": "「双剣」のレシピ",
		"&quot;Long Sword&quot; Recipe": "「長巻」のレシピ",
		"&quot;Single-handed Staff&quot; Recipe": "「片手杖」のレシピ",
		"&quot;Claw&quot; Recipe": "「爪」のレシピ",
		"&quot;Single-handed Sword&quot; Recipe": "「片手剣」のレシピ",
		"&quot;Fan&quot; Recipe": "「扇」のレシピ",
		"&quot;Axe&quot; Recipe": "「斧」のレシピ",
		"&quot;War Hammer&quot; Recipe": "「槌」のレシピ",
		"&quot;Legendary Sword&quot; Recipe": "「歴戦の名剣」のレシピ",
		"&quot;Plant Seeds&quot; Recipe": "「植物の種」のレシピ",
		"&quot;Stone Seeds&quot; Recipe": "「石の種」のレシピ",
		"&quot;Fire Seeds&quot; Recipe": "「火の種」のレシピ",
		"&quot;Water Seeds&quot; Recipe": "「水の種」のレシピ",
		"&quot;Mystic Seeds&quot; Recipe": "「神秘の種」のレシピ",
		"&quot;Poison Seeds&quot; Recipe": "「毒の種」のレシピ",
		"&quot;Golden Seeds&quot; Recipe": "「金の種」のレシピ",
		"Packed Rice": "バクダン飯",
		"Roasted Chicken": "鶏肉の直火串焼き",
		"Gibier Burger": "ジビエバーガー",
		"Mixed Sandwich": "お手軽ミックスサンド",
		"Smoked Meat": "冒険者の燻製肉",
		"Dried Meat Pizza": "干し肉とチーズのピザ",
		"Fresh Fish Carpaccio": "鮮魚のカルパッチョ",
		"Summer Veggie Stew": "夏野菜のポトフ",
		"Forest Green Pasta": "森林グリーンパスタ",
		"Seafood Paella": "海鮮パエリア",
		"Red Chili Soup": "レッドチリスープ",
		"Steak on Crystal": "結晶板焼きステーキ",
		"Roasted Monster Fish": "怪魚の丸焼き",
		"Beef Omelette Rice": "ビーフデミオムライス",
		"White Sauce Ragu": "ホワイトラグー",
		"Observing Hut": "観測小屋",
		"Farm": "農園",
		"Laboratory": "研究所",
		"Room Extension 1": "部屋の増築１",
		"Room Extension 2": "部屋の増築２",
		"Build Observing Hut": "観測小屋の建築",
		"Build Lookout": "見張り台の建築",
		"Build Windmill": "風車の建築",
		"Build Greenhouse": "温室の建築",
		"Build Celestial Globe": "天球儀の建築",
		"Build Laboratory": "研究所の建築",
		"Rebuild (Observing Hut)": "建て替え（観測小屋）",
		"Rebuild (Farm)": "建て替え（農園）",
		"Rebuild (Laboratory)": "建て替え（研究所）",
		"Chick Doll": "ひよこ人形",
		"Crystal Object": "クリスタルの置物",
		"Fairy Doll": "妖精さん人形",
		"Puni Jelly": "ぷにゼリー",
		"Puni Doll": "ぷにんぎょう",
		"Exhibition Stand": "展示台",
		"Hanging Lantern": "飾りランタン",
		"Round Table": "丸テーブル",
		"Leather Sofa": "革のソファ",
		"Chic Sofa": "シックなソファ",
		"Elegant Low Table": "上品なローテーブル",
		"Pendulum Clock": "振り子時計",
		"Piano": "ピアノ",
		"Cute Bed": "かわいいベッド",
		"Extravagant Bed": "豪華なベッド",
		"Barrel": "たる",
		"Fashionable Bench": "おしゃれなベンチ",
		"Garden Table": "ガーデンテーブル",
		"Potted Plant": "彩花の鉢植え",
		"Oren Doll": "オーレン人形",
		"Dinner Bell": "ディナーベル",
		"Decorative Sword": "飾り大剣",
		"Resort Bed": "リゾートベッド",
		"Resort Sofa": "リゾートソファ",
		"Table with Tablecloth": "クロス付きテーブル",
		"Potted Palm": "ヤシの鉢植え",
		"Music Stand": "譜面台",
		"Giant Manuscript": "巨大写本",
		"Pixie Pot": "小妖精の鉢植え",
		"Great Elemental's Chair": "大精霊の椅子",
		"Celestial Body Model": "浮遊天球",
		"Farm Photo": "農村の写真",
		"Countryside Photo": "田舎町の写真",
		"Rocking Chair": "ロッキングチェア",
		"Cute Sofa": "かわいいソファ",
		"Blackboard": "黒板",
		"Blacksmith Statue": "とある武器職人の像",
		"Goat": "ヤギ",
		"Crisp Bun": "こんがり食パン",
		"Pumpkin Doll": "かぼちゃ人形",
		"Globe": "ちきゅーぎ",
		"Transport Cannon": "配達用大砲",
		"Ashra Donut": "アスラ・ドーナツ",
		"Giant Luceaux Seed": "巨大なリュコの実",
		"Mountain of Sweets": "山盛りお菓子",
		"Exotic Horn": "異国の角笛",
		"Apple Basket": "リンゴのバスケット",
		"Knight's Armor": "騎士の甲冑",
		"Teddy Bear": "テディベア",
		"Beautiful Picture Frame": "立派な写真立て",
		"Mysterious Broom": "不思議な箒",
		"Phonograph": "蓄音機",
		"Weasel Doll": "イタチの人形",
		"Shiny Bust": "光り輝く胸像",
		"Sparkling Bust": "煌く胸像",
		"Photo of the Capital": "王都の写真",
		"Fi Doll": "フィー人形",
		"Candy House": "お菓子の家",
		"Mini Cork Board": "ミニコルクボード",
		"Books And Bookends": "本とブックエンド",
		"Tea Set": "ティーセット",
		"Synthesis Eqp Set": "調合器具セット",
		"Basket of Uni": "山盛りうに",
		"Mushroom Shaped Lamp": "キノコ型ランプ",
		"Small Devil Doll": "小悪魔人形",
		"Downwind": "ダウンウィンド",
		"Rainbow Lapis": "レインボーラピス",
		"Cerberus Spirit": "サーベラススピリット",
		"Draconic Arrow": "ドラコニックアロー",
		"Maleficus": "マレフィクス",
		"Calamity Code": "カラミティコード",
		"Sugar Drip": "シュガードリップ",
		"Eternal Spring": "不変の薬泉",
		"Suonare": "スウォナーレ",
		"Voltage Liberator": "ボルトリベレイト",
		"Windsong Fowl": "風詠みの鳥像",
		"Bell of Tranquility": "沈静の呼び鈴",
		"Lovely Blossom": "ラブリーブロッサム",
		"Neutronenstern": "ナイトロシュテルン",
		"Violet Cauldron": "紫黒の大壺",
		"Seal Branch": "シールグレイン",
		"Old Dragon's Claw": "古竜の鉤爪",
		"Water Stone": "水環石",
		"Silence Steel": "サイレスチル",
		"Verdant Moonflower": "深緑の月華",
		"Heavenly Seawater": "天海水",
		"Clearfish": "六花魚",
		"Pine Fruit": "ホウリの実",
		"Melocotone": "メロコトーン",
		"Star Clam": "ほししじみ",
		"Gemeater": "ジェムイータ",
		"Tsurugi Mushroom": "ツルギタケ",
		"Floating Petal Stone": "浮上花石",
		"Verdeum Metal": "ベルデウム金属",
		"Wool Flower": "風乗りの花",
		"Cleaner Plant": "ラルコ草",
		"Medicinal Sap": "薬樹液",
		"Immortal Sapling": "不朽の杣木",
		"Blessed Clouds": "恵みの綿雲",
		"Carved Relic": "木彫りの遺物",
		"Reaper's Scythe": "死神の大鎌",
		"Heavenly Rain Thread": "天梅雨の糸",
		"Unstable Lump": "不安定な塊",
		"Ignis Nut": "イグニスナッツ",
		"Ancient Scroll": "古風なスクロール",
		"Edelhard": "エーデルハルト",
		"Medica Solution": "メディカ溶液",
		"Toxited": "トキシテッド",
		"Jelly Sandwich": "ゼリーサンド",
		"Crimson Birth": "クリムゾンバース",
		"Riot Coal": "ライオットコール",
		"Vajra Wire": "金剛線",
		"Lumiere Potpourri": "リュミエールポプリ",
		"Ideal Unit": "イデアルユニット",
		"Dragon's Tears": "竜の涙",
		"Antique Style": "アンティークスタイル",
		"Hunter's Wear": "ハンターウェア",
		"Luminous Gold Armor": "光輝の金鎧",
		"Immortal Gloves": "イモータルグローブ",
		"Fleur Corsage": "フルールコサージュ",
		"Lamp of Force": "理力のランプ",
		"Aurora Jewel": "アウロラジュエル",
		"Glück Potion": "グリュック薬毒",
		"Torch of the Ages": "千古の灯火",
		"Royal Spun Thread": "王家の紡糸",
		"White Sand of Eternity": "久遠の白砂",
		"Traveling Grass": "旅する枯草",
		"White Sand Metal": "白砂金属",
		"Ametrite": "アメトライト",
		"Forgotten Pottery": "遺却された陶器",
		"Desert Cleaner": "砂漠の掃除屋",
		"Trifruit": "トライフルーツ",
		"Cactus Blossom": "サボタン",
		"Mortal Anima": "モータルアニマ",
		"Shark Bone": "ティブロボーン",
		"Exotic Meat": "珍味な肉",
		"Kala's Translated Texts (Copy)": "カラの翻訳文献・写し",
		"Golden Puniball": "ぷにぷに玉・黄金",
		"Crimson Neutralizer": "中和剤・真紅",
		"Azure Neutralizer": "中和剤・蒼天",
		"Emerald Neutralizer": "中和剤・翠緑",
		"Thunder Neutralizer": "中和剤・万雷",
		"Hard Ingot": "インゴット・堅",
		"Soft Cloth": "クロース・柔",
		"Strong Alchemy Fibers": "錬金繊維・剛",
		"Flame Mixing Oil": "ミックスオイル・燃",
		"Superior Medica Powder": "メディカパウダー・優",
		"Strong Poisonous Liquid": "ポイズンリキッド・強",
		"&quot;White Tower Key&quot; Recipe": "「白楼の鍵」のレシピ",
		"Sandstorm Crystal": "砂嵐の結晶",
		"White Tower Key": "白楼の鍵",
		"Bloodstone Key": "血晶石の鍵",
		"Fallen Angel Key": "堕天の鍵",
		"Dream Key": "夢想の鍵",
		"Eclipse Key": "日蝕の鍵",
		"Colorless Crystal Key": "無彩晶の鍵",
		"Divine Wing Ruler Key": "神翼の支配者の鍵",
		"Master of the Void Key": "虚空を統べる者の鍵",
		"Cradle of Life Key": "生命のゆりかごの鍵",
		"White Moon's Soul": "白月の魂",
		"Universe Sphere": "ユニバースフィア",
		"Fairywood": "フェアリーバオム",
		"Mini Volcano": "リーテンボルケ",
		"Seven-Color Pansy": "七色ビオラ",
		"Fairy Sapling": "妖精の苗木",
		"Lava Rock": "ラーヴァローク",
		"Moon Fragment": "月のフラグメント",
		"&quot;White Moon's Soul&quot; Recipe": "「白月の魂」のレシピ",
	},
	"monster": {
		"Blue Puni": "青ぷに",
		"Green Puni": "緑ぷに",
		"Red Puni": "赤ぷに",
		"Flower Puni": "花ぷに",
		"Black Puni": "黒ぷに",
		"Silver Puni": "シルバーぷに",
		"Gold Puni": "ゴールドぷに",
		"Lavender Puni": "ラベンダーぷに",
		"Big Puni": "でかぷに",
		"Shining Puni": "シャイニングぷに",
		"Rafflesia Puni": "ラフレシアぷに",
		"Darkness Puni": "ダークネスぷに",
		"Precious Puni": "プレシャスぷに",
		"Giant Weasel": "オオイタチ",
		"Bluefin": "ブルーフィン",
		"Silky Fur": "シルキーファー",
		"Scarf Bunny": "スカーフバニー",
		"Night Hunter": "ナイトハンター",
		"Ruined Corrupter": "ルインコラプター",
		"Hide Stalker": "ハイドストーカー",
		"Loppy Ear": "ロップイヤー",
		"Mother Weasel": "オオイタチマザー",
		"Savage Assassin": "サベージアサシン",
		"Hex Rabbit": "ヘクスラビット",
		"Large Antler": "ラージアントラー",
		"Holy Beast of the Stars": "星の聖獣",
		"Flower Pixie": "花の精",
		"Illuminated Sylph": "イルミネイトシルフ",
		"Flower Gardener": "フラワーガーデナー",
		"Zephyr Pixie": "ゼファーピクシー",
		"Eternal Guardian": "悠久の守り手",
		"Blazing Maiden": "光熱の乙女",
		"Hallowed Spirit": "ホーリースピリット",
		"Plumed Lorelei": "プルームローレライ",
		"Elder Fairy": "エルダーフェアリー",
		"Mirage Master": "幻を司る者",
		"Lunaria Angel": "ルナリアエンゼル",
		"Nightmare Spirit": "悪夢の精",
		"Schwarzwraith": "シュヴァルツレイス",
		"Sweet Nocturnal ": "スイートノクターナル",
		"Moon Veil": "ムーンヴェイル",
		"Stone Golem": "ストーンゴーレム",
		"Rock Puppet": "ロックパペット",
		"Jewel Guard": "ジュエルガード",
		"Fairystone Puppet": "魔石の傀儡",
		"Metal Golem": "メタルゴーレム",
		"Meteorite Doll": "メテオライトドール",
		"Earth Master": "土塊の使役者",
		"Rusty Onyx": "ラスティオニキス",
		"Colossus Golem": "コロッサスゴーレム",
		"Eternal Sculpture": "不朽の彫像",
		"Boulder Soldier": "巨石の兵士",
		"Darkomaton": "ダークマタ",
		"Noir Doll": "ノワールドール",
		"Cramberry": "クラムベリー",
		"Harvest Prayer": "豊穣を祈る者",
		"Horned Sheep": "つのひつじ",
		"Ashen Wool": "アッシュウール",
		"Fluffy Sheep": "フラッフィーシープ",
		"Dreamcatcher": "ドリームキャッチャー",
		"Giant Sheep": "きょだいひつじ",
		"Mindlurker": "暗い思い出の獣",
		"Mad Beast": "マッドビースト",
		"Scaled Armadillo": "スケイルアルマジロ",
		"Intact Carapace": "インタクトカラパス",
		"Tiny Devil": "タイニーデビル",
		"Blue Fiend": "ブルーフィーンド",
		"Hot Evil": "ホットイービル",
		"Ash Demon": "アッシュデーモン",
		"King Devil": "ダイアクマ",
		"Storm Elemental ": "ストームエレメンタル",
		"Icy Crystal": "アイシークリスタル",
		"Spirit of Nature": "自然の精霊",
		"Scrambled Energy": "スクランブルエナジー",
		"Disaster Core": "ディザスターコア",
		"Earth Plant": "アースプラント",
		"Root Spreader": "ルートスプレッダー",
		"Great Tree Messenger": "大樹の使い",
		"Great Mistread": "グリームミストルード",
		"Yggdrasil": "ユグドラシル",
		"Rageness": "レイジネス",
		"Ground Builder": "グランドビルダー",
		"Ruler of the Forest": "森の支配者",
		"Spark Riser": "スパークライザー",
		"Giant Sloth": "巨大ナマケモノ",
		"Feral Crow": "フェラルクロウ",
		"Smart Ripper": "スマートリッパー",
		"Ferocious Hopper": "バッダスホッパー",
		"Fierce Hunter": "獰猛たる狩人",
		"Tyrant": "タイラント",
		"Living Armor": "動く甲冑",
		"Ghost Armor": "ゴーストアーマー",
		"Honor Guard Armor": "亡国の近衛鎧",
		"Gladiator": "グラディエーター",
		"Legendary Warrior": "伝承の古強者",
		"Immortal Knight": "イモータルナイト",
		"Royal Admiral": "ロイヤルアドミラル",
		"Heavy Warrior Armor": "戦士の大鎧",
		"Noble Paladin": "ノーブルパラディン",
		"Great Guardian": "グレートガーディアン",
		"Demonic Phantom": "幻影の幽鬼",
		"Berserker Shadow": "狂戦士の影",
		"Temple Warrior": "テンプルウォーリアー",
		"Shattered Breaker": "シャタードブレイカー",
		"Stinger": "スティンガー",
		"Sharpened Scissors": "シャープシザーズ",
		"Pile Bunker": "パイルバンカー",
		"Parching Demon": "渇きの悪魔",
		"Dark Scout": "常闇の斥候",
		"Spine Rat": "スパインラット",
		"Ogre Head": "オーガヘッド",
		"Shadow Vanguard": "影の尖兵",
		"Thrust Hedge": "スラストヘッジ",
		"Shadow Eater": "シャドウイーター",
		"Legion Needle": "レジオンニードル",
		"Mini Wyvern": "ミニワイバーン",
		"Zephyr Feather": "ウィンドフェザー",
		"Evil Orchis": "イービルオーキス",
		"Stout Drake": "ファットドレイク",
		"Mach Hawk": "マッハホーク",
		"Watcher": "ウォッチャー",
		"Draconic Lord": "ドラゴニックロード",
		"Giant Maw": "ジャイアントモー",
		"Mega Wyvern": "メガワイバーン",
		"King of Storms": "キングオブストーム",
		"Cloud Liner": "クラウドライナー",
		"Landbound Dragon": "地縛竜",
		"Cursed Wing": "呪われた翼",
		"Armored Wing": "アーマーウィング",
		"Steel Raptor": "鋼の猛禽",
		"Sprinting Bird": "スプリントバード",
		"Massive Beak": "マッシブビーク",
		"Albatross": "アルバトロス",
		"Wild Crest": "ワイルドクレスト",
		"Overwhelming Bird": "狂奔する怪鳥",
		"Twilight Songbird": "宵鳴鳥",
		"Lifeless Shadow": "亡き巨鳥の影",
		"Twilight Assassin": "宵闇の刺客",
		"Cloak-in-dagger": "クロークインダガー",
		"Shadow Assassin ": "影の暗殺者",
		"Cipher Code": "サイファーコード",
		"Hell Keeper": "地獄の番人",
		"Slashblader": "スラッシュブレイダー",
		"Crimson Arms": "クリムゾンアームズ",
		"Spellblade Wielder": "魔剣の遣い手",
		"Demon Slayer Wolf": "破邪の月狼",
		"Sleipnir": "スレイプニル",
		"Hide Shark": "ハイドシャーク",
		"Megamouth": "大顎鮫",
		"Spinal Fin": "スピネルフィン",
		"Grand Tusk": "グランタスカー",
		"Sandstorm Tyrant": "砂塵の暴君",
		"Desert Lagoon": "デザートラグーン",
		"Mind Ravager": "思念の捕食者",
		"Land Crawler": "大地を這う大魚",
		"Soul Cleaver": "ソウルクリーバー",
		"Dark General": "常闇の将軍",
		"Cluster Beetle": "クラストビートル",
		"Shadow Commander": "影の司令",
		"Horned Demon": "ホーンデーモン",
		"Rhino Fiend": "ライノフィーンド",
		"Old Castle Dragon": "古城の翼竜",
		"Dragon Lord": "天統べる覇竜",
		"Dragon of Light": "闇を裂く光竜",
		"Ravaging Queen": "常闇の女王",
		"Queen of Shadows": "影の女王",
		"Crownless Queen": "無冠の女王",
		"Floating Skeleton": "浮遊する骸",
		"Skeleton Emperor ": "スケルトンエンペラー",
		"Automaton": "オートマトン",
		"Sentry Guard": "セントリーガード",
		"Elder Treant": "エルダートレント",
		"Ancient Dragon": "エンシェントドラゴン",
		"Deranged King": "狂気の王",
		"Gatekeeper": "ゲートキーパー",
		"Code of the Universe": "万象の大典",
		"Code of the Universe - Final": "万象の大典・終章",
		"Colossus Soldier": "巨像の兵士",
		"Code of the Universe (Arm)": "万象の大典・腕",
		"Weasel Roast": "ラムロースト２号",
		"Lamb Roast": "ラムロースト３号",
		"Orig. Code of the Universe": "万象の原典",
		"Orig. Code of the Universe (Arm)": "万象の原典・腕",
	}
}