localization["kor"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "라이자의 아틀리에3 소재 배포 문의",
		"Choose a language:": "언어 선택:",
		"Choose a map:": "지도 선택:",
		"Kurken": "쿠켄 섬",
		"Mainland": "쿠켄 섬 주변지역",
		"Cleria": "클레리아 지방",
		"Nemed": "네메드 지방",
		"Orim": "이계 오림",
		"Code": "만상의 대전",
		"Rosca": "로스카 섬",
		"Rosca Control Tower": "로스카 섬 중앙 제어탑",
		"Ashra-am Baird Outskirts": "왕도 아슬라 암 버트 변경",
		"Choose an item:": "소재 선택:",
		"Filter Gathering Tool:": "선별 채집 도구:",
		"Hand Maximum Rank": "맨손채집 최대 순위",
		"None": "없음",
		"Rank One": "순위 1",
		"Rank Two": "순위 2",
		"Rank Three": "순위 3",
		"Rod Maximum Rank": "지팡이채집 최대 순위",
		"Sickle Maximum Rank": "낫채집 최대 순위",
		"Axe Maximum Rank": "도끼채집 최대 순위",
		"Hammer Maximum Rank": "망치채집 최대 순위",
		"Net Maximum Rank": "그물채집 최대 순위",
		"Alchemy Mysteries DLC": "DLC 연금술의 신비",
		"Art of Adventure DLC": "DLC 모험의 극의",
		"Search": "찾다",
		"Number found:": "결과 찾기:",
		"$1 in $2": "$1 in $2",
		"Hand Gathering": "맨손채집",
		"Rod Gathering": "지팡이채집",
		"Sickle Gathering": "낫채집",
		"Axe Gathering": "도끼채집",
		"Hammer Gathering": "망치채집",
		"Net Gathering": "그물채집",
	},
	"item": {
		"Clean Water": "깨끗한 물",
		"Goats Milk": "염소 우유",
		"Water Bamboo": "대나무 물통",
		"Plant Essence": "식물 농축액",
		"Roteswasser Tonic": "로테스바서 광수",
		"Rapwar Water": "라프와르 물",
		"Foamy Water": "부글거리는 물",
		"Jade Water": "비취의 황수",
		"Ancient Blue Water": "태고의 창수",
		"Curious Aqua": "큐리어스 아쿠아",
		"Black Water": "검은 물",
		"Nameless Grass": "이름 없는 풀",
		"Wasser Wheat": "바서 보리",
		"Dry Grass": "마른풀",
		"Hill Lettuce": "언덕 양상추",
		"Blue Herb": "블루 허브",
		"Rishikelp": "리시리코",
		"Chomping Grass": "덥석초",
		"Sweet Leaf": "스위트 리프",
		"Ancient Branch": "고대수의 가지",
		"Campanula": "초롱꽃",
		"Glowing Diatom": "광규조",
		"Lucky Clover": "행운의 클로버",
		"Blue Clover": "푸른 토끼풀",
		"Light Absorbing Grass": "흡광초",
		"Rosen Leaf": "로젠 리프",
		"Uni": "성게",
		"Ancient Uni": "고대 성게",
		"Water Uni": "물 성게",
		"Charcoal Uni": "숯 성게",
		"Gold Uni": "황금 성게",
		"Demon Uni": "도깨비가시 성게",
		"Emperor Uni": "대왕 성게",
		"Health Flower": "병망화",
		"Northern Wind Flower": "북풍화",
		"Sunny Honey Flower": "양기의 밀화",
		"Bubble Grass": "방울초",
		"Stained Flower": "스테인드 플라워",
		"Caged Flower": "감옥의 요화",
		"Spring Princess": "청수의 백희",
		"Soul Flower": "산화의 꽃",
		"Rose Crystal": "로즈 크리스털",
		"Delphi Rose": "델포이 로즈",
		"Polar Cactus": "극지 선인장",
		"Timeteller": "시간알리미",
		"Taun": "톤",
		"Tall Taun": "거대 톤",
		"Sapling Branch": "어린 가지 잎",
		"Medicinal Moss": "의약용 이끼",
		"Fertile Soil": "비옥한 흙",
		"Dry Incense": "건조향",
		"Bitter Root": "씁쓸한 뿌리",
		"Crimson Grass": "홍초",
		"Earth's Secret Oils": "대지의 비유",
		"Sage Grass": "선인초",
		"Life Leaf": "생명의 잎",
		"Refueling Extract": "리퓨르 농축액",
		"Yugdore Water": "유그돌 용수",
		"Stinky Trash": "음식물 쓰레기",
		"Mushroom Powder": "버섯 파우더",
		"Mispel Seed": "미스펠 씨앗",
		"Resentful Scream": "원망의 외침",
		"Blessing of Delusion": "허망의 축복",
		"Dragon Flower": "용장란",
		"Demon Blood": "데몬 블러드",
		"Forest Sage": "숲의 현자",
		"Celestial Tears": "천궁의 눈물",
		"Solflower": "태양의 꽃",
		"Dunkelheit": "던켈하이트",
		"Soft Sand": "부드러운 모래",
		"Burning Sand": "가연성 모래",
		"Corail Saber": "코라이유서블",
		"Polluted Humus": "오염된 부엽토",
		"Emerald Glass": "에메랄드 풀",
		"Seafloor Soil": "수저의 흙",
		"Black Muck": "검은 진흙",
		"Vortex Sand": "소용돌이 모래",
		"Glittering Sand": "글리터 샌드",
		"Eroded Stone": "풍화된 석재",
		"Nectar Rock": "감로 바위",
		"Nepheline": "네펠라이트",
		"Waterside Moss Stone": "물가의 이끼돌",
		"Ethereal Stone": "백령암",
		"Ancient Pillar": "고대의 석주",
		"Coral Stone": "산호석",
		"Breeze Stone": "브리즈 스톤",
		"Riverstone": "리버 스톤",
		"Blue Flame Riverstone": "리버 스톤 창염",
		"Hot Saltpeter": "열초석",
		"Arknite": "아크나이트",
		"Crimson Ore": "적열광",
		"Aqua Ore": "아쿠아광",
		"Lightning Ore": "번개광",
		"Wind Ore": "빈트광",
		"Amatite Ore": "아마타이트광",
		"Luminous Rock": "야광암",
		"Pentanite": "펜트나이트",
		"Mordenite": "몰디나이트",
		"Goldinite": "골디나이트",
		"Degenesis Stone": "창생의 역석",
		"Septrin": "셉트리엔",
		"Adamant": "아다만트",
		"Eternal Crystal": "영원결정",
		"Small Crystals": "조그마한 결정",
		"Unknown Gemstone": "정체불명의 원석",
		"Glowing Coral": "빛나는 산호",
		"White Shell Pearl": "대왕조개의 진주",
		"Black Shell Pearl": "대왕조개의 흑진주",
		"Amber Fragment": "호박 파편",
		"Amber Crystal": "호박 수정",
		"Three-Colored Stone": "삼색혼석",
		"Clear Branch": "클리어 브랜치",
		"Holy Arbor Crystal": "성수 결정",
		"Underworld Crystal": "이계 결정",
		"Black Glitter Stone": "흑황석",
		"Rainbow Gemstone": "칠황 원석",
		"Dried Lumber": "마른 톱밥",
		"Flint Pepper": "플린트 페퍼",
		"Explosive Vine": "작렬 덩굴풀",
		"Flaming Black Sand": "불꽃의 검은 모래",
		"Magma Powder": "마그마 파우더",
		"Scrap Paper": "종잇조각",
		"Flammable Bark": "가연성 나무껍질",
		"Palma Bark": "팔마 나무껍질",
		"Fuel Coconut": "퓨얼 코코넛",
		"Natural Oil": "천연기름",
		"Amber Oil": "호박유",
		"Fire and Ice Crystal": "염빙결정",
		"Eternal Fire": "영세의 불꽃",
		"Beast Meat": "짐승 고기",
		"Fresh Meat": "신선한 고기",
		"Some Kind of Egg": "무언가의 알",
		"Oil Tree Fruit": "오일 나무 열매",
		"Nectar Fruit": "감로의 열매",
		"Wild Potato": "야생감자",
		"Portpea": "포르트콩",
		"Red Devil": "붉은 악마",
		"Clenoko": "쿠레노코",
		"Red King Apple": "왕사과",
		"Skull Pumpkin": "스컬 펌프킨",
		"Venom Nut": "베놈 너트",
		"Palma Fruit": "팔마의 열매",
		"Fresh Berry": "프레스 베리",
		"Werder Nut": "베르다 너트",
		"Kurken Fruit": "쿠켄 프루트",
		"Fortune Fruit": "포춘 프루트",
		"Rainbow Grapevine": "무지갯빛 포도",
		"Summer Gem": "서머 젬",
		"Softtail": "소프테일",
		"Beehive": "벌집",
		"Silver Beehive": "백은 벌집",
		"Gold Beehive": "황금 벌집",
		"Bee Haven": "비 하이븐",
		"Honey Ball": "허니볼",
		"Eicheloa": "아이페 로아",
		"Mushroom Colony": "군체 버섯",
		"Brodenbits": "브로든 비츠",
		"Utopiechampignon": "유피토니언",
		"Jellyfish Mushroom": "해파리 버섯",
		"Stool of Nature": "걸상 버섯",
		"Dusk Mushroom": "밤의 귀부인",
		"Danger Mushroom": "극위험 버섯",
		"Jewel Mushroom": "결정 버섯",
		"Golden Crown": "골든 크라운",
		"Sardine": "정어리",
		"Seriole": "방어",
		"Pourpremoule": "풀무르",
		"Crab": "슈랍",
		"Pretty Shells": "예쁜 조개껍질",
		"Spikey": "가시돔",
		"Uni Starfish": "성게 불가사리",
		"Chestnut": "밤",
		"Rainbow Fish": "무지갯빛 생선",
		"Mace Fish": "메이스 피시",
		"Stingray": "스팅 레이",
		"Myria Fish": "만년어",
		"Lake Master": "호수의 지배자",
		"Dragonpalace Nautilus": "용궁 앵무조개",
		"Crown Shellfish": "왕관 소라",
		"Imperial Fish": "황어",
		"Seven Stars": "칠성무당벌레",
		"Honey Ant": "꿀단지개미",
		"Narwhal Grasshopper": "외뿔 메뚜기",
		"Lantern Fly": "등롱 반딧불",
		"Rose Bee": "로즈 비",
		"Giant Beetle": "왕투구풍뎅이",
		"Baby Wyrm": "베이비 블룸",
		"Crimson Cloak": "크림슨 사마귀",
		"Spirit Isopod": "스피릿 모르그",
		"Amber Fly": "앰버 플라이",
		"Lapis Papillion": "라피스 파피용",
		"Trihorn": "트라이혼",
		"Ancient Bug": "왕고충",
		"Rock Schloss": "바위게",
		"Restraint Silk": "속박의 강실",
		"Cotton Grass": "솜털풀",
		"Tough Vine": "튼튼한 덩굴",
		"Arbor Ivy": "거목 담쟁이덩굴",
		"Queen Spider Web": "여왕거미의 집",
		"Hug of Arachne": "아라크네의 포옹",
		"Eiche": "아이페",
		"Tough Log": "튼튼한 통나무",
		"Mossy Driftwood": "이끼 낀 유목",
		"Holy Arbor Branch": "성수의 큰 가지",
		"Palma": "팔마",
		"Fossil Tree": "화석나무",
		"Miasma Log": "맹독 나무",
		"Lightning Tree": "축전 나무",
		"Ancient Log": "태고의 고목",
		"Millennial Tree": "천년수의 유목",
		"Wing Plant": "윙 플랜트",
		"Smoke Signal Flower": "봉화초",
		"Crispy Mushroom": "바삭바삭한 버섯",
		"Sky Bubble": "스카이 버블",
		"Rotwood Miasma": "부목의 독무",
		"Water Holy Branch": "수성수의 가지",
		"Dragon Breath": "화룡의 숨결",
		"Fairystone Fragment": "마석 파편",
		"Dark Crystal Fragment": "암수정 파편",
		"Holy Stone Fragment": "성석 파편",
		"Rainbow Wing Fragment": "홍익의 파편",
		"Magic Tome Piece": "마도서 조각",
		"Old Magic Tome": "낡은 마도서",
		"Holy Tree Leaf": "성수의 잎",
		"Mystic Sphere": "플로트 스피어",
		"Ancient Fossil": "고대생물의 화석",
		"Forever Ice Block": "영구빙괴",
		"Decayed Iron Pieces": "썩은 쇳조각",
		"Rusted Sword": "녹슨 검",
		"Broken Tools": "망가진 도구",
		"Liquid Metal": "액체금속",
		"Ancient Sword": "낡은 투검",
		"Blue Puniball": "푸니푸니 구슬 청",
		"Green Puniball": "푸니푸니 구슬 녹",
		"Red Puniball": "푸니푸니 구슬 적",
		"Black Puniball": "푸니푸니 구슬 흑",
		"Silver Puniball": "푸니푸니 구슬 은",
		"Gold Puniball": "푸니푸니 구슬 금",
		"Animal Hide": "동물 모피",
		"Mythical Hide": "환수 모피",
		"Large Bone": "커다란 뼈",
		"Beast Fossil": "거대 짐승의 화석",
		"Water Beast Fossil": "물짐승의 거대화석",
		"Water Beast Scale": "물짐승의 비늘",
		"Cave Bat Wing": "동굴박쥐의 날개",
		"White Swallow's Nest": "흰 제비의 둥지",
		"Beast Fin": "마수의 등지느러미",
		"Beast Shell": "마수의 갑각",
		"Beast Scales": "마수의 비늘",
		"Giant Bird Feather": "거대새의 풍절우",
		"Giant Bird Egg": "거대새의 대란",
		"Goat Horn": "염소 뿔",
		"Demon Claws": "마조",
		"Fluffy Wool": "푹신푹신한 울",
		"Poison Needle": "가느다란 독침",
		"Dragon Wing": "익룡의 날개",
		"Dragon Egg": "익룡의 알",
		"Dragon Eye": "용의 눈",
		"Dragon Bone": "용골",
		"Dragon Meat": "용 고기",
		"Guardian Armor": "수호자의 견갑",
		"Heroic Spirit": "영령의 혼",
		"Giant Puniball": "왕 푸니 구슬",
		"Fairy Horn Adornment": "요정의 대각장식",
		"Giant Claws": "거대한 발톱",
		"Golem Core": "골렘 코어",
		"Inverted Scale": "역린",
		"Ether Core": "에텔 코어",
		"Imp's Lost Item": "소악마의 분실물",
		"Elemental Force": "엘리먼트 포스",
		"Twisted Thorns": "덩굴 뿌리",
		"Curved Long Nails": "길게 굽은 발톱",
		"Running Beast Crest": "들짐승의 볏",
		"Phantom Color Tail": "환색 꼬리",
		"Wolf Beast's Blade": "늑대의 사냥칼",
		"Duet Stock Solution": "두엣 원액",
		"Scintilla Ore": "신티라 광석",
		"Lujada's Fairystone": "루지아다 마석",
		"Pink Puniball": "푸니푸니 구슬 앵",
		"Giant Kurken Fruit": "거대 쿠켄 프루트",
		"Cow Milk": "우유",
		"Giant Claws": "거대한 발톱",
		"White Swallow's Nest": "흰 제비의 둥지",
		"Water Beast Scale": "물짐승의 비늘",
		"Mythical Hide": "환수 모피",
		"Dragon Meat": "용 고기",
		"Heroic Spirit": "영령의 혼",
		"Dragon Wing": "익룡의 날개",
		"Demon Claws": "마조",
		"Dragon Bone": "용골",
		"Dragon Eye": "용의 눈",
		"Ether Core": "에텔 코어",
		"Myria Fish": "만년어",
		"Summer Gem": "서머 젬",
		"Spring Princess": "청수의 백희",
		"Giant Beetle": "왕투구풍뎅이",
		"Corail Saber": "코라이유서블",
		"Celestial Tears": "천궁의 눈물",
		"Sky Bubble": "스카이 버블",
		"Rainbow Fish": "무지갯빛 생선",
		"Red Devil": "붉은 악마",
		"Chomping Grass": "덥석초",
		"Solflower": "태양의 꽃",
		"Dark Crystal Fragment": "암수정 파편",
		"Campanula": "초롱꽃",
		"Earth's Secret Oils": "대지의 비유",
		"Softtail": "소프테일",
		"Dunkelheit": "던켈하이트",
		"Emperor Uni": "대왕 성게",
		"Light Absorbing Grass": "흡광초",
		"Black Muck": "검은 진흙",
		"Fire and Ice Crystal": "염빙결정",
		"Seal Branch": "실 그레인",
		"Old Dragon's Claw": "고룡의 발톱",
		"Water Stone": "수환석",
		"Silence Steel": "사일레스틸",
		"Verdant Moonflower": "심록빛의 월화",
		"Heavenly Seawater": "천해수",
		"Clearfish": "육화어",
		"Pine Fruit": "봉리 열매",
		"Melocotone": "멜로코톤",
		"Star Clam": "별 조개",
		"Gemeater": "젬 이터",
		"Tsurugi Mushroom": "검 버섯",
		"Floating Petal Stone": "부상 화석",
		"Verdeum Metal": "베르데움 금속",
		"Wool Flower": "풍매화",
		"Cleaner Plant": "랄코초",
		"Medicinal Sap": "약수액",
		"Immortal Sapling": "불후의 산목",
		"Blessed Clouds": "은혜로운 뭉게구름",
		"Carved Relic": "목제 유물",
		"Reaper's Scythe": "사신의 대낫",
		"Heavenly Rain Thread": "단비의 실",
		"Unstable Lump": "불안정한 덩어리",
		"Ignis Nut": "이그니스 너트",
		"Ancient Scroll": "고풍스러운 스크롤",
		"Torch of the Ages": "천고의 등불",
		"Royal Spun Thread": "왕가의 방사",
		"White Sand of Eternity": "영원한 흰모래",
		"Traveling Grass": "여행하는 마른풀",
		"White Sand Metal": "흰모래 금속",
		"Ametrite": "아메트라이트",
		"Forgotten Pottery": "유실된 도기",
		"Desert Cleaner": "사막의 청소부",
		"Trifruit": "트라이 프루트",
		"Cactus Blossom": "사보탄",
		"Mortal Anima": "모탈 아니마",
		"Shark Bone": "티브로 본",
		"Exotic Meat": "맛깔나는 고기",
		"Kala's Translated Texts (Copy)": "칼라의 번역집 사본",
		"Golden Puniball": "푸니푸니 구슬 황금",
		"Sandstorm Crystal": "모래 폭풍의 결정",
		"White Moon's Soul": "백월의 혼",
		"Universe Sphere": "유니버스피어",
		"Fairywood": "페어리 바움",
		"Mini Volcano": "리텐 보르케",
		"Seven-Color Pansy": "무지갯빛 비올라",
		"Fairy Sapling": "요정의 묘목",
		"Lava Rock": "라바로크",
		"Moon Fragment": "달의 프래그먼트",
	},
	"monster": {
		"Blue Puni": "파랑 푸니",
		"Green Puni": "초록 푸니",
		"Red Puni": "빨강 푸니",
		"Flower Puni": "꽃 푸니",
		"Black Puni": "블랙 푸니",
		"Silver Puni": "실버 푸니",
		"Gold Puni": "골드 푸니",
		"Lavender Puni": "라벤더 푸니",
		"Big Puni": "거대 푸니",
		"Shining Puni": "샤이닝 푸니",
		"Rafflesia Puni": "라플레시아 푸니",
		"Darkness Puni": "다크니스 푸니",
		"Precious Puni": "프레셔스 푸니",
		"Giant Weasel": "왕족제비",
		"Bluefin": "블루핀",
		"Silky Fur": "실키 퍼",
		"Scarf Bunny": "스카프 버니",
		"Night Hunter": "나이트 헌터",
		"Ruined Corrupter": "루인 커럽터",
		"Hide Stalker": "하이드 스토커",
		"Loppy Ear": "롭 이어",
		"Mother Weasel": "어미 왕족제비",
		"Savage Assassin": "새비지 어쌔신",
		"Hex Rabbit": "헥스 래빗",
		"Large Antler": "라지 앤틀러",
		"Holy Beast of the Stars": "별의 성수",
		"Flower Pixie": "꽃의 요정",
		"Illuminated Sylph": "일루미네이트 실프",
		"Flower Gardener": "플라워 가드너",
		"Zephyr Pixie": "제퍼 픽시",
		"Eternal Guardian": "유구의 수호자",
		"Blazing Maiden": "광열의 소녀",
		"Hallowed Spirit": "홀리 스피릿",
		"Plumed Lorelei": "플룸 로렐라이",
		"Elder Fairy": "엘더 페어리",
		"Mirage Master": "환영의 지배자",
		"Lunaria Angel": "루나리아 엔젤",
		"Nightmare Spirit": "악몽의 정령",
		"Schwarzwraith": "슈바르츠 레이스",
		"Sweet Nocturnal ": "스위트 녹터널",
		"Moon Veil": "문 베일",
		"Stone Golem": "스톤 골렘",
		"Rock Puppet": "록 퍼핏",
		"Jewel Guard": "쥬얼 가드",
		"Fairystone Puppet": "마석의 괴뢰",
		"Metal Golem": "메탈 골렘",
		"Meteorite Doll": "메테오라이트 돌",
		"Earth Master": "토괴의 사역자",
		"Rusty Onyx": "러스티 오닉스",
		"Colossus Golem": "콜로서스 골렘",
		"Eternal Sculpture": "불후의 조각상",
		"Boulder Soldier": "거석 병사",
		"Darkomaton": "다크마타",
		"Noir Doll": "느와 돌",
		"Cramberry": "크랜베리",
		"Harvest Prayer": "풍작을 바라는 자",
		"Horned Sheep": "뿔 양",
		"Ashen Wool": "애쉬 울",
		"Fluffy Sheep": "플러피 십",
		"Dreamcatcher": "드림 캐처",
		"Giant Sheep": "거대 양",
		"Mindlurker": "어두운 추억의 짐승",
		"Mad Beast": "광기에 물든 짐승",
		"Scaled Armadillo": "스케일 아르마딜로",
		"Intact Carapace": "인택트 캐러페이스",
		"Tiny Devil": "타이니 데빌",
		"Blue Fiend": "블루 핀드",
		"Hot Evil": "핫 이빌",
		"Ash Demon": "애시 데몬",
		"King Devil": "대악마",
		"Storm Elemental ": "스톰 엘리먼트",
		"Icy Crystal": "아이시 크리스털",
		"Spirit of Nature": "자연의 정령",
		"Scrambled Energy": "스크램블 에너지",
		"Disaster Core": "디재스터 코어",
		"Earth Plant": "어스 플랜트",
		"Root Spreader": "루트 스프레더",
		"Great Tree Messenger": "거목의 사자",
		"Great Mistread": "그림 미스트루드",
		"Yggdrasil": "위그드라실",
		"Rageness": "레이지니스",
		"Ground Builder": "그랜드 빌더",
		"Ruler of the Forest": "숲의 지배자",
		"Spark Riser": "슈퍼 크라이저",
		"Giant Sloth": "거대 나무늘보",
		"Feral Crow": "페럴 크로우",
		"Smart Ripper": "스마트 리퍼",
		"Ferocious Hopper": "배드애스 호퍼",
		"Fierce Hunter": "영악한 사냥꾼",
		"Tyrant": "타이런트",
		"Living Armor": "움직이는 갑주",
		"Ghost Armor": "고스트 아머",
		"Honor Guard Armor": "망국의 근위갑옷",
		"Gladiator": "글래디에이터",
		"Legendary Warrior": "전승의 전사",
		"Immortal Knight": "불멸의 나이트",
		"Royal Admiral": "로열 애드미럴",
		"Heavy Warrior Armor": "전사의 대갑옷",
		"Noble Paladin": "노블 팔라딘",
		"Great Guardian": "그레이트 가디언",
		"Demonic Phantom": "허상의 망령",
		"Berserker Shadow": "광전사의 그림자",
		"Temple Warrior": "템플 워리어",
		"Shattered Breaker": "셰터드 브레이커",
		"Stinger": "스팅거",
		"Sharpened Scissors": "샤프 시저스",
		"Pile Bunker": "파일 벙커",
		"Parching Demon": "굶주린 악마",
		"Dark Scout": "암흑의 척후",
		"Spine Rat": "스파인 래트",
		"Ogre Head": "오거 헤드",
		"Shadow Vanguard": "그림자 첨병",
		"Thrust Hedge": "스러스트 헤지",
		"Shadow Eater": "섀도우 이터",
		"Legion Needle": "리전 니들",
		"Mini Wyvern": "미니 와이번",
		"Zephyr Feather": "윈드 페더",
		"Evil Orchis": "이블 오키스",
		"Stout Drake": "팻 드레이크",
		"Mach Hawk": "마하 호크",
		"Watcher": "워처",
		"Draconic Lord": "드래고닉 로드",
		"Giant Maw": "자이언트 모",
		"Mega Wyvern": "메가 와이번",
		"King of Storms": "킹 오브 스톰",
		"Cloud Liner": "클라우드 라이너",
		"Landbound Dragon": "지박룡",
		"Cursed Wing": "저주받은 날개",
		"Armored Wing": "아머 윙",
		"Steel Raptor": "강철 맹금",
		"Sprinting Bird": "스프린트 버드",
		"Massive Beak": "매시브 비크",
		"Albatross": "알바트로스",
		"Wild Crest": "와일드 크레스트",
		"Overwhelming Bird": "광분하는 괴조",
		"Twilight Songbird": "소명조",
		"Lifeless Shadow": "죽은 새의 그림자",
		"Twilight Assassin": "황혼의 자객",
		"Cloak-in-dagger": "클록 인 더거",
		"Shadow Assassin ": "그림자 암살자",
		"Cipher Code": "사이퍼 코드",
		"Hell Keeper": "지옥의 파수꾼",
		"Slashblader": "슬래시 블레이더",
		"Crimson Arms": "크림슨 암스",
		"Spellblade Wielder": "마검의 사자",
		"Demon Slayer Wolf": "파사의 월랑",
		"Sleipnir": "슬레이프니르",
		"Hide Shark": "하이드 샤크",
		"Megamouth": "대악교",
		"Spinal Fin": "스피넬 핀",
		"Grand Tusk": "그랜 터스커",
		"Sandstorm Tyrant": "모래의 폭군",
		"Desert Lagoon": "데저트 라군",
		"Mind Ravager": "사념 포식자",
		"Land Crawler": "대지를 기는 생선",
		"Soul Cleaver": "소울 클리버",
		"Dark General": "어둠의 장군",
		"Cluster Beetle": "클러스트 비틀",
		"Shadow Commander": "그림자 사령",
		"Horned Demon": "혼 데몬",
		"Rhino Fiend": "라이노 핀드",
		"Old Castle Dragon": "고성의 익룡",
		"Dragon Lord": "하늘의 지배자",
		"Dragon of Light": "어둠을 가르는 광룡",
		"Ravaging Queen": "침식의 여왕",
		"Queen of Shadows": "그림자 여왕",
		"Crownless Queen": "무관의 여왕",
		"Floating Skeleton": "부유하는 뼈",
		"Skeleton Emperor ": "황제 스켈레톤",
		"Automaton": "오토마톤",
		"Sentry Guard": "센트리 가드",
		"Elder Treant": "엘더 트렌트",
		"Ancient Dragon": "에인션트 드래곤",
		"Deranged King": "광기의 왕",
		"Gatekeeper": "게이트 키퍼",
		"Code of the Universe": "만상의 대전",
		"Code of the Universe - Final": "만상의 대전ㆍ종장",
		"Colossus Soldier": "거상의 병사",
		"Code of the Universe (Arm)": "만상의 대전ㆍ팔",
		"Weasel Roast": "램 로스트 2호",
		"Lamb Roast": "램 로스트 3호",
		"Orig. Code of the Universe": "만상의 원전",
		"Orig. Code of the Universe (Arm)": "만상의 원전ㆍ팔",
	}
}