localization["cht"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "萊莎的鍊金工房3 素材分布查詢",
		"Choose a language:": "選擇語言：",
		"Choose a map:": "選擇地圖：",
		"Kurken": "庫肯島",
		"Mainland": "庫肯島周邊地區",
		"Cleria": "克萊莉亞地區",
		"Nemed": "內米德地區",
		"Orim": "異界奧靈",
		"Code": "萬象大典",
		"Rosca": "羅斯卡島",
		"Rosca Control Tower": "羅斯卡島中央控制塔",
		"Ashra-am Baird Outskirts": "王都阿斯拉‧阿姆‧伯特邊境",
		"Choose an item:": "選擇道具：",
		"Filter Gathering Tool:": "篩選採集工具：",
		"Hand Maximum Rank": "空手等級",
		"None": "無",
		"Rank One": "等級1",
		"Rank Two": "等級2",
		"Rank Three": "等級3",
		"Rod Maximum Rank": "手杖等級",
		"Sickle Maximum Rank": "鐮刀等級",
		"Axe Maximum Rank": "斧頭等級",
		"Hammer Maximum Rank": "錘子等級",
		"Net Maximum Rank": "捕捉網等級",
		"Alchemy Mysteries DLC": "DLC 鍊金術之神秘",
		"Art of Adventure DLC": "DLC 冒險之精髓",
		"Search": "搜尋",
		"Number found:": "尋找結果：",
		"$1 in $2": "$2有 $1 處",
		"Hand Gathering": "空手採集",
		"Rod Gathering": "手杖採集",
		"Sickle Gathering": "鐮刀採集",
		"Axe Gathering": "斧頭採集",
		"Hammer Gathering": "錘子採集",
		"Net Gathering": "捕捉網採集",
	},
	"item": {
		"Clean Water": "乾淨的水",
		"Goats Milk": "山羊奶",
		"Water Bamboo": "儲水竹",
		"Plant Essence": "植物精華",
		"Roteswasser Tonic": "羅德士瓦瑟礦水",
		"Rapwar Water": "梨花水",
		"Foamy Water": "起泡水",
		"Jade Water": "翡翠煌水",
		"Ancient Blue Water": "太古蒼水",
		"Curious Aqua": "神秘液體",
		"Black Water": "黑水",
		"Nameless Grass": "無名草",
		"Wasser Wheat": "瓦塞麥",
		"Dry Grass": "焦草",
		"Hill Lettuce": "丘陵萵苣",
		"Blue Herb": "藍色香草",
		"Rishikelp": "利西利藻",
		"Chomping Grass": "咬人草",
		"Sweet Leaf": "甜葉",
		"Ancient Branch": "古樹枝",
		"Campanula": "吊鐘草",
		"Glowing Diatom": "光矽藻",
		"Lucky Clover": "幸運四葉草",
		"Blue Clover": "藍詰草",
		"Light Absorbing Grass": "吸光草",
		"Rosen Leaf": "玫瑰葉",
		"Uni": "海膽",
		"Ancient Uni": "古代海膽",
		"Water Uni": "水海膽",
		"Charcoal Uni": "炭海膽",
		"Gold Uni": "黃金海膽",
		"Demon Uni": "鬼角海膽",
		"Emperor Uni": "大王海膽",
		"Health Flower": "忘憂花",
		"Northern Wind Flower": "北風之花",
		"Sunny Honey Flower": "陽氣蜜花",
		"Bubble Grass": "肥皂草",
		"Stained Flower": "彩光之花",
		"Caged Flower": "樹籠妖花",
		"Spring Princess": "清水白姫",
		"Soul Flower": "散命花",
		"Rose Crystal": "玫瑰水晶",
		"Delphi Rose": "德爾福玫瑰",
		"Polar Cactus": "極地仙人掌",
		"Timeteller": "報時花",
		"Taun": "通草",
		"Tall Taun": "長頸通草",
		"Sapling Branch": "幼樹枝葉",
		"Medicinal Moss": "藥苔",
		"Fertile Soil": "肥沃土壤",
		"Dry Incense": "乾燥香",
		"Bitter Root": "苦根",
		"Crimson Grass": "紅草",
		"Earth's Secret Oils": "大地秘油",
		"Sage Grass": "仙人草",
		"Life Leaf": "生命葉片",
		"Refueling Extract": "補給精華",
		"Yugdore Water": "優古多爾的湧水",
		"Stinky Trash": "廚餘",
		"Mushroom Powder": "蘑菇孢子",
		"Mispel Seed": "歐楂種子",
		"Resentful Scream": "怨嗟悲鳴",
		"Blessing of Delusion": "虛妄祝福",
		"Dragon Flower": "龍葬蘭",
		"Demon Blood": "惡魔之血",
		"Forest Sage": "森林智草",
		"Celestial Tears": "天宮之淚",
		"Solflower": "太陽花",
		"Dunkelheit": "一夜花",
		"Soft Sand": "軟砂",
		"Burning Sand": "可燃之砂",
		"Corail Saber": "珊瑚砂",
		"Polluted Humus": "受污染的腐葉土",
		"Emerald Glass": "翡翠玻璃",
		"Seafloor Soil": "水底土",
		"Black Muck": "黑泥",
		"Vortex Sand": "漩渦流砂",
		"Glittering Sand": "閃耀砂粒",
		"Eroded Stone": "風化石材",
		"Nectar Rock": "甘露岩",
		"Nepheline": "霞石",
		"Waterside Moss Stone": "水邊苔石",
		"Ethereal Stone": "白靈岩",
		"Ancient Pillar": "古代石柱",
		"Coral Stone": "珊瑚石",
		"Breeze Stone": "微風石",
		"Riverstone": "河石",
		"Blue Flame Riverstone": "河石‧蒼炎",
		"Hot Saltpeter": "熱硝石",
		"Arknite": "方舟夜石",
		"Crimson Ore": "赤熱礦",
		"Aqua Ore": "海藍石礦",
		"Lightning Ore": "閃電礦",
		"Wind Ore": "風礦",
		"Amatite Ore": "赤鐵礦",
		"Luminous Rock": "夜光岩",
		"Pentanite": "派恩特夜石",
		"Mordenite": "毛爾迪夜石",
		"Goldinite": "戈爾迪夜石",
		"Degenesis Stone": "創生逆石",
		"Septrin": "聖石",
		"Adamant": "金剛石",
		"Eternal Crystal": "永恆結晶",
		"Small Crystals": "小晶石",
		"Unknown Gemstone": "未知的原石",
		"Glowing Coral": "發光珊瑚",
		"White Shell Pearl": "大貝白珍珠",
		"Black Shell Pearl": "大貝黑珍珠",
		"Amber Fragment": "琥珀碎片",
		"Amber Crystal": "琥珀水晶",
		"Three-Colored Stone": "三色石",
		"Clear Branch": "清瑩樹枝",
		"Holy Arbor Crystal": "聖樹結晶",
		"Underworld Crystal": "異界結晶",
		"Black Glitter Stone": "黑煌石",
		"Rainbow Gemstone": "七煌原石",
		"Dried Lumber": "乾燥木屑",
		"Flint Pepper": "燧石胡椒",
		"Explosive Vine": "炸裂藤",
		"Flaming Black Sand": "焰之黑砂",
		"Magma Powder": "岩漿粉",
		"Scrap Paper": "紙屑",
		"Flammable Bark": "易燃樹皮",
		"Palma Bark": "帕爾馬樹皮",
		"Fuel Coconut": "燃料椰子",
		"Natural Oil": "天然油",
		"Amber Oil": "琥珀油",
		"Fire and Ice Crystal": "炎冰結晶",
		"Eternal Fire": "永世之焰",
		"Beast Meat": "獸肉",
		"Fresh Meat": "新鮮的肉",
		"Some Kind of Egg": "未知的蛋",
		"Oil Tree Fruit": "油木果實",
		"Nectar Fruit": "甘露果實",
		"Wild Potato": "野生馬鈴薯",
		"Portpea": "波多豆",
		"Red Devil": "紅惡魔",
		"Clenoko": "餘暉筍",
		"Red King Apple": "王玉蘋果",
		"Skull Pumpkin": "顱骨南瓜",
		"Venom Nut": "猛毒果",
		"Palma Fruit": "帕爾馬果實",
		"Fresh Berry": "莓果",
		"Werder Nut": "森林核果",
		"Kurken Fruit": "庫肯果",
		"Fortune Fruit": "幸運果實",
		"Rainbow Grapevine": "七色葡萄",
		"Summer Gem": "夏季寶石",
		"Softtail": "柔軟奶油果",
		"Beehive": "蜂巢",
		"Silver Beehive": "銀色蜂巢",
		"Gold Beehive": "金色蜂巢",
		"Bee Haven": "疊層蜂蜜塊",
		"Honey Ball": "蜜蜂球巢",
		"Eicheloa": "橡樹菇",
		"Mushroom Colony": "群生蘑菇",
		"Brodenbits": "布羅登皮特菇",
		"Utopiechampignon": "尤皮特齒菇",
		"Jellyfish Mushroom": "水母菇",
		"Stool of Nature": "椅菇",
		"Dusk Mushroom": "暗夜貴婦人",
		"Danger Mushroom": "極其危險菇",
		"Jewel Mushroom": "寶晶塞歐伊菇",
		"Golden Crown": "金色王冠",
		"Sardine": "沙丁魚",
		"Seriole": "黃尾魚",
		"Pourpremoule": "普魯姆魯螺",
		"Crab": "灌木蟹",
		"Pretty Shells": "美麗貝殼",
		"Spikey": "刺刺魚",
		"Uni Starfish": "海膽海星",
		"Chestnut": "栗子",
		"Rainbow Fish": "彩虹魚",
		"Mace Fish": "釘錘魚",
		"Stingray": "汙濁魟魚",
		"Myria Fish": "萬年魚",
		"Lake Master": "湖底之主",
		"Dragonpalace Nautilus": "龍宮鸚鵡螺",
		"Crown Shellfish": "王冠海螺",
		"Imperial Fish": "皇魚",
		"Seven Stars": "七星蟲",
		"Honey Ant": "蜜蟻",
		"Narwhal Grasshopper": "獨角蚱蜢",
		"Lantern Fly": "燈籠螢火蟲",
		"Rose Bee": "玫瑰蜂",
		"Giant Beetle": "甲蟲",
		"Baby Wyrm": "幼虹蟲",
		"Crimson Cloak": "緋紅斗篷",
		"Spirit Isopod": "靈團蟲",
		"Amber Fly": "琥珀飛蟲",
		"Lapis Papillion": "娜匹斯蝶",
		"Trihorn": "三角甲蟲",
		"Ancient Bug": "王古蟲",
		"Rock Schloss": "岩城蟹",
		"Restraint Silk": "鋼化蛛絲",
		"Cotton Grass": "綿毛草",
		"Tough Vine": "強韌藤蔓",
		"Arbor Ivy": "大樹常春藤",
		"Queen Spider Web": "女王蜘蛛網",
		"Hug of Arachne": "阿拉克妮的擁抱",
		"Eiche": "橡木",
		"Tough Log": "結實的圓木",
		"Mossy Driftwood": "長苔蘚的漂流木",
		"Holy Arbor Branch": "聖樹大枝",
		"Palma": "帕爾馬木",
		"Fossil Tree": "化石樹",
		"Miasma Log": "釋放瘴氣的倒木",
		"Lightning Tree": "蓄雷樹",
		"Ancient Log": "太古老柴",
		"Millennial Tree": "千年樹幼樹",
		"Wing Plant": "翼葉草",
		"Smoke Signal Flower": "狼煙草",
		"Crispy Mushroom": "焦菇",
		"Sky Bubble": "天空泡沫",
		"Rotwood Miasma": "朽木毒霧",
		"Water Holy Branch": "水聖樹樹枝",
		"Dragon Breath": "火龍吐息",
		"Fairystone Fragment": "魔石碎片",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Holy Stone Fragment": "聖石碎片",
		"Rainbow Wing Fragment": "虹翼碎片",
		"Magic Tome Piece": "魔導書殘頁",
		"Old Magic Tome": "陳舊的魔導書",
		"Holy Tree Leaf": "聖樹葉",
		"Mystic Sphere": "漂浮球體",
		"Ancient Fossil": "古代生物化石",
		"Forever Ice Block": "永恆冰塊",
		"Decayed Iron Pieces": "鏽蝕鐵片",
		"Rusted Sword": "生鏽的劍",
		"Broken Tools": "壞掉的道具",
		"Liquid Metal": "液態金屬",
		"Ancient Sword": "古老鬥劍",
		"Blue Puniball": "噗尼噗尼珠‧藍",
		"Green Puniball": "噗尼噗尼珠‧綠",
		"Red Puniball": "噗尼噗尼珠‧紅",
		"Black Puniball": "噗尼噗尼珠‧黑",
		"Silver Puniball": "噗尼噗尼珠‧銀",
		"Gold Puniball": "噗尼噗尼珠‧金",
		"Animal Hide": "動物毛皮",
		"Mythical Hide": "幻獸毛皮",
		"Large Bone": "大骨",
		"Beast Fossil": "巨獸化石",
		"Water Beast Fossil": "水獸巨大化石",
		"Water Beast Scale": "水獸鱗片",
		"Cave Bat Wing": "洞窟蝙蝠翅膀",
		"White Swallow's Nest": "白燕舊巢",
		"Beast Fin": "魔獸背鰭",
		"Beast Shell": "魔獸甲殼",
		"Beast Scales": "魔獸鱗片",
		"Giant Bird Feather": "巨鳥破風羽",
		"Giant Bird Egg": "巨鳥蛋",
		"Goat Horn": "山羊角",
		"Demon Claws": "魔爪",
		"Fluffy Wool": "柔軟羊毛",
		"Poison Needle": "劇毒細針",
		"Dragon Wing": "翼龍之翼",
		"Dragon Egg": "翼龍之蛋",
		"Dragon Eye": "龍之眼",
		"Dragon Bone": "龍骨",
		"Dragon Meat": "龍肉",
		"Guardian Armor": "守護者硬甲",
		"Heroic Spirit": "英靈之魂",
		"Giant Puniball": "大噗尼珠",
		"Fairy Horn Adornment": "妖精的大角飾",
		"Giant Claws": "巨大的爪子",
		"Golem Core": "魔巨人核心",
		"Inverted Scale": "逆鱗",
		"Ether Core": "乙太核",
		"Imp's Lost Item": "小惡魔的遺失物",
		"Elemental Force": "元素之力",
		"Twisted Thorns": "交纏之根",
		"Curved Long Nails": "彎曲長爪",
		"Running Beast Crest": "走獸肉冠",
		"Phantom Color Tail": "幻色尾",
		"Wolf Beast's Blade": "狼獸的獵刃",
		"Duet Stock Solution": "二重奏原液",
		"Scintilla Ore": "火花礦石",
		"Lujada's Fairystone": "露水魔石",
		"Pink Puniball": "噗尼噗尼珠‧櫻",
		"Giant Kurken Fruit": "巨大庫肯果",
		"Cow Milk": "牛奶",
		"Giant Claws": "巨大的爪子",
		"White Swallow's Nest": "白燕舊巢",
		"Water Beast Scale": "水獸鱗片",
		"Mythical Hide": "幻獸毛皮",
		"Dragon Meat": "龍肉",
		"Heroic Spirit": "英靈之魂",
		"Dragon Wing": "翼龍之翼",
		"Demon Claws": "魔爪",
		"Dragon Bone": "龍骨",
		"Dragon Eye": "龍之眼",
		"Ether Core": "乙太核",
		"Myria Fish": "萬年魚",
		"Summer Gem": "夏季寶石",
		"Spring Princess": "清水白姫",
		"Giant Beetle": "甲蟲",
		"Corail Saber": "珊瑚砂",
		"Celestial Tears": "天宮之淚",
		"Sky Bubble": "天空泡沫",
		"Rainbow Fish": "彩虹魚",
		"Red Devil": "紅惡魔",
		"Chomping Grass": "咬人草",
		"Solflower": "太陽花",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Campanula": "吊鐘草",
		"Earth's Secret Oils": "大地秘油",
		"Softtail": "柔軟奶油果",
		"Dunkelheit": "一夜花",
		"Emperor Uni": "大王海膽",
		"Light Absorbing Grass": "吸光草",
		"Black Muck": "黑泥",
		"Fire and Ice Crystal": "炎冰結晶",
		"Seal Branch": "封印樹枝",
		"Old Dragon's Claw": "古龍鉤爪",
		"Water Stone": "水環石",
		"Silence Steel": "靜寂金屬",
		"Verdant Moonflower": "深綠之月華",
		"Heavenly Seawater": "天海水",
		"Clearfish": "六花魚",
		"Pine Fruit": "鵬梨果實",
		"Melocotone": "桃色岩鹽",
		"Star Clam": "星形蜆",
		"Gemeater": "食寶石蟲",
		"Tsurugi Mushroom": "劍菇",
		"Floating Petal Stone": "漂浮花石",
		"Verdeum Metal": "碧綠金屬",
		"Wool Flower": "乘風之花",
		"Cleaner Plant": "消毒草",
		"Medicinal Sap": "藥樹液",
		"Immortal Sapling": "不朽林木",
		"Blessed Clouds": "恩惠積雲",
		"Carved Relic": "木雕遺物",
		"Reaper's Scythe": "死神大鐮",
		"Heavenly Rain Thread": "天梅雨之絲",
		"Unstable Lump": "不穩定的聚合體",
		"Ignis Nut": "火焰毬果",
		"Ancient Scroll": "古風卷軸",
		"Torch of the Ages": "遠古燈火",
		"Royal Spun Thread": "王家紡絲",
		"White Sand of Eternity": "久遠白砂",
		"Traveling Grass": "旅行的枯草",
		"White Sand Metal": "白砂金屬",
		"Ametrite": "紫黃礦",
		"Forgotten Pottery": "被遺忘的陶器",
		"Desert Cleaner": "砂漠清潔工",
		"Trifruit": "三角果",
		"Cactus Blossom": "牡丹仙人掌",
		"Mortal Anima": "致命幽魂",
		"Shark Bone": "鯊魚顎骨",
		"Exotic Meat": "稀有的肉",
		"Kala's Translated Texts (Copy)": "卡菈的翻譯文獻‧抄本",
		"Golden Puniball": "噗尼噗尼珠‧黃金",
		"Sandstorm Crystal": "砂塵暴結晶",
		"White Moon's Soul": "白月之魂",
		"Universe Sphere": "宇宙球體",
		"Fairywood": "小妖精木材",
		"Mini Volcano": "小小火山",
		"Seven-Color Pansy": "七色堇",
		"Fairy Sapling": "妖精樹苗",
		"Lava Rock": "岩漿石",
		"Moon Fragment": "月亮碎片",
	},
	"monster": {
		"Blue Puni": "藍噗尼",
		"Green Puni": "綠噗尼",
		"Red Puni": "紅噗尼",
		"Flower Puni": "花噗尼",
		"Black Puni": "黑噗尼",
		"Silver Puni": "銀噗尼",
		"Gold Puni": "金噗尼",
		"Lavender Puni": "薰衣草噗尼",
		"Big Puni": "巨大噗尼",
		"Shining Puni": "發光噗尼",
		"Rafflesia Puni": "大王花噗尼",
		"Darkness Puni": "暗黑噗尼",
		"Precious Puni": "珍奇噗尼",
		"Giant Weasel": "大鼬",
		"Bluefin": "藍鰭鼬",
		"Silky Fur": "柔滑皮鼬",
		"Scarf Bunny": "圍巾兔",
		"Night Hunter": "暗夜獵人",
		"Ruined Corrupter": "毀滅的侵蝕者",
		"Hide Stalker": "暗地追跡者",
		"Loppy Ear": "垂耳兔",
		"Mother Weasel": "大鼬媽媽",
		"Savage Assassin": "野性刺客",
		"Hex Rabbit": "咒術兔",
		"Large Antler": "巨大鹿角",
		"Holy Beast of the Stars": "星辰聖獸",
		"Flower Pixie": "花精",
		"Illuminated Sylph": "微光靈者",
		"Flower Gardener": "護花園丁",
		"Zephyr Pixie": "微風仙子",
		"Eternal Guardian": "悠久守護者",
		"Blazing Maiden": "光熱少女",
		"Hallowed Spirit": "聖光靈體",
		"Plumed Lorelei": "羽毛女妖",
		"Elder Fairy": "妖精長老",
		"Mirage Master": "控幻者",
		"Lunaria Angel": "月光天使",
		"Nightmare Spirit": "惡夢之靈",
		"Schwarzwraith": "黑色巨靈",
		"Sweet Nocturnal ": "美好之夜",
		"Moon Veil": "月之面紗",
		"Stone Golem": "硬石魔巨人",
		"Rock Puppet": "石傀儡",
		"Jewel Guard": "寶石衛兵",
		"Fairystone Puppet": "魔石傀儡",
		"Metal Golem": "金屬魔巨人",
		"Meteorite Doll": "隕石魔偶",
		"Earth Master": "土塊使役者",
		"Rusty Onyx": "鏽瑪瑙巨魔",
		"Colossus Golem": "巨像魔巨人",
		"Eternal Sculpture": "不朽雕像",
		"Boulder Soldier": "巨石士兵",
		"Darkomaton": "暗黑魔巨人",
		"Noir Doll": "漆黑魔偶",
		"Cramberry": "蔓越莓",
		"Harvest Prayer": "祈求豐收者",
		"Horned Sheep": "角綿羊",
		"Ashen Wool": "灰毛綿羊",
		"Fluffy Sheep": "柔毛綿羊",
		"Dreamcatcher": "捕夢者",
		"Giant Sheep": "巨大綿羊",
		"Mindlurker": "灰暗回憶之獸",
		"Mad Beast": "狂暴猛獸",
		"Scaled Armadillo": "鱗甲犰狳",
		"Intact Carapace": "完美甲殼",
		"Tiny Devil": "迷你惡魔",
		"Blue Fiend": "藍惡魔",
		"Hot Evil": "炙熱惡魔",
		"Ash Demon": "灰惡魔",
		"King Devil": "大惡魔",
		"Storm Elemental ": "風暴元素",
		"Icy Crystal": "寒冰水晶",
		"Spirit of Nature": "自然精靈",
		"Scrambled Energy": "能量爭奪者",
		"Disaster Core": "災難核心",
		"Earth Plant": "大地草",
		"Root Spreader": "根莖傳播者",
		"Great Tree Messenger": "大樹使者",
		"Great Mistread": "閃霧狂暴",
		"Yggdrasil": "世界樹",
		"Rageness": "怠惰者",
		"Ground Builder": "大地建築工",
		"Ruler of the Forest": "森林支配者",
		"Spark Riser": "閃耀統籌者",
		"Giant Sloth": "巨大樹懶",
		"Feral Crow": "兇猛鉤爪",
		"Smart Ripper": "狡猾開膛手",
		"Ferocious Hopper": "卑鄙跳躍者",
		"Fierce Hunter": "凶猛獵人",
		"Tyrant": "狂怒暴君",
		"Living Armor": "移動盔甲",
		"Ghost Armor": "鬼魂鎧甲",
		"Honor Guard Armor": "亡國的近衛鎧",
		"Gladiator": "角鬥士",
		"Legendary Warrior": "傳承古強者",
		"Immortal Knight": "不朽騎士",
		"Royal Admiral": "皇家上將",
		"Heavy Warrior Armor": "戰士的大鎧",
		"Noble Paladin": "貴族聖騎士",
		"Great Guardian": "偉大守護者",
		"Demonic Phantom": "幻影幽鬼",
		"Berserker Shadow": "狂戰士之影",
		"Temple Warrior": "神殿戰士",
		"Shattered Breaker": "粉碎破壞者",
		"Stinger": "毒刺",
		"Sharpened Scissors": "銳剪",
		"Pile Bunker": "貫釘",
		"Parching Demon": "旱季惡魔",
		"Dark Scout": "常闇斥候",
		"Spine Rat": "脊柱鼠",
		"Ogre Head": "巨獸首領",
		"Shadow Vanguard": "魅影尖兵",
		"Thrust Hedge": "猛刺之蝟",
		"Shadow Eater": "食影者",
		"Legion Needle": "針山刺蝟",
		"Mini Wyvern": "迷你雙足飛龍",
		"Zephyr Feather": "風羽",
		"Evil Orchis": "惡魔蘭龍",
		"Stout Drake": "大肚龍",
		"Mach Hawk": "馬赫飛翼",
		"Watcher": "守望者",
		"Draconic Lord": "飛龍領主",
		"Giant Maw": "巨咽龍",
		"Mega Wyvern": "巨型雙足飛龍",
		"King of Storms": "風暴之王",
		"Cloud Liner": "雲端行者",
		"Landbound Dragon": "地縛龍",
		"Cursed Wing": "詛咒之翼",
		"Armored Wing": "鎧甲之翼",
		"Steel Raptor": "鋼鐵猛禽",
		"Sprinting Bird": "快跑鳥",
		"Massive Beak": "巨喙鳥",
		"Albatross": "信天翁",
		"Wild Crest": "野生大冠雞",
		"Overwhelming Bird": "狂奔怪鳥",
		"Twilight Songbird": "宵鳴鳥",
		"Lifeless Shadow": "死亡巨鳥之影",
		"Twilight Assassin": "宵闇刺客",
		"Cloak-in-dagger": "身披短刃者",
		"Shadow Assassin ": "暗影刺客",
		"Cipher Code": "暗號代碼",
		"Hell Keeper": "地獄守衛",
		"Slashblader": "斬擊劍狼",
		"Crimson Arms": "緋紅刃狼",
		"Spellblade Wielder": "魔劍好手",
		"Demon Slayer Wolf": "破邪月狼",
		"Sleipnir": "斯雷普尼爾",
		"Hide Shark": "暗穴鯊魚",
		"Megamouth": "大顎鮫",
		"Spinal Fin": "尖晶鰭鯊",
		"Grand Tusk": "巨型獠牙",
		"Sandstorm Tyrant": "砂塵暴君",
		"Desert Lagoon": "沙漠潟湖鯊",
		"Mind Ravager": "思念捕食者",
		"Land Crawler": "盤踞大地的大魚",
		"Soul Cleaver": "斷魂者",
		"Dark General": "常闇將軍",
		"Cluster Beetle": "地殼甲蟲",
		"Shadow Commander": "魅影司令",
		"Horned Demon": "巨角惡魔",
		"Rhino Fiend": "犀角魔鬼",
		"Old Castle Dragon": "古城飛龍",
		"Dragon Lord": "統天霸龍",
		"Dragon of Light": "撕裂黑暗的光龍",
		"Ravaging Queen": "常闇女王",
		"Queen of Shadows": "魅影女王",
		"Crownless Queen": "無冠女王",
		"Floating Skeleton": "懸浮屍骸",
		"Skeleton Emperor ": "骷髏皇帝",
		"Automaton": "自動機器人",
		"Sentry Guard": "哨衛",
		"Elder Treant": "樹人長老",
		"Ancient Dragon": "古代巨龍",
		"Deranged King": "癲狂之王",
		"Gatekeeper": "守門人",
		"Code of the Universe": "萬象大典",
		"Code of the Universe - Final": "萬象大典‧終章",
		"Colossus Soldier": "巨像士兵",
		"Code of the Universe (Arm)": "萬象大典‧巨臂",
		"Weasel Roast": "烤羊肉2號",
		"Lamb Roast": "烤羊肉3號",
		"Orig. Code of the Universe": "萬象原典",
		"Orig. Code of the Universe (Arm)": "萬象原典‧巨臂",
	}
}