localization["chs"] = {
	"ui": {
		"Ryza 3 Material Map Finder": "莱莎的炼金工房3 素材分布查询",
		"Choose a language:": "选择语言：",
		"Choose a map:": "选择地图：",
		"Kurken": "库肯岛",
		"Mainland": "库肯岛周边地区",
		"Cleria": "克莱莉亚地区",
		"Nemed": "内米德地区",
		"Orim": "异界奥灵",
		"Code": "万象大典",
		"Rosca": "罗斯卡岛",
		"Rosca Control Tower": "罗斯卡岛中央控制塔",
		"Ashra-am Baird Outskirts": "王都阿斯拉·阿姆·伯特边境",
		"Choose an item:": "选择道具：",
		"Filter Gathering Tool:": "筛选采集工具：",
		"Hand Maximum Rank": "徒手等级",
		"None": "无",
		"Rank One": "等级1",
		"Rank Two": "等级2",
		"Rank Three": "等级3",
		"Rod Maximum Rank": "手杖等级",
		"Sickle Maximum Rank": "镰刀等级",
		"Axe Maximum Rank": "斧头等级",
		"Hammer Maximum Rank": "锤子等级",
		"Net Maximum Rank": "捕捉网等级",
		"Alchemy Mysteries DLC": "DLC 炼金术之神秘",
		"Art of Adventure DLC": "DLC 冒险之精髓",
		"Search": "搜索",
		"Number found:": "查找结果：",
		"$1 in $2": "$2有 $1 处",
		"Hand Gathering": "徒手采集",
		"Rod Gathering": "手杖采集",
		"Sickle Gathering": "镰刀采集",
		"Axe Gathering": "斧头采集",
		"Hammer Gathering": "锤子采集",
		"Net Gathering": "捕捉网采集",
	},
	"item": {
		"Clean Water": "清澈的水",
		"Goats Milk": "山羊奶",
		"Water Bamboo": "储水竹",
		"Plant Essence": "植物精华",
		"Roteswasser Tonic": "洛特斯瓦萨矿水",
		"Rapwar Water": "梨花水",
		"Foamy Water": "起泡水",
		"Jade Water": "翡翠煌水",
		"Ancient Blue Water": "太古苍水",
		"Curious Aqua": "神秘液体",
		"Black Water": "黑水",
		"Nameless Grass": "无名草",
		"Wasser Wheat": "瓦塞麦",
		"Dry Grass": "焦草",
		"Hill Lettuce": "丘陵生菜",
		"Blue Herb": "蓝色香草",
		"Rishikelp": "利西利藻",
		"Chomping Grass": "咬人草",
		"Sweet Leaf": "甜叶",
		"Ancient Branch": "古树枝",
		"Campanula": "吊钟草",
		"Glowing Diatom": "光硅藻",
		"Lucky Clover": "幸运四叶草",
		"Blue Clover": "蓝诘草",
		"Light Absorbing Grass": "吸光草",
		"Rosen Leaf": "玫瑰叶",
		"Uni": "海胆",
		"Ancient Uni": "古代海胆",
		"Water Uni": "水海胆",
		"Charcoal Uni": "炭海胆",
		"Gold Uni": "黄金海胆",
		"Demon Uni": "鬼角海胆",
		"Emperor Uni": "大王海胆",
		"Health Flower": "忘忧花",
		"Northern Wind Flower": "北风之花",
		"Sunny Honey Flower": "阳气蜜花",
		"Bubble Grass": "肥皂草",
		"Stained Flower": "彩光之花",
		"Caged Flower": "树笼妖花",
		"Spring Princess": "清水白姬",
		"Soul Flower": "散命花",
		"Rose Crystal": "玫瑰水晶",
		"Delphi Rose": "德尔福玫瑰",
		"Polar Cactus": "极地仙人掌",
		"Timeteller": "报时花",
		"Taun": "唐木叶",
		"Tall Taun": "长颈通草",
		"Sapling Branch": "幼树枝叶",
		"Medicinal Moss": "药苔",
		"Fertile Soil": "肥土",
		"Dry Incense": "干燥香",
		"Bitter Root": "苦根",
		"Crimson Grass": "红草",
		"Earth's Secret Oils": "大地秘油",
		"Sage Grass": "仙人草",
		"Life Leaf": "生命叶片",
		"Refueling Extract": "补给精华",
		"Yugdore Water": "优古多尔的涌水",
		"Stinky Trash": "厨余垃圾",
		"Mushroom Powder": "蘑菇孢子",
		"Mispel Seed": "欧楂种子",
		"Resentful Scream": "怨嗟悲鸣",
		"Blessing of Delusion": "虚妄祝福",
		"Dragon Flower": "龙葬兰",
		"Demon Blood": "恶魔之血",
		"Forest Sage": "森林智草",
		"Celestial Tears": "天宫之泪",
		"Solflower": "太阳花",
		"Dunkelheit": "一夜花",
		"Soft Sand": "软砂",
		"Burning Sand": "可燃之砂",
		"Corail Saber": "珊瑚砂",
		"Polluted Humus": "受污染的腐叶土",
		"Emerald Glass": "翡翠玻璃",
		"Seafloor Soil": "水底土",
		"Black Muck": "黑泥",
		"Vortex Sand": "漩涡流砂",
		"Glittering Sand": "闪耀砂粒",
		"Eroded Stone": "风化石材",
		"Nectar Rock": "甘露岩",
		"Nepheline": "霞石",
		"Waterside Moss Stone": "水边苔石",
		"Ethereal Stone": "白灵岩",
		"Ancient Pillar": "古代石柱",
		"Coral Stone": "珊瑚石",
		"Breeze Stone": "微风石",
		"Riverstone": "河石",
		"Blue Flame Riverstone": "河石·苍炎",
		"Hot Saltpeter": "热硝石",
		"Arknite": "方舟夜石",
		"Crimson Ore": "赤热矿",
		"Aqua Ore": "海蓝石矿",
		"Lightning Ore": "闪电矿",
		"Wind Ore": "风矿",
		"Amatite Ore": "赤铁矿",
		"Luminous Rock": "夜光岩",
		"Pentanite": "派恩特夜石",
		"Mordenite": "毛尔迪夜石",
		"Goldinite": "戈尔迪夜石",
		"Degenesis Stone": "创生逆石",
		"Septrin": "圣石",
		"Adamant": "金刚石",
		"Eternal Crystal": "永恒结晶",
		"Small Crystals": "小晶石",
		"Unknown Gemstone": "未知的原石",
		"Glowing Coral": "发光珊瑚",
		"White Shell Pearl": "大贝白珍珠",
		"Black Shell Pearl": "大贝黑珍珠",
		"Amber Fragment": "琥珀碎片",
		"Amber Crystal": "琥珀水晶",
		"Three-Colored Stone": "三色石",
		"Clear Branch": "清莹树枝",
		"Holy Arbor Crystal": "圣树结晶",
		"Underworld Crystal": "异界结晶",
		"Black Glitter Stone": "黑煌石",
		"Rainbow Gemstone": "七煌原石",
		"Dried Lumber": "干燥木屑",
		"Flint Pepper": "燧石胡椒",
		"Explosive Vine": "炸裂藤",
		"Flaming Black Sand": "焰之黑砂",
		"Magma Powder": "岩浆粉",
		"Scrap Paper": "纸屑",
		"Flammable Bark": "易燃树皮",
		"Palma Bark": "帕尔马树皮",
		"Fuel Coconut": "燃料椰子",
		"Natural Oil": "天然油",
		"Amber Oil": "琥珀油",
		"Fire and Ice Crystal": "炎冰结晶",
		"Eternal Fire": "永世之焰",
		"Beast Meat": "兽肉",
		"Fresh Meat": "新鲜的肉",
		"Some Kind of Egg": "未知的蛋",
		"Oil Tree Fruit": "油木果实",
		"Nectar Fruit": "甘露果实",
		"Wild Potato": "野生土豆",
		"Portpea": "波多豆",
		"Red Devil": "红恶魔",
		"Clenoko": "余晖笋",
		"Red King Apple": "王玉苹果",
		"Skull Pumpkin": "颅骨南瓜",
		"Venom Nut": "猛毒果",
		"Palma Fruit": "帕尔马果实",
		"Fresh Berry": "莓果",
		"Werder Nut": "森林核果",
		"Kurken Fruit": "库肯果",
		"Fortune Fruit": "幸运果实",
		"Rainbow Grapevine": "七色葡萄",
		"Summer Gem": "夏季宝石",
		"Softtail": "柔软奶油果",
		"Beehive": "蜂巢",
		"Silver Beehive": "银色蜂巢",
		"Gold Beehive": "金色蜂巢",
		"Bee Haven": "叠层蜂蜜块",
		"Honey Ball": "蜜蜂球巢",
		"Eicheloa": "橡树菇",
		"Mushroom Colony": "群生蘑菇",
		"Brodenbits": "布罗登皮特菇",
		"Utopiechampignon": "尤皮特齿菇",
		"Jellyfish Mushroom": "水母菇",
		"Stool of Nature": "椅菇",
		"Dusk Mushroom": "暗夜贵妇人",
		"Danger Mushroom": "极其危险菇",
		"Jewel Mushroom": "宝晶塞欧伊菇",
		"Golden Crown": "金色王冠",
		"Sardine": "沙丁鱼",
		"Seriole": "黄尾鱼",
		"Pourpremoule": "普鲁姆鲁螺",
		"Crab": "灌木蟹",
		"Pretty Shells": "美丽贝壳",
		"Spikey": "刺刺鱼",
		"Uni Starfish": "海胆海星",
		"Chestnut": "栗子",
		"Rainbow Fish": "彩虹鱼",
		"Mace Fish": "钉锤鱼",
		"Stingray": "污浊魔鬼鱼",
		"Myria Fish": "万年鱼",
		"Lake Master": "湖底之主",
		"Dragonpalace Nautilus": "龙宫鹦鹉螺",
		"Crown Shellfish": "王冠海螺",
		"Imperial Fish": "皇鱼",
		"Seven Stars": "七星虫",
		"Honey Ant": "蜜蚁",
		"Narwhal Grasshopper": "独角蚱蜢",
		"Lantern Fly": "灯笼萤火虫",
		"Rose Bee": "玫瑰蜂",
		"Giant Beetle": "甲虫",
		"Baby Wyrm": "幼虹虫",
		"Crimson Cloak": "绯红斗篷",
		"Spirit Isopod": "灵团虫",
		"Amber Fly": "琥珀飞虫",
		"Lapis Papillion": "娜匹斯蝶",
		"Trihorn": "三角甲虫",
		"Ancient Bug": "王古虫",
		"Rock Schloss": "岩城蟹",
		"Restraint Silk": "钢化蛛丝",
		"Cotton Grass": "绵毛草",
		"Tough Vine": "强韧藤蔓",
		"Arbor Ivy": "大树常春藤",
		"Queen Spider Web": "女王蜘蛛网",
		"Hug of Arachne": "阿拉克妮的拥抱",
		"Eiche": "橡木",
		"Tough Log": "结实的圆木",
		"Mossy Driftwood": "长苔藓的流木",
		"Holy Arbor Branch": "圣树大枝",
		"Palma": "帕尔马木",
		"Fossil Tree": "化石树",
		"Miasma Log": "释放瘴气的倒木",
		"Lightning Tree": "蓄雷树",
		"Ancient Log": "太古老柴",
		"Millennial Tree": "千年树幼树",
		"Wing Plant": "翼叶草",
		"Smoke Signal Flower": "狼烟草",
		"Crispy Mushroom": "焦菇",
		"Sky Bubble": "天空泡沫",
		"Rotwood Miasma": "朽木毒雾",
		"Water Holy Branch": "水圣树树枝",
		"Dragon Breath": "火龙吐息",
		"Fairystone Fragment": "魔石碎片",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Holy Stone Fragment": "圣石碎片",
		"Rainbow Wing Fragment": "虹翼碎片",
		"Magic Tome Piece": "魔导书残页",
		"Old Magic Tome": "陈旧的魔导书",
		"Holy Tree Leaf": "圣树叶",
		"Mystic Sphere": "漂浮球体",
		"Ancient Fossil": "古代生物化石",
		"Forever Ice Block": "永恒冰块",
		"Decayed Iron Pieces": "锈蚀铁片",
		"Rusted Sword": "生锈的剑",
		"Broken Tools": "坏掉的道具",
		"Liquid Metal": "液态金属",
		"Ancient Sword": "古老斗剑",
		"Blue Puniball": "噗尼噗尼珠·蓝",
		"Green Puniball": "噗尼噗尼珠·绿",
		"Red Puniball": "噗尼噗尼珠·红",
		"Black Puniball": "噗尼噗尼珠·黑",
		"Silver Puniball": "噗尼噗尼珠·银",
		"Gold Puniball": "噗尼噗尼珠·金",
		"Animal Hide": "动物毛皮",
		"Mythical Hide": "幻兽毛皮",
		"Large Bone": "大骨",
		"Beast Fossil": "巨兽化石",
		"Water Beast Fossil": "水兽巨大化石",
		"Water Beast Scale": "水兽鳞片",
		"Cave Bat Wing": "洞窟蝙蝠翅膀",
		"White Swallow's Nest": "白燕旧巢",
		"Beast Fin": "魔兽背鳍",
		"Beast Shell": "魔兽甲壳",
		"Beast Scales": "魔兽鳞片",
		"Giant Bird Feather": "巨鸟破风羽",
		"Giant Bird Egg": "巨鸟蛋",
		"Goat Horn": "山羊角",
		"Demon Claws": "魔爪",
		"Fluffy Wool": "柔软羊毛",
		"Poison Needle": "剧毒细针",
		"Dragon Wing": "翼龙之翼",
		"Dragon Egg": "翼龙之蛋",
		"Dragon Eye": "龙之眼",
		"Dragon Bone": "龙骨",
		"Dragon Meat": "龙肉",
		"Guardian Armor": "守护者硬甲",
		"Heroic Spirit": "英灵之魂",
		"Giant Puniball": "大噗尼珠",
		"Fairy Horn Adornment": "妖精的大角饰",
		"Giant Claws": "巨大的爪子",
		"Golem Core": "魔巨人核心",
		"Inverted Scale": "逆鳞",
		"Ether Core": "以太核",
		"Imp's Lost Item": "小恶魔的遗失物",
		"Elemental Force": "元素之力",
		"Twisted Thorns": "交缠之根",
		"Curved Long Nails": "弯曲长爪",
		"Running Beast Crest": "走兽肉冠",
		"Phantom Color Tail": "幻色尾",
		"Wolf Beast's Blade": "狼兽的猎刃",
		"Duet Stock Solution": "二重奏原液",
		"Scintilla Ore": "火花矿石",
		"Lujada's Fairystone": "露水魔石",
		"Pink Puniball": "噗尼噗尼珠·樱",
		"Giant Kurken Fruit": "巨大库肯果",
		"Cow Milk": "牛奶",
		"Giant Claws": "巨大的爪子",
		"White Swallow's Nest": "白燕旧巢",
		"Water Beast Scale": "水兽鳞片",
		"Mythical Hide": "幻兽毛皮",
		"Dragon Meat": "龙肉",
		"Heroic Spirit": "英灵之魂",
		"Dragon Wing": "翼龙之翼",
		"Demon Claws": "魔爪",
		"Dragon Bone": "龙骨",
		"Dragon Eye": "龙之眼",
		"Ether Core": "以太核",
		"Myria Fish": "万年鱼",
		"Summer Gem": "夏季宝石",
		"Spring Princess": "清水白姬",
		"Giant Beetle": "甲虫",
		"Corail Saber": "珊瑚砂",
		"Celestial Tears": "天宫之泪",
		"Sky Bubble": "天空泡沫",
		"Rainbow Fish": "彩虹鱼",
		"Red Devil": "红恶魔",
		"Chomping Grass": "咬人草",
		"Solflower": "太阳花",
		"Dark Crystal Fragment": "暗水晶碎片",
		"Campanula": "吊钟草",
		"Earth's Secret Oils": "大地秘油",
		"Softtail": "柔软奶油果",
		"Dunkelheit": "一夜花",
		"Emperor Uni": "大王海胆",
		"Light Absorbing Grass": "吸光草",
		"Black Muck": "黑泥",
		"Fire and Ice Crystal": "炎冰结晶",
		"Seal Branch": "封印树枝",
		"Old Dragon's Claw": "古龙钩爪",
		"Water Stone": "水环石",
		"Silence Steel": "静寂金属",
		"Verdant Moonflower": "深绿之月华",
		"Heavenly Seawater": "天海水",
		"Clearfish": "六花鱼",
		"Pine Fruit": "鹏梨果实",
		"Melocotone": "桃色岩盐",
		"Star Clam": "星形蚬",
		"Gemeater": "食宝石虫",
		"Tsurugi Mushroom": "剑菇",
		"Floating Petal Stone": "漂浮花石",
		"Verdeum Metal": "碧绿金属",
		"Wool Flower": "乘风之花",
		"Cleaner Plant": "消毒草",
		"Medicinal Sap": "药树液",
		"Immortal Sapling": "不朽林木",
		"Blessed Clouds": "恩惠积云",
		"Carved Relic": "木雕遗物",
		"Reaper's Scythe": "死神大镰",
		"Heavenly Rain Thread": "天梅雨之丝",
		"Unstable Lump": "不稳定的聚合体",
		"Ignis Nut": "火焰松果",
		"Ancient Scroll": "古风卷轴",
		"Torch of the Ages": "远古灯火",
		"Royal Spun Thread": "王家纺丝",
		"White Sand of Eternity": "久远白砂",
		"Traveling Grass": "旅行的枯草",
		"White Sand Metal": "白砂金属",
		"Ametrite": "紫黄矿",
		"Forgotten Pottery": "被遗忘的陶器",
		"Desert Cleaner": "沙漠清洁工",
		"Trifruit": "三角果",
		"Cactus Blossom": "牡丹仙人掌",
		"Mortal Anima": "致命幽魂",
		"Shark Bone": "鲨鱼颚骨",
		"Exotic Meat": "稀有的肉",
		"Kala's Translated Texts (Copy)": "卡菈的翻译文献·抄本",
		"Golden Puniball": "噗尼噗尼珠·黄金",
		"Sandstorm Crystal": "沙尘暴结晶",
		"White Moon's Soul": "白月之魂",
		"Universe Sphere": "宇宙球体",
		"Fairywood": "小妖精木材",
		"Mini Volcano": "小小火山",
		"Seven-Color Pansy": "七色堇",
		"Fairy Sapling": "妖精树苗",
		"Lava Rock": "岩浆石",
		"Moon Fragment": "月亮碎片",
	},
	"monster": {
		"Blue Puni": "蓝噗尼",
		"Green Puni": "绿噗尼",
		"Red Puni": "红噗尼",
		"Flower Puni": "花噗尼",
		"Black Puni": "黑噗尼",
		"Silver Puni": "银噗尼",
		"Gold Puni": "金噗尼",
		"Lavender Puni": "薰衣草噗尼",
		"Big Puni": "巨大噗尼",
		"Shining Puni": "发光噗尼",
		"Rafflesia Puni": "大王花噗尼",
		"Darkness Puni": "暗黑噗尼",
		"Precious Puni": "珍奇噗尼",
		"Giant Weasel": "大鼬",
		"Bluefin": "蓝鳍鼬",
		"Silky Fur": "柔滑皮鼬",
		"Scarf Bunny": "围巾兔",
		"Night Hunter": "夜猎人",
		"Ruined Corrupter": "毁灭的侵蚀者",
		"Hide Stalker": "暗地追迹者",
		"Loppy Ear": "垂耳兔",
		"Mother Weasel": "大鼬妈妈",
		"Savage Assassin": "野性刺客",
		"Hex Rabbit": "咒术兔",
		"Large Antler": "巨大鹿角",
		"Holy Beast of the Stars": "星辰圣兽",
		"Flower Pixie": "花精",
		"Illuminated Sylph": "微光灵者",
		"Flower Gardener": "护花园丁",
		"Zephyr Pixie": "微风仙子",
		"Eternal Guardian": "悠久守护者",
		"Blazing Maiden": "光热少女",
		"Hallowed Spirit": "神圣鬼魂",
		"Plumed Lorelei": "羽毛女妖",
		"Elder Fairy": "年长妖精",
		"Mirage Master": "控幻者",
		"Lunaria Angel": "露娜莉亚天使",
		"Nightmare Spirit": "恶梦之灵",
		"Schwarzwraith": "黑色巨灵",
		"Sweet Nocturnal ": "美好之夜",
		"Moon Veil": "月之面纱",
		"Stone Golem": "硬石魔巨人",
		"Rock Puppet": "石傀儡",
		"Jewel Guard": "宝石卫兵",
		"Fairystone Puppet": "魔石傀儡",
		"Metal Golem": "金属魔巨人",
		"Meteorite Doll": "陨石魔偶",
		"Earth Master": "土块使役者",
		"Rusty Onyx": "锈玛瑙巨魔",
		"Colossus Golem": "巨像魔巨人",
		"Eternal Sculpture": "不朽雕像",
		"Boulder Soldier": "巨石士兵",
		"Darkomaton": "暗黑魔巨人",
		"Noir Doll": "漆黑魔偶",
		"Cramberry": "蔓越莓",
		"Harvest Prayer": "祈求丰收者",
		"Horned Sheep": "角绵羊",
		"Ashen Wool": "灰毛绵羊",
		"Fluffy Sheep": "柔毛绵羊",
		"Dreamcatcher": "捕梦者",
		"Giant Sheep": "巨大绵羊",
		"Mindlurker": "灰暗回忆之兽",
		"Mad Beast": "狂暴猛兽",
		"Scaled Armadillo": "鳞甲犰狳",
		"Intact Carapace": "完美甲壳",
		"Tiny Devil": "迷你恶魔",
		"Blue Fiend": "蓝恶魔",
		"Hot Evil": "炙热恶魔",
		"Ash Demon": "灰恶魔",
		"King Devil": "大恶魔",
		"Storm Elemental ": "风暴元素",
		"Icy Crystal": "寒冰水晶",
		"Spirit of Nature": "自然精灵",
		"Scrambled Energy": "能量争夺者",
		"Disaster Core": "灾难核心",
		"Earth Plant": "大地草",
		"Root Spreader": "根茎传播者",
		"Great Tree Messenger": "大树使者",
		"Great Mistread": "闪雾狂暴",
		"Yggdrasil": "世界树",
		"Rageness": "怠惰者",
		"Ground Builder": "大地建筑工",
		"Ruler of the Forest": "森林支配者",
		"Spark Riser": "闪耀统筹者",
		"Giant Sloth": "巨大树懒",
		"Feral Crow": "凶猛钩爪",
		"Smart Ripper": "狡猾开膛手",
		"Ferocious Hopper": "卑鄙跳跃者",
		"Fierce Hunter": "凶猛猎人",
		"Tyrant": "狂怒暴君",
		"Living Armor": "移动盔甲",
		"Ghost Armor": "鬼魂铠甲",
		"Honor Guard Armor": "亡国的近卫铠",
		"Gladiator": "角斗士",
		"Legendary Warrior": "传说的古代勇士",
		"Immortal Knight": "永世的骑士",
		"Royal Admiral": "皇家上将",
		"Heavy Warrior Armor": "战士的大铠",
		"Noble Paladin": "贵族圣骑士",
		"Great Guardian": "伟大守护者",
		"Demonic Phantom": "幻影幽鬼",
		"Berserker Shadow": "狂战士之影",
		"Temple Warrior": "神殿战士",
		"Shattered Breaker": "粉碎破坏者",
		"Stinger": "毒刺",
		"Sharpened Scissors": "锐剪",
		"Pile Bunker": "贯钉",
		"Parching Demon": "干渴的恶魔",
		"Dark Scout": "常暗的斥候",
		"Spine Rat": "脊柱鼠",
		"Ogre Head": "巨人兽首领",
		"Shadow Vanguard": "魅影尖兵",
		"Thrust Hedge": "猛刺之猬",
		"Shadow Eater": "食影者",
		"Legion Needle": "针山刺猬",
		"Mini Wyvern": "迷你双足飞龙",
		"Zephyr Feather": "风羽",
		"Evil Orchis": "邪恶的兰花",
		"Stout Drake": "大肚龙",
		"Mach Hawk": "马赫飞翼",
		"Watcher": "守望者",
		"Draconic Lord": "龙之君王",
		"Giant Maw": "巨咽龙",
		"Mega Wyvern": "巨型双足飞龙",
		"King of Storms": "风暴之王",
		"Cloud Liner": "云轮",
		"Landbound Dragon": "地缚龙",
		"Cursed Wing": "诅咒之翼",
		"Armored Wing": "铠甲之翼",
		"Steel Raptor": "钢铁猛禽",
		"Sprinting Bird": "快跑鸟",
		"Massive Beak": "巨喙鸟",
		"Albatross": "信天翁",
		"Wild Crest": "野生大冠鸡",
		"Overwhelming Bird": "狂奔怪鸟",
		"Twilight Songbird": "宵鸣鸟",
		"Lifeless Shadow": "死亡巨鸟之影",
		"Twilight Assassin": "宵暗刺客",
		"Cloak-in-dagger": "身披短刃者",
		"Shadow Assassin ": "暗影刺客",
		"Cipher Code": "暗号代码",
		"Hell Keeper": "地狱守卫",
		"Slashblader": "斩击剑狼",
		"Crimson Arms": "绯红刃狼",
		"Spellblade Wielder": "魔剑好手",
		"Demon Slayer Wolf": "破邪月狼",
		"Sleipnir": "斯雷普尼尔",
		"Hide Shark": "暗穴鲨鱼",
		"Megamouth": "大颚鲛",
		"Spinal Fin": "尖晶鳍鲨",
		"Grand Tusk": "巨型獠牙",
		"Sandstorm Tyrant": "砂尘暴君",
		"Desert Lagoon": "沙漠潟湖鲨",
		"Mind Ravager": "思念捕食者",
		"Land Crawler": "盘踞大地的大鱼",
		"Soul Cleaver": "断魂者",
		"Dark General": "常暗将军",
		"Cluster Beetle": "地壳甲虫",
		"Shadow Commander": "魅影司令",
		"Horned Demon": "巨角恶魔",
		"Rhino Fiend": "犀角魔鬼",
		"Old Castle Dragon": "古城飞龙",
		"Dragon Lord": "统天霸龙",
		"Dragon of Light": "撕裂黑暗的光龙",
		"Ravaging Queen": "常暗女王",
		"Queen of Shadows": "魅影女王",
		"Crownless Queen": "无冠女王",
		"Floating Skeleton": "悬浮尸骸",
		"Skeleton Emperor ": "骷髅皇帝",
		"Automaton": "自动机器人",
		"Sentry Guard": "哨卫",
		"Elder Treant": "树人长老",
		"Ancient Dragon": "古代巨龙",
		"Deranged King": "癫狂之王",
		"Gatekeeper": "守门人",
		"Code of the Universe": "万象大典",
		"Code of the Universe - Final": "万象大典·终章",
		"Colossus Soldier": "巨像士兵",
		"Code of the Universe (Arm)": "万象大典·巨臂",
		"Weasel Roast": "烤羊肉2号",
		"Lamb Roast": "烤羊肉3号",
		"Orig. Code of the Universe": "万象原典",
		"Orig. Code of the Universe (Arm)": "万象原典·巨臂",
	}
}